/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.features;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Observable;
import org.softlang.company.Subunit;
import org.softlang.company.impl.bean.DepartmentImpl;
import org.softlang.company.impl.bean.EmployeeImpl;
import org.softlang.features.Precedence;

@RunWith(EvoSuiteRunner.class)
public class TestPrecedence_3 {


  //Test case number: 3
  /*
   * 7 covered goals:
   * 1 Weak Mutation 16: org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V:20 - ReplaceComparisonOperator < -> -2
   * 2 org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V: I39 Branch 5 IFLT L20 - true
   * 3 Weak Mutation 10: org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V:20 - DeleteStatement: getSalary()D
   * 4 Weak Mutation 11: org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V:20 - DeleteStatement: getManager()Lorg/softlang/company/Employee;
   * 5 Weak Mutation 12: org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V:20 - DeleteStatement: getSalary()D
   * 6 Weak Mutation 13: org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V:20 - DeleteStatement: doubleSub(DD)I
   * 7 Weak Mutation 16: org.softlang.features.Precedence.update(Ljava/util/Observable;Ljava/lang/Object;)V:20 - ReplaceComparisonOperator < -> -2
   */
  @Test
  public void test3()  throws Throwable  {
      Precedence precedence0 = new Precedence();
      EmployeeImpl employeeImpl0 = new EmployeeImpl();
      DepartmentImpl departmentImpl0 = new DepartmentImpl();
      departmentImpl0.add((Subunit) employeeImpl0);
      employeeImpl0.setManager(true);
      EmployeeImpl employeeImpl1 = new EmployeeImpl();
      departmentImpl0.add((Subunit) employeeImpl1);
      employeeImpl1.setSalary((-121.68200415013897));
      precedence0.update((Observable) employeeImpl1, (Object) "salary");
      assertNotSame(employeeImpl1, employeeImpl0);
  }
}
