/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.compat;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.compat.DbCompat;
import com.sleepycat.je.CursorConfig;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.SecondaryConfig;

@RunWith(EvoSuiteRunner.class)
public class TestDbCompat_11 {


  //Test case number: 11
  /*
   * 9 covered goals:
   * 1 Weak Mutation 11: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:75 - DeleteStatement: getReadCommitted()Z
   * 2 Weak Mutation 12: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:75 - DeleteStatement: setReadCommitted(Z)V
   * 3 Weak Mutation 13: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:76 - DeleteStatement: getReadUncommitted()Z
   * 4 Weak Mutation 14: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:76 - DeleteStatement: setReadUncommitted(Z)V
   * 5 com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;: root-Branch
   * 6 Weak Mutation 11: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:75 - DeleteStatement: getReadCommitted()Z
   * 7 Weak Mutation 12: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:75 - DeleteStatement: setReadCommitted(Z)V
   * 8 Weak Mutation 13: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:76 - DeleteStatement: getReadUncommitted()Z
   * 9 Weak Mutation 14: com.sleepycat.compat.DbCompat.cloneCursorConfig(Lcom/sleepycat/je/CursorConfig;)Lcom/sleepycat/je/CursorConfig;:76 - DeleteStatement: setReadUncommitted(Z)V
   */
  @Test
  public void test11()  throws Throwable  {
      CursorConfig cursorConfig0 = CursorConfig.READ_COMMITTED;
      CursorConfig cursorConfig1 = DbCompat.cloneCursorConfig(cursorConfig0);
      assertEquals(false, cursorConfig1.getReadCommitted());
  }
}
