/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.utilint;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.utilint.TinyHashSet;

@RunWith(EvoSuiteRunner.class)
public class TestTinyHashSet_0 {


  //Test case number: 0
  /*
   * 9 covered goals:
   * 1 Weak Mutation 23: com.sleepycat.je.utilint.TinyHashSet.size()I:18 - ReplaceComparisonOperator = null -> != null
   * 2 Weak Mutation 26: com.sleepycat.je.utilint.TinyHashSet.size()I:21 - ReplaceComparisonOperator = null -> != null
   * 3 Weak Mutation 29: com.sleepycat.je.utilint.TinyHashSet.size()I:25 - ReplaceConstant - 0 -> 1
   * 4 com.sleepycat.je.utilint.TinyHashSet.<init>()V: root-Branch
   * 5 com.sleepycat.je.utilint.TinyHashSet.size()I: I4 Branch 6 IFNULL L18 - true
   * 6 com.sleepycat.je.utilint.TinyHashSet.size()I: I13 Branch 7 IFNULL L21 - true
   * 7 Weak Mutation 23: com.sleepycat.je.utilint.TinyHashSet.size()I:18 - ReplaceComparisonOperator = null -> != null
   * 8 Weak Mutation 26: com.sleepycat.je.utilint.TinyHashSet.size()I:21 - ReplaceComparisonOperator = null -> != null
   * 9 Weak Mutation 29: com.sleepycat.je.utilint.TinyHashSet.size()I:25 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test0()  throws Throwable  {
      TinyHashSet tinyHashSet0 = new TinyHashSet();
      int int0 = tinyHashSet0.size();
      assertEquals(0, int0);
  }
}
