/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.utilint;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.utilint.TinyHashSet;

@RunWith(EvoSuiteRunner.class)
public class TestTinyHashSet_5 {


  //Test case number: 5
  /*
   * 7 covered goals:
   * 1 Weak Mutation 58: com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z:48 - DeleteField: setLjava/util/Set;
   * 2 Weak Mutation 61: com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z:49 - DeleteStatement: add(Ljava/lang/Object;)Z
   * 3 Weak Mutation 60: com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z:49 - DeleteField: setLjava/util/Set;
   * 4 com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z: I18 Branch 18 IFNULL L48 - false
   * 5 Weak Mutation 58: com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z:48 - DeleteField: setLjava/util/Set;
   * 6 Weak Mutation 61: com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z:49 - DeleteStatement: add(Ljava/lang/Object;)Z
   * 7 Weak Mutation 60: com.sleepycat.je.utilint.TinyHashSet.add(Ljava/lang/Object;)Z:49 - DeleteField: setLjava/util/Set;
   */
  @Test
  public void test5()  throws Throwable  {
      TinyHashSet tinyHashSet0 = new TinyHashSet();
      tinyHashSet0.add((Object) tinyHashSet0);
      tinyHashSet0.add((Object) tinyHashSet0);
      Object object0 = new Object();
      boolean boolean0 = tinyHashSet0.add(object0);
      assertEquals(2, tinyHashSet0.size());
      assertEquals(true, boolean0);
  }
}
