/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.utilint;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.utilint.HexFormatter;

@RunWith(EvoSuiteRunner.class)
public class TestHexFormatter {


  //Test case number: 0
  /*
   * 45 covered goals:
   * 1 Weak Mutation 0: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:5 - InsertUnaryOp Negation of l
   * 2 Weak Mutation 1: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:5 - DeleteStatement: toHexString(J)Ljava/lang/String;
   * 3 Weak Mutation 2: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:5 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 4 Weak Mutation 3: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 0 -> 1
   * 5 Weak Mutation 4: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 0000000000000000 -> 
   * 6 Weak Mutation 5: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 0 -> 1
   * 7 Weak Mutation 6: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 0
   * 8 Weak Mutation 7: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 1
   * 9 Weak Mutation 8: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> -1
   * 10 Weak Mutation 9: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 15
   * 11 Weak Mutation 10: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 17
   * 12 Weak Mutation 11: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - DeleteStatement: length()I
   * 13 Weak Mutation 12: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> +
   * 14 Weak Mutation 13: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> %
   * 15 Weak Mutation 14: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> /
   * 16 Weak Mutation 15: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> *
   * 17 Weak Mutation 17: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - DeleteStatement: insert(ILjava/lang/String;)Ljava/lang/StringBuffer;
   * 18 Weak Mutation 16: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - DeleteStatement: substring(II)Ljava/lang/String;
   * 19 Weak Mutation 19: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:7 - ReplaceConstant - 0x -> 
   * 20 Weak Mutation 18: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:7 - ReplaceConstant - 0 -> 1
   * 21 Weak Mutation 20: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:7 - DeleteStatement: insert(ILjava/lang/String;)Ljava/lang/StringBuffer;
   * 22 Weak Mutation 21: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:8 - DeleteStatement: toString()Ljava/lang/String;
   * 23 com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;: root-Branch
   * 24 Weak Mutation 0: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:5 - InsertUnaryOp Negation of l
   * 25 Weak Mutation 1: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:5 - DeleteStatement: toHexString(J)Ljava/lang/String;
   * 26 Weak Mutation 2: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:5 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 27 Weak Mutation 3: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 0 -> 1
   * 28 Weak Mutation 4: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 0000000000000000 -> 
   * 29 Weak Mutation 5: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 0 -> 1
   * 30 Weak Mutation 6: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 0
   * 31 Weak Mutation 7: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 1
   * 32 Weak Mutation 8: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> -1
   * 33 Weak Mutation 9: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 15
   * 34 Weak Mutation 10: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceConstant - 16 -> 17
   * 35 Weak Mutation 11: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - DeleteStatement: length()I
   * 36 Weak Mutation 12: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> +
   * 37 Weak Mutation 13: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> %
   * 38 Weak Mutation 14: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> /
   * 39 Weak Mutation 15: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - ReplaceArithmeticOperator - -> *
   * 40 Weak Mutation 17: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - DeleteStatement: insert(ILjava/lang/String;)Ljava/lang/StringBuffer;
   * 41 Weak Mutation 16: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:6 - DeleteStatement: substring(II)Ljava/lang/String;
   * 42 Weak Mutation 19: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:7 - ReplaceConstant - 0x -> 
   * 43 Weak Mutation 18: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:7 - ReplaceConstant - 0 -> 1
   * 44 Weak Mutation 21: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:8 - DeleteStatement: toString()Ljava/lang/String;
   * 45 Weak Mutation 20: com.sleepycat.je.utilint.HexFormatter.formatLong(J)Ljava/lang/String;:7 - DeleteStatement: insert(ILjava/lang/String;)Ljava/lang/StringBuffer;
   */
  @Test
  public void test0()  throws Throwable  {
      String string0 = HexFormatter.formatLong(1197L);
      assertEquals("0x00000000000004ad", string0);
      assertNotNull(string0);
  }
}
