/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.utilint;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.utilint.TinyHashSet;
import java.util.Iterator;
import java.util.Set;

@RunWith(EvoSuiteRunner.class)
public class TestTinyHashSet_11 {


  //Test case number: 11
  /*
   * 16 covered goals:
   * 1 Weak Mutation 5: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z:94 - DeleteField: returnedTheObjectZ
   * 2 Weak Mutation 8: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z:94 - ReplaceConstant - 0 -> 1
   * 3 Weak Mutation 9: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:97 - InsertUnaryOp Negation
   * 4 Weak Mutation 11: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:97 - ReplaceComparisonOperator == -> !=
   * 5 Weak Mutation 12: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:100 - ReplaceConstant - 1 -> 0
   * 6 Weak Mutation 13: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:101 - DeleteField: theObjectLjava/lang/Object;
   * 7 com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z: I4 Branch 2 IFNE L94 - true
   * 8 com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;: I4 Branch 3 IFEQ L97 - true
   * 9 Weak Mutation 4: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z:94 - InsertUnaryOp Negation
   * 10 Weak Mutation 6: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z:94 - ReplaceComparisonOperator != -> ==
   * 11 Weak Mutation 5: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z:94 - DeleteField: returnedTheObjectZ
   * 12 Weak Mutation 8: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.hasNext()Z:94 - ReplaceConstant - 0 -> 1
   * 13 Weak Mutation 9: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:97 - InsertUnaryOp Negation
   * 14 Weak Mutation 11: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:97 - ReplaceComparisonOperator == -> !=
   * 15 Weak Mutation 12: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:100 - ReplaceConstant - 1 -> 0
   * 16 Weak Mutation 13: com.sleepycat.je.utilint.TinyHashSet$SingleElementIterator.next()Ljava/lang/Object;:101 - DeleteField: theObjectLjava/lang/Object;
   */
  @Test
  public void test11()  throws Throwable  {
      TinyHashSet tinyHashSet0 = new TinyHashSet();
      TinyHashSet.SingleElementIterator tinyHashSet_SingleElementIterator0 = new TinyHashSet.SingleElementIterator((Object) "", tinyHashSet0);
      String string0 = (String)tinyHashSet_SingleElementIterator0.next();
      assertNotNull(string0);
      
      boolean boolean0 = tinyHashSet_SingleElementIterator0.hasNext();
      assertEquals(true, tinyHashSet_SingleElementIterator0.returnedTheObject);
      assertEquals(false, boolean0);
  }
}
