#!/bin/bash

source common




### attribute types not supported: integer, string 
## must provide a minimum number of observation for this one to work
# METHOD="weka.classifiers.trees.J48"
# DATASET="./data/unreal.ids.arff"

### attribute types not supported: integer, string, REAL
METHOD=weka.associations.Apriori
DATASET="./data/unreal.noids.arff"

java -cp .:$LIBSDIR/weka.jar "$METHOD" -t $DATASET