#!/bin/bash

BASEDIR="$HOME/git/spl-test-amplification"
LIBSDIR="$BASEDIR/libs"
JAVASCRIPTSDIR="$BASEDIR/java-scripts"
EVOSUITE="$LIBSDIR/evosuite-20130504.jar"
JUNIT="$LIBSDIR/junit-4.11.jar"
LOG4J="$LIBSDIR/log4j-1.2.13.jar"
SKARINGA="$LIBSDIR/skaringa-r3p7.jar"
XSTREAM="$LIBSDIR/xstream-1.1.3.jar"
JUNIT3="$LIBSDIR/junit-3.8.1.jar"

export BASEDIR
export LIBSDIR
export EVOSUITE
export JUNIT
export JUNIT3
export LOG4J
export SKARINGA
export XSTREAM