#!/bin/bash

INPUTDIR=$1

## time budget for generating tests 
## for each class under $INPUTDIR
TIMEOUT=120

## calling evosuite
java \
    -jar $EVOSUITE \
    -generateSuite \
    -cp ${JUNIT}:${LOG4J}:${SKARINGA}:${XSTREAM}:${JUNIT3} \
    -target $INPUTDIR \
    -Dsearch_budget=$TIMEOUT \
    -Doutput_granularity=TESTCASE \
    -Dcriterion=weakMutation \
    -Dstopping_condition=MaxTime