/*
 * This file was automatically generated by EvoSuite
 */

package org.prevayler.foundation;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.io.IOException;
import org.prevayler.foundation.FileManager;

@RunWith(EvoSuiteRunner.class)
public class TestFileManager_1 {


  //Test case number: 1
  /*
   * 16 covered goals:
   * 1 Weak Mutation 11: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - ReplaceConstant - Path exists but is not a directory:  -> 
   * 2 Weak Mutation 12: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 3 Weak Mutation 13: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
   * 4 Weak Mutation 14: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: toString()Ljava/lang/String;
   * 5 org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V: I24 Branch 3 IFNE L12 - false
   * 6 Weak Mutation 1: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:11 - DeleteStatement: exists()Z
   * 7 Weak Mutation 2: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:11 - ReplaceComparisonOperator != -> ==
   * 8 Weak Mutation 9: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: isDirectory()Z
   * 9 Weak Mutation 10: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - ReplaceComparisonOperator != -> ==
   * 10 Weak Mutation 9: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: isDirectory()Z
   * 11 Weak Mutation 10: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - ReplaceComparisonOperator != -> ==
   * 12 Weak Mutation 11: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - ReplaceConstant - Path exists but is not a directory:  -> 
   * 13 Weak Mutation 12: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 14 Weak Mutation 13: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
   * 15 Weak Mutation 14: org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V:12 - DeleteStatement: toString()Ljava/lang/String;
   * 16 org.prevayler.foundation.FileManager.produceDirectory(Ljava/io/File;)V: I4 Branch 1 IFNE L11 - true
   */
  @Test
  public void test1()  throws Throwable  {
      File file0 = File.createTempFile("?)R@", "?)R@");
      try {
        FileManager.produceDirectory(file0);
        fail("Expecting exception: IOException");
      } catch(IOException e) {
        /*
         * Path exists but is not a directory: /var/folders/nq/zr797mk520g827f_9zncfn9r0000gn/T/?)R@4434820274983178803?)R@
         */
      }
  }
}
