/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.util.UtfOps;

@RunWith(EvoSuiteRunner.class)
public class TestUtfOps_16 {


  //Test case number: 16
  /*
   * 9 covered goals:
   * 1 com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I: I39 Branch 40 TABLESWITCH L130 Case 14 - true
   * 2 com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I: I110 Branch 43 IF_ICMPNE L152 - true
   * 3 Weak Mutation 117: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:127 - InsertUnaryOp IINC -1
   * 4 Weak Mutation 116: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:127 - InsertUnaryOp IINC 1
   * 5 Weak Mutation 115: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:127 - InsertUnaryOp Negation
   * 6 Weak Mutation 129: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:128 - InsertUnaryOp Negation
   * 7 Weak Mutation 131: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:128 - InsertUnaryOp IINC -1
   * 8 Weak Mutation 130: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:128 - InsertUnaryOp IINC 1
   * 9 Weak Mutation 159: com.sleepycat.util.UtfOps.bytesToChars([BI[CIIZ)I:130 - ReplaceBitwiseOperator & -> |
   */
  @Test
  public void test16()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-24);
      char[] charArray0 = new char[6];
      try {
        UtfOps.bytesToChars(byteArray0, 0, charArray0, 0, 49, true);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }
}
