/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.util.FastInputStream;
import java.io.IOException;

@RunWith(EvoSuiteRunner.class)
public class TestFastInputStream_9 {


  //Test case number: 9
  /*
   * 17 covered goals:
   * 1 Weak Mutation 76: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC -1
   * 2 Weak Mutation 77: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp Negation
   * 3 Weak Mutation 78: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC 1
   * 4 Weak Mutation 79: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC -1
   * 5 Weak Mutation 74: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp Negation
   * 6 Weak Mutation 75: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC 1
   * 7 Weak Mutation 80: com.sleepycat.util.FastInputStream.read([BII)I:65 - DeleteStatement: readFast([BII)I
   * 8 Weak Mutation 141: com.sleepycat.util.FastInputStream.readFast([BII)I:93 - ReplaceComparisonOperator <= -> ==
   * 9 com.sleepycat.util.FastInputStream.read([BII)I: root-Branch
   * 10 Weak Mutation 76: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC -1
   * 11 Weak Mutation 77: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp Negation
   * 12 Weak Mutation 78: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC 1
   * 13 Weak Mutation 79: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC -1
   * 14 Weak Mutation 74: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp Negation
   * 15 Weak Mutation 75: com.sleepycat.util.FastInputStream.read([BII)I:65 - InsertUnaryOp IINC 1
   * 16 Weak Mutation 80: com.sleepycat.util.FastInputStream.read([BII)I:65 - DeleteStatement: readFast([BII)I
   * 17 Weak Mutation 141: com.sleepycat.util.FastInputStream.readFast([BII)I:93 - ReplaceComparisonOperator <= -> ==
   */
  @Test
  public void test9()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      FastInputStream fastInputStream0 = new FastInputStream(byteArray0);
      // Undeclared exception!
      try {
        fastInputStream0.read(byteArray0, (-1), (int) (byte) (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }
}
