/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.company.impl.pojo;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.softlang.company.impl.pojo.DepartmentImpl;

@RunWith(EvoSuiteRunner.class)
public class TestContainerImpl_0 {


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 Weak Mutation 0: org.softlang.company.impl.pojo.ContainerImpl.subunits()Ljava/lang/Iterable;:11 - DeleteField: subunitsLjava/util/List;
   * 2 org.softlang.company.impl.pojo.ContainerImpl.<init>()V: root-Branch
   * 3 org.softlang.company.impl.pojo.ContainerImpl.subunits()Ljava/lang/Iterable;: root-Branch
   * 4 Weak Mutation 0: org.softlang.company.impl.pojo.ContainerImpl.subunits()Ljava/lang/Iterable;:11 - DeleteField: subunitsLjava/util/List;
   */
  @Test
  public void test0()  throws Throwable  {
      DepartmentImpl departmentImpl0 = new DepartmentImpl();
      Iterable<?> iterable0 = departmentImpl0.subunits();
      assertNotNull(iterable0);
  }
}
