/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.company.impl.pojo;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.softlang.company.impl.pojo.CompanyImpl;

@RunWith(EvoSuiteRunner.class)
public class TestComponentImpl_0 {


  //Test case number: 0
  /*
   * 5 covered goals:
   * 1 Weak Mutation 0: org.softlang.company.impl.pojo.ComponentImpl.getName()Ljava/lang/String;:9 - DeleteField: nameLjava/lang/String;
   * 2 org.softlang.company.impl.pojo.ComponentImpl.<init>()V: root-Branch
   * 3 org.softlang.company.impl.pojo.ComponentImpl.getName()Ljava/lang/String;: root-Branch
   * 4 org.softlang.company.impl.pojo.ComponentImpl.setName(Ljava/lang/String;)V: root-Branch
   * 5 Weak Mutation 0: org.softlang.company.impl.pojo.ComponentImpl.getName()Ljava/lang/String;:9 - DeleteField: nameLjava/lang/String;
   */
  @Test
  public void test0()  throws Throwable  {
      CompanyImpl companyImpl0 = new CompanyImpl();
      companyImpl0.setName("");
      String string0 = companyImpl0.getName();
      assertEquals("", string0);
  }
}
