/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.company.impl.pojo;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.softlang.company.Subunit;
import org.softlang.company.impl.pojo.DepartmentImpl;
import org.softlang.company.impl.pojo.EmployeeImpl;

@RunWith(EvoSuiteRunner.class)
public class TestContainerImpl_1 {


  //Test case number: 1
  /*
   * 5 covered goals:
   * 1 Weak Mutation 1: org.softlang.company.impl.pojo.ContainerImpl.add(Lorg/softlang/company/Subunit;)Z:14 - DeleteField: subunitsLjava/util/List;
   * 2 Weak Mutation 2: org.softlang.company.impl.pojo.ContainerImpl.add(Lorg/softlang/company/Subunit;)Z:14 - DeleteStatement: add(Ljava/lang/Object;)Z
   * 3 org.softlang.company.impl.pojo.ContainerImpl.add(Lorg/softlang/company/Subunit;)Z: root-Branch
   * 4 Weak Mutation 1: org.softlang.company.impl.pojo.ContainerImpl.add(Lorg/softlang/company/Subunit;)Z:14 - DeleteField: subunitsLjava/util/List;
   * 5 Weak Mutation 2: org.softlang.company.impl.pojo.ContainerImpl.add(Lorg/softlang/company/Subunit;)Z:14 - DeleteStatement: add(Ljava/lang/Object;)Z
   */
  @Test
  public void test1()  throws Throwable  {
      DepartmentImpl departmentImpl0 = new DepartmentImpl();
      EmployeeImpl employeeImpl0 = new EmployeeImpl();
      boolean boolean0 = departmentImpl0.add((Subunit) employeeImpl0);
      assertEquals(true, boolean0);
  }
}
