/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.CharArraySource;
import de.susebox.jtopas.ReaderSource;
import de.susebox.jtopas.StandardTokenizer;
import de.susebox.jtopas.StandardTokenizerProperties;
import de.susebox.jtopas.StringSource;
import de.susebox.jtopas.Token;
import de.susebox.jtopas.TokenizerException;
import de.susebox.jtopas.TokenizerProperties;
import de.susebox.jtopas.TokenizerSource;

@RunWith(EvoSuiteRunner.class)
public class TestStandardTokenizer_7 {


  //Test case number: 7
  /*
   * 57 covered goals:
   * 1 Weak Mutation 23: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteField: _startPositionI
   * 2 Weak Mutation 27: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteField: _startPositionI
   * 3 Weak Mutation 0: de.susebox.jtopas.StandardTokenizer$StringDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;Lde/susebox/jtopas/CharSequenceTokenizerSource;II)V:404 - DeleteStatement: setData(Lde/susebox/jtopas/CharSequenceTokenizerSource;)V
   * 4 Weak Mutation 19: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteField: _sourceLde/susebox/jtopas/CharSequenceTokenizerSource;
   * 5 Weak Mutation 21: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp +1
   * 6 Weak Mutation 20: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp Negation
   * 7 Weak Mutation 22: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp -1
   * 8 Weak Mutation 25: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp +1
   * 9 Weak Mutation 24: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp Negation
   * 10 Weak Mutation 26: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp -1
   * 11 Weak Mutation 29: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp +1
   * 12 Weak Mutation 28: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp Negation
   * 13 Weak Mutation 31: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteField: _lengthI
   * 14 Weak Mutation 30: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - InsertUnaryOp -1
   * 15 Weak Mutation 34: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - ReplaceArithmeticOperator + -> /
   * 16 Weak Mutation 35: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - ReplaceArithmeticOperator + -> *
   * 17 Weak Mutation 32: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - ReplaceArithmeticOperator + -> -
   * 18 Weak Mutation 33: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - ReplaceArithmeticOperator + -> %
   * 19 Weak Mutation 38: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - InsertUnaryOp Negation
   * 20 Weak Mutation 39: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - InsertUnaryOp IINC 1
   * 21 Weak Mutation 36: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteStatement: subSequence(II)Ljava/lang/CharSequence;
   * 22 Weak Mutation 42: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - InsertUnaryOp IINC 1
   * 23 Weak Mutation 43: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - InsertUnaryOp IINC -1
   * 24 Weak Mutation 40: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - InsertUnaryOp IINC -1
   * 25 Weak Mutation 41: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - InsertUnaryOp Negation
   * 26 Weak Mutation 44: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.<init>(Lde/susebox/jtopas/StandardTokenizer;II)V:258 - DeleteStatement: setDataRange(II)V
   * 27 Weak Mutation 55: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.setDataRange(II)V:292 - InsertUnaryOp IINC -1
   * 28 Weak Mutation 54: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.setDataRange(II)V:292 - InsertUnaryOp IINC 1
   * 29 Weak Mutation 53: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.setDataRange(II)V:292 - InsertUnaryOp Negation
   * 30 Weak Mutation 58: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.setDataRange(II)V:293 - InsertUnaryOp IINC -1
   * 31 Weak Mutation 57: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.setDataRange(II)V:293 - InsertUnaryOp IINC 1
   * 32 Weak Mutation 56: de.susebox.jtopas.StandardTokenizer$AbstractDataProvider.setDataRange(II)V:293 - InsertUnaryOp Negation
   * 33 Weak Mutation 102: de.susebox.jtopas.StandardTokenizer.getRangeStart()I:106 - InsertUnaryOp Negation
   * 34 Weak Mutation 103: de.susebox.jtopas.StandardTokenizer.getRangeStart()I:106 - InsertUnaryOp +1
   * 35 Weak Mutation 98: de.susebox.jtopas.StandardTokenizer.<init>()V:489 - ReplaceConstant - 0 -> 1
   * 36 Weak Mutation 99: de.susebox.jtopas.StandardTokenizer.<init>()V:494 - ReplaceConstant - 0 -> 1
   * 37 Weak Mutation 110: de.susebox.jtopas.StandardTokenizer.setSource(Lde/susebox/jtopas/TokenizerSource;)V:122 - ReplaceConstant - 0 -> 1
   * 38 Weak Mutation 111: de.susebox.jtopas.StandardTokenizer.setSource(Lde/susebox/jtopas/TokenizerSource;)V:122 - ReplaceConstant - 0 -> 1
   * 39 Weak Mutation 108: de.susebox.jtopas.StandardTokenizer.setSource(Lde/susebox/jtopas/TokenizerSource;)V:121 - DeleteStatement: getSource()Lde/susebox/jtopas/TokenizerSource;
   * 40 Weak Mutation 109: de.susebox.jtopas.StandardTokenizer.setSource(Lde/susebox/jtopas/TokenizerSource;)V:122 - DeleteField: _charSequenceTokenizerSourceLde/susebox/jtopas/CharSequenceTokenizerSource;
   * 41 Weak Mutation 106: de.susebox.jtopas.StandardTokenizer.setSource(Lde/susebox/jtopas/TokenizerSource;)V:118 - ReplaceConstant - 0 -> 1
   * 42 Weak Mutation 107: de.susebox.jtopas.StandardTokenizer.setSource(Lde/susebox/jtopas/TokenizerSource;)V:119 - ReplaceConstant - 0 -> 1
   * 43 Weak Mutation 104: de.susebox.jtopas.StandardTokenizer.getRangeStart()I:106 - InsertUnaryOp -1
   * 44 Weak Mutation 119: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - InsertUnaryOp IINC 1
   * 45 Weak Mutation 118: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - InsertUnaryOp Negation
   * 46 Weak Mutation 117: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - DeleteField: _dataProviderLde/susebox/jtopas/StandardTokenizer$AbstractDataProvider;
   * 47 Weak Mutation 127: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - InsertUnaryOp IINC 1
   * 48 Weak Mutation 126: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - InsertUnaryOp Negation
   * 49 Weak Mutation 124: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - ReplaceArithmeticOperator - -> /
   * 50 Weak Mutation 123: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - ReplaceArithmeticOperator - -> %
   * 51 Weak Mutation 121: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - DeleteStatement: getRangeStart()I
   * 52 Weak Mutation 120: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - InsertUnaryOp IINC -1
   * 53 Weak Mutation 129: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - DeleteStatement: setDataRange(II)V
   * 54 Weak Mutation 128: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:153 - InsertUnaryOp IINC -1
   * 55 Weak Mutation 130: de.susebox.jtopas.StandardTokenizer.getDataProvider(II)Lde/susebox/jtopas/spi/DataProvider;:154 - DeleteField: _dataProviderLde/susebox/jtopas/StandardTokenizer$AbstractDataProvider;
   * 56 Weak Mutation 23: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteField: _startPositionI
   * 57 Weak Mutation 27: de.susebox.jtopas.StandardTokenizer$StringDataProvider.toString()Ljava/lang/String;:449 - DeleteField: _startPositionI
   */
  @Test
  public void test7()  throws Throwable  {
      StandardTokenizer standardTokenizer0 = new StandardTokenizer();
      StringSource stringSource0 = new StringSource((String) null);
      standardTokenizer0.setSource((TokenizerSource) stringSource0);
      // Undeclared exception!
      try {
        standardTokenizer0.getText((-1), (int) 'G');
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
