/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.StandardTokenizerProperties;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractTokenizerProperties_21 {


  //Test case number: 21
  /*
   * 5 covered goals:
   * 1 Weak Mutation 270: de.susebox.jtopas.AbstractTokenizerProperties.getBlockCommentCompanion(Ljava/lang/String;)Ljava/lang/Object;:745 - DeleteStatement: getBlockComment(Ljava/lang/String;)Lde/susebox/jtopas/TokenizerProperty;
   * 2 Weak Mutation 271: de.susebox.jtopas.AbstractTokenizerProperties.getBlockCommentCompanion(Ljava/lang/String;)Ljava/lang/Object;:747 - ReplaceComparisonOperator = null -> != null
   * 3 de.susebox.jtopas.AbstractTokenizerProperties.getBlockCommentCompanion(Ljava/lang/String;)Ljava/lang/Object;: I9 Branch 18 IFNULL L747 - true
   * 4 Weak Mutation 270: de.susebox.jtopas.AbstractTokenizerProperties.getBlockCommentCompanion(Ljava/lang/String;)Ljava/lang/Object;:745 - DeleteStatement: getBlockComment(Ljava/lang/String;)Lde/susebox/jtopas/TokenizerProperty;
   * 5 Weak Mutation 271: de.susebox.jtopas.AbstractTokenizerProperties.getBlockCommentCompanion(Ljava/lang/String;)Ljava/lang/Object;:747 - ReplaceComparisonOperator = null -> != null
   */
  @Test
  public void test21()  throws Throwable  {
      StandardTokenizerProperties standardTokenizerProperties0 = new StandardTokenizerProperties(0);
      standardTokenizerProperties0.getBlockCommentCompanion("\"");
      assertEquals(0, standardTokenizerProperties0.getParseFlags());
      assertEquals("!#-/:-@[-^`{-~", standardTokenizerProperties0.getSeparators());
      assertEquals(true, standardTokenizerProperties0.newlineIsWhitespace());
      assertEquals(" \t\r\n", standardTokenizerProperties0.getWhitespaces());
  }
}
