/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.CharArraySource;

@RunWith(EvoSuiteRunner.class)
public class TestCharArraySource_5 {


  //Test case number: 5
  /*
   * 23 covered goals:
   * 1 Weak Mutation 85: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp Negation
   * 2 Weak Mutation 87: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp IINC -1
   * 3 Weak Mutation 86: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp IINC 1
   * 4 Weak Mutation 81: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp Negation
   * 5 Weak Mutation 80: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - DeleteField: _data[C
   * 6 Weak Mutation 83: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp -1
   * 7 Weak Mutation 82: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp +1
   * 8 Weak Mutation 89: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> %
   * 9 Weak Mutation 88: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> -
   * 10 Weak Mutation 91: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> *
   * 11 Weak Mutation 90: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> /
   * 12 de.susebox.jtopas.CharArraySource.charAt(I)C: root-Branch
   * 13 Weak Mutation 85: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp Negation
   * 14 Weak Mutation 87: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp IINC -1
   * 15 Weak Mutation 86: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp IINC 1
   * 16 Weak Mutation 81: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp Negation
   * 17 Weak Mutation 80: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - DeleteField: _data[C
   * 18 Weak Mutation 83: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp -1
   * 19 Weak Mutation 82: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - InsertUnaryOp +1
   * 20 Weak Mutation 89: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> %
   * 21 Weak Mutation 88: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> -
   * 22 Weak Mutation 91: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> *
   * 23 Weak Mutation 90: de.susebox.jtopas.CharArraySource.charAt(I)C:131 - ReplaceArithmeticOperator + -> /
   */
  @Test
  public void test5()  throws Throwable  {
      char[] charArray0 = new char[14];
      CharArraySource charArraySource0 = new CharArraySource(charArray0);
      charArraySource0.charAt(1);
      assertEquals(14, charArraySource0.length());
  }
}
