/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.StandardTokenizerProperties;

@RunWith(EvoSuiteRunner.class)
public class TestStandardTokenizerProperties_2 {


  //Test case number: 2
  /*
   * 21 covered goals:
   * 1 Weak Mutation 84: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - DeleteField: _separatorsNoCaseLjava/lang/String;
   * 2 Weak Mutation 83: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - ReplaceComparisonOperator <= -> -1
   * 3 de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 20 IFLE L226 - false
   * 4 Weak Mutation 69: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:221 - ReplaceComparisonOperator != -> <
   * 5 Weak Mutation 79: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - DeleteField: _separatorsNoCaseLjava/lang/String;
   * 6 Weak Mutation 85: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - DeleteField: _separatorsCaseLjava/lang/String;
   * 7 Weak Mutation 84: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - DeleteField: _separatorsNoCaseLjava/lang/String;
   * 8 Weak Mutation 80: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - DeleteStatement: length()I
   * 9 Weak Mutation 83: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - ReplaceComparisonOperator <= -> -1
   * 10 Weak Mutation 82: de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;:226 - ReplaceComparisonOperator <= -> <
   * 11 Weak Mutation 110: de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;:254 - ReplaceComparisonOperator != -> <
   * 12 Weak Mutation 126: de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;:259 - DeleteField: _whitespacesCaseLjava/lang/String;
   * 13 Weak Mutation 123: de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;:259 - ReplaceComparisonOperator <= -> <
   * 14 Weak Mutation 121: de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;:259 - DeleteStatement: length()I
   * 15 Weak Mutation 120: de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;:259 - DeleteField: _whitespacesNoCaseLjava/lang/String;
   * 16 de.susebox.jtopas.StandardTokenizerProperties.putCharSet(Ljava/lang/String;IZ)V: I235 Branch 109 IFEQ L941 - false
   * 17 de.susebox.jtopas.StandardTokenizerProperties.putCharSet(Ljava/lang/String;IZ)V: I238 Branch 110 IF_ICMPNE L941 - false
   * 18 de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;: I6 Branch 18 IFNE L221 - true
   * 19 de.susebox.jtopas.StandardTokenizerProperties.doSetSeparators(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 20 IFLE L226 - true
   * 20 de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;: I6 Branch 23 IFNE L254 - true
   * 21 de.susebox.jtopas.StandardTokenizerProperties.doSetWhitespaces(Ljava/lang/String;)Ljava/lang/String;: I37 Branch 25 IFLE L259 - true
   */
  @Test
  public void test2()  throws Throwable  {
      StandardTokenizerProperties standardTokenizerProperties0 = new StandardTokenizerProperties((-1775));
      assertNotNull(standardTokenizerProperties0);
      
      standardTokenizerProperties0.setSeparators("//");
      assertEquals(true, standardTokenizerProperties0.newlineIsWhitespace());
      assertEquals(-1775, standardTokenizerProperties0.getParseFlags());
  }
}
