/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.TokenizerPropertyEvent;

@RunWith(EvoSuiteRunner.class)
public class TestTokenizerPropertyEvent_4 {


  //Test case number: 4
  /*
   * 3 covered goals:
   * 1 Weak Mutation 24: de.susebox.jtopas.TokenizerPropertyEvent.equals(Ljava/lang/Object;)Z:194 - ReplaceConstant - 0 -> 1
   * 2 de.susebox.jtopas.TokenizerPropertyEvent.equals(Ljava/lang/Object;)Z: I3 Branch 1 IFNONNULL L193 - false
   * 3 Weak Mutation 24: de.susebox.jtopas.TokenizerPropertyEvent.equals(Ljava/lang/Object;)Z:194 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test4()  throws Throwable  {
      TokenizerPropertyEvent tokenizerPropertyEvent0 = new TokenizerPropertyEvent();
      boolean boolean0 = tokenizerPropertyEvent0.equals((Object) null);
      assertEquals(0, tokenizerPropertyEvent0.getType());
      assertEquals(false, boolean0);
  }
}
