/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.java.lang.ExtIllegalArgumentException;
import de.susebox.java.lang.ExtUnsupportedOperationException;
import de.susebox.jtopas.StandardTokenizer;
import de.susebox.jtopas.StandardTokenizerProperties;
import de.susebox.jtopas.TokenizerException;
import de.susebox.jtopas.TokenizerProperties;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.spi.DataProvider;

@RunWith(EvoSuiteRunner.class)
public class TestStandardTokenizerProperties_26 {


  //Test case number: 26
  /*
   * 11 covered goals:
   * 1 Weak Mutation 419: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:730 - DeleteField: _patternsLjava/util/ArrayList;
   * 2 Weak Mutation 426: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - ReplaceConstant - 0 -> 1
   * 3 Weak Mutation 421: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - DeleteStatement: size()I
   * 4 Weak Mutation 420: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - DeleteField: _patternsLjava/util/ArrayList;
   * 5 Weak Mutation 423: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - ReplaceComparisonOperator <= -> <
   * 6 de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z: I12 Branch 79 IFLE L731 - true
   * 7 Weak Mutation 426: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - ReplaceConstant - 0 -> 1
   * 8 Weak Mutation 419: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:730 - DeleteField: _patternsLjava/util/ArrayList;
   * 9 Weak Mutation 421: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - DeleteStatement: size()I
   * 10 Weak Mutation 420: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - DeleteField: _patternsLjava/util/ArrayList;
   * 11 Weak Mutation 423: de.susebox.jtopas.StandardTokenizerProperties.hasPattern()Z:731 - ReplaceComparisonOperator <= -> <
   */
  @Test
  public void test26()  throws Throwable  {
      StandardTokenizerProperties standardTokenizerProperties0 = new StandardTokenizerProperties((-1745));
      assertNotNull(standardTokenizerProperties0);
      
      boolean boolean0 = standardTokenizerProperties0.hasPattern();
      assertEquals(true, standardTokenizerProperties0.newlineIsWhitespace());
      assertEquals(-1746, standardTokenizerProperties0.getParseFlags());
      assertEquals(false, boolean0);
  }
}
