/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.java.lang.ExtIllegalArgumentException;
import de.susebox.java.lang.ExtUnsupportedOperationException;
import de.susebox.jtopas.StandardTokenizer;
import de.susebox.jtopas.StandardTokenizerProperties;
import de.susebox.jtopas.TokenizerException;
import de.susebox.jtopas.TokenizerProperties;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.spi.DataProvider;

@RunWith(EvoSuiteRunner.class)
public class TestStandardTokenizerProperties_38 {


  //Test case number: 38
  /*
   * 6 covered goals:
   * 1 de.susebox.jtopas.StandardTokenizerProperties.hasSequenceCommentOrString()Z: I13 Branch 64 IFNONNULL L604 - true
   * 2 Weak Mutation 340: de.susebox.jtopas.StandardTokenizerProperties.hasSequenceCommentOrString()Z:604 - ReplaceComparisonOperator != null -> = null
   * 3 Weak Mutation 339: de.susebox.jtopas.StandardTokenizerProperties.hasSequenceCommentOrString()Z:604 - ReplaceConstant - 0 -> 1
   * 4 Weak Mutation 338: de.susebox.jtopas.StandardTokenizerProperties.hasSequenceCommentOrString()Z:604 - DeleteField: _sequences[Lde/susebox/jtopas/impl/SequenceStore;
   * 5 Weak Mutation 337: de.susebox.jtopas.StandardTokenizerProperties.hasSequenceCommentOrString()Z:603 - DeleteField: _sequences[Lde/susebox/jtopas/impl/SequenceStore;
   * 6 Weak Mutation 344: de.susebox.jtopas.StandardTokenizerProperties.hasSequenceCommentOrString()Z:604 - ReplaceConstant - 1 -> 0
   */
  @Test
  public void test38()  throws Throwable  {
      StandardTokenizerProperties standardTokenizerProperties0 = new StandardTokenizerProperties(1226, "KxHV", "KxHV");
      assertEquals(false, standardTokenizerProperties0.hasSequenceCommentOrString());
      assertNotNull(standardTokenizerProperties0);
      
      standardTokenizerProperties0.addBlockComment("KxHV", "KxHV", "KxHV");
      boolean boolean0 = standardTokenizerProperties0.hasSequenceCommentOrString();
      assertEquals(4, standardTokenizerProperties0.getSequenceMaxLength());
      assertEquals(true, boolean0);
  }
}
