/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.java.lang.ExtIndexOutOfBoundsException;
import de.susebox.jtopas.AbstractTokenizer;
import de.susebox.jtopas.ReaderSource;
import de.susebox.jtopas.StandardTokenizer;
import de.susebox.jtopas.StandardTokenizerProperties;
import de.susebox.jtopas.Token;
import de.susebox.jtopas.TokenizerException;
import de.susebox.jtopas.TokenizerProperties;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.TokenizerSource;
import de.susebox.jtopas.spi.KeywordHandler;
import de.susebox.jtopas.spi.PatternHandler;
import de.susebox.jtopas.spi.SequenceHandler;
import java.io.PipedReader;
import java.io.Reader;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractTokenizer_41 {


  //Test case number: 41
  /*
   * 23 covered goals:
   * 1 Weak Mutation 1405: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1628 - InsertUnaryOp IINC 1
   * 2 Weak Mutation 1404: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1628 - InsertUnaryOp Negation
   * 3 Weak Mutation 1406: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1628 - InsertUnaryOp IINC -1
   * 4 Weak Mutation 1476: de.susebox.jtopas.AbstractTokenizer.comparePrefix(ILjava/lang/String;Z)I:1717 - ReplaceComparisonOperator >= -> >
   * 5 Weak Mutation 1551: de.susebox.jtopas.AbstractTokenizer.comparePrefix(ILjava/lang/String;Z)I:1734 - ReplaceConstant - 0 -> 1
   * 6 de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I: I80 Branch 195 LOOKUPSWITCH L1625 Case -1 - false
   * 7 de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I: I80 Branch 196 LOOKUPSWITCH L1625 Case 0 - true
   * 8 de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I: I80 Branch 197 LOOKUPSWITCH L1625 Default-Case - false
   * 9 de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I: I108 Branch 198 IFGE L1635 - false
   * 10 de.susebox.jtopas.AbstractTokenizer.comparePrefix(ILjava/lang/String;Z)I: I14 Branch 214 IF_ICMPGE L1717 - true
   * 11 Weak Mutation 1405: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1628 - InsertUnaryOp IINC 1
   * 12 Weak Mutation 1404: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1628 - InsertUnaryOp Negation
   * 13 Weak Mutation 1406: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1628 - InsertUnaryOp IINC -1
   * 14 Weak Mutation 1401: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - InsertUnaryOp IINC 1
   * 15 Weak Mutation 1400: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - InsertUnaryOp Negation
   * 16 Weak Mutation 1403: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - DeleteStatement: comparePrefix(ILjava/lang/String;Z)I
   * 17 Weak Mutation 1402: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - InsertUnaryOp IINC -1
   * 18 Weak Mutation 1397: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - InsertUnaryOp Negation
   * 19 Weak Mutation 1399: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - InsertUnaryOp IINC -1
   * 20 Weak Mutation 1398: de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I:1625 - InsertUnaryOp IINC 1
   * 21 Weak Mutation 1476: de.susebox.jtopas.AbstractTokenizer.comparePrefix(ILjava/lang/String;Z)I:1717 - ReplaceComparisonOperator >= -> >
   * 22 Weak Mutation 1551: de.susebox.jtopas.AbstractTokenizer.comparePrefix(ILjava/lang/String;Z)I:1734 - ReplaceConstant - 0 -> 1
   * 23 de.susebox.jtopas.AbstractTokenizer.completeBlockComment(Lde/susebox/jtopas/TokenizerProperty;)I: I43 Branch 191 IFEQ L1613 - true
   */
  @Test
  public void test41()  throws Throwable  {
      StandardTokenizer standardTokenizer0 = new StandardTokenizer();
      assertNotNull(standardTokenizer0);
      
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "";
      StandardTokenizerProperties standardTokenizerProperties0 = (StandardTokenizerProperties)standardTokenizer0.getPatternHandler();
      TokenizerProperty tokenizerProperty0 = new TokenizerProperty(65536, stringArray0, (Object) standardTokenizerProperties0);
      int int0 = standardTokenizer0.completeBlockComment(tokenizerProperty0);
      assertEquals(false, standardTokenizer0.hasMoreToken());
      assertEquals(0, int0);
  }
}
