/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.txn;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.dbi.MemoryBudget;
import com.sleepycat.je.txn.Lock;
import com.sleepycat.je.txn.LockGrantType;
import com.sleepycat.je.txn.LockType;
import com.sleepycat.je.txn.Locker;
import java.util.List;
import java.util.Set;

@RunWith(EvoSuiteRunner.class)
public class TestLock_10 {


  //Test case number: 10
  /*
   * 11 covered goals:
   * 1 Weak Mutation 106: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - ReplaceComparisonOperator == -> !=
   * 2 Weak Mutation 107: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - ReplaceConstant - 1 -> 0
   * 3 Weak Mutation 104: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - DeleteStatement: getLockType()Lcom/sleepycat/je/txn/LockType;
   * 4 Weak Mutation 105: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - DeleteStatement: isWriteLock()Z
   * 5 com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z: I9 Branch 32 IFNULL L255 - false
   * 6 com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z: I13 Branch 33 IFEQ L255 - false
   * 7 Weak Mutation 103: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - ReplaceComparisonOperator = null -> != null
   * 8 Weak Mutation 106: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - ReplaceComparisonOperator == -> !=
   * 9 Weak Mutation 107: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - ReplaceConstant - 1 -> 0
   * 10 Weak Mutation 104: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - DeleteStatement: getLockType()Lcom/sleepycat/je/txn/LockType;
   * 11 Weak Mutation 105: com.sleepycat.je.txn.Lock.isOwnedWriteLock(Lcom/sleepycat/je/txn/Locker;)Z:255 - DeleteStatement: isWriteLock()Z
   */
  @Test
  public void test10()  throws Throwable  {
      Lock lock0 = new Lock((Long) (-308L));
      LockType lockType0 = LockType.RANGE_WRITE;
      LockGrantType lockGrantType0 = lock0.lock(lockType0, (Locker) null, false, (MemoryBudget) null, 0);
      assertNotNull(lockGrantType0);
      
      boolean boolean0 = lock0.isOwnedWriteLock((Locker) null);
      assertEquals(1, lock0.nOwners());
      assertEquals(true, boolean0);
  }
}
