/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.txn;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.MemoryBudget;
import com.sleepycat.je.txn.Lock;
import com.sleepycat.je.txn.LockGrantType;
import com.sleepycat.je.txn.LockType;
import com.sleepycat.je.txn.Locker;
import java.util.List;
import java.util.Set;

@RunWith(EvoSuiteRunner.class)
public class TestLock_16 {


  //Test case number: 16
  /*
   * 48 covered goals:
   * 1 Weak Mutation 304: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:620 - DeleteField: firstOwnerLcom/sleepycat/je/txn/LockInfo;
   * 2 Weak Mutation 307: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - InsertUnaryOp Negation
   * 3 Weak Mutation 306: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - ReplaceConstant - 0 -> 1
   * 4 Weak Mutation 309: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - InsertUnaryOp IINC -1
   * 5 Weak Mutation 308: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - InsertUnaryOp IINC 1
   * 6 Weak Mutation 312: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - ReplaceComparisonOperator >= -> -1
   * 7 Weak Mutation 313: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - DeleteField: firstOwnerLcom/sleepycat/je/txn/LockInfo;
   * 8 Weak Mutation 315: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - InsertUnaryOp Negation
   * 9 Weak Mutation 314: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - DeleteStatement: getLocker()Lcom/sleepycat/je/txn/Locker;
   * 10 Weak Mutation 317: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - InsertUnaryOp IINC -1
   * 11 Weak Mutation 316: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - InsertUnaryOp IINC 1
   * 12 Weak Mutation 318: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - ReplaceComparisonOperator != -> ==
   * 13 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I29 Branch 137 IFNULL L620 - false
   * 14 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I38 Branch 138 IF_ICMPGE L621 - false
   * 15 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I47 Branch 139 IF_ACMPNE L622 - false
   * 16 Weak Mutation 54: com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z:163 - ReplaceComparisonOperator = null -> != null
   * 17 Weak Mutation 53: com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z:162 - ReplaceConstant - 0 -> 1
   * 18 Weak Mutation 62: com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z:180 - InsertUnaryOp Negation
   * 19 Weak Mutation 305: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:620 - ReplaceComparisonOperator = null -> != null
   * 20 Weak Mutation 297: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:616 - ReplaceConstant - 1 -> 0
   * 21 Weak Mutation 298: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:616 - ReplaceComparisonOperator != -> ==
   * 22 Weak Mutation 320: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:628 - ReplaceComparisonOperator = null -> != null
   * 23 Weak Mutation 54: com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z:163 - ReplaceComparisonOperator = null -> != null
   * 24 Weak Mutation 53: com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z:162 - ReplaceConstant - 0 -> 1
   * 25 Weak Mutation 62: com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z:180 - InsertUnaryOp Negation
   * 26 Weak Mutation 305: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:620 - ReplaceComparisonOperator = null -> != null
   * 27 Weak Mutation 304: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:620 - DeleteField: firstOwnerLcom/sleepycat/je/txn/LockInfo;
   * 28 Weak Mutation 307: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - InsertUnaryOp Negation
   * 29 Weak Mutation 306: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - ReplaceConstant - 0 -> 1
   * 30 Weak Mutation 309: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - InsertUnaryOp IINC -1
   * 31 Weak Mutation 308: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - InsertUnaryOp IINC 1
   * 32 Weak Mutation 313: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - DeleteField: firstOwnerLcom/sleepycat/je/txn/LockInfo;
   * 33 Weak Mutation 312: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:621 - ReplaceComparisonOperator >= -> -1
   * 34 Weak Mutation 315: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - InsertUnaryOp Negation
   * 35 Weak Mutation 314: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - DeleteStatement: getLocker()Lcom/sleepycat/je/txn/Locker;
   * 36 Weak Mutation 317: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - InsertUnaryOp IINC -1
   * 37 Weak Mutation 316: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - InsertUnaryOp IINC 1
   * 38 Weak Mutation 318: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:622 - ReplaceComparisonOperator != -> ==
   * 39 Weak Mutation 320: com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;:628 - ReplaceComparisonOperator = null -> != null
   * 40 com.sleepycat.je.txn.Lock.flushOwner(Lcom/sleepycat/je/txn/LockInfo;Lcom/sleepycat/je/dbi/MemoryBudget;I)Z: I7 Branch 16 IFNULL L163 - true
   * 41 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I13 Branch 136 IF_ICMPNE L616 - true
   * 42 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I64 Branch 140 IFNULL L628 - true
   * 43 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I117 Branch 144 IFNULL L640 - true
   * 44 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I133 Branch 145 IFNULL L643 - true
   * 45 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I177 Branch 149 IFNULL L653 - true
   * 46 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I212 Branch 152 IFNULL L661 - true
   * 47 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I272 Branch 156 IFNE L675 - false
   * 48 com.sleepycat.je.txn.Lock.transferMultiple(Lcom/sleepycat/je/txn/Locker;[Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/dbi/MemoryBudget;I)Lcom/sleepycat/je/txn/LockType;: I274 Branch 157 IFNE L675 - false
   */
  @Test
  public void test16()  throws Throwable  {
      Lock lock0 = new Lock();
      LockType lockType0 = LockType.READ;
      LockGrantType lockGrantType0 = lock0.lock(lockType0, (Locker) null, false, (MemoryBudget) null, 0);
      assertNotNull(lockGrantType0);
      assertEquals(1, lock0.nOwners());
      
      Locker[] lockerArray0 = new Locker[7];
      // Undeclared exception!
      try {
        lock0.transferMultiple((Locker) null, lockerArray0, (MemoryBudget) null, 0);
        fail("Expecting exception: AssertionError");
      } catch(AssertionError e) {
      }
  }
}
