/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.txn;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.txn.LockConflict;
import com.sleepycat.je.txn.LockType;

@RunWith(EvoSuiteRunner.class)
public class TestLockType_2 {


  //Test case number: 2
  /*
   * 19 covered goals:
   * 1 Weak Mutation 11: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - DeleteField: conflictMatrix[[Lcom/sleepycat/je/txn/LockConflict;
   * 2 Weak Mutation 12: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp Negation
   * 3 Weak Mutation 13: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp +1
   * 4 Weak Mutation 14: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp -1
   * 5 Weak Mutation 15: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - DeleteField: indexI
   * 6 Weak Mutation 17: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp +1
   * 7 Weak Mutation 16: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp Negation
   * 8 Weak Mutation 19: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - DeleteField: indexI
   * 9 Weak Mutation 18: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp -1
   * 10 com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;: root-Branch
   * 11 Weak Mutation 11: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - DeleteField: conflictMatrix[[Lcom/sleepycat/je/txn/LockConflict;
   * 12 Weak Mutation 12: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp Negation
   * 13 Weak Mutation 13: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp +1
   * 14 Weak Mutation 14: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp -1
   * 15 Weak Mutation 15: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - DeleteField: indexI
   * 16 Weak Mutation 17: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp +1
   * 17 Weak Mutation 16: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp Negation
   * 18 Weak Mutation 19: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - DeleteField: indexI
   * 19 Weak Mutation 18: com.sleepycat.je.txn.LockType.getConflict(Lcom/sleepycat/je/txn/LockType;)Lcom/sleepycat/je/txn/LockConflict;:86 - InsertUnaryOp -1
   */
  @Test
  public void test2()  throws Throwable  {
      LockType lockType0 = LockType.RANGE_WRITE;
      LockConflict lockConflict0 = lockType0.getConflict(lockType0);
      assertNotNull(lockConflict0);
      assertEquals(false, lockConflict0.getRestart());
  }
}
