/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.txn;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.tree.LN;
import com.sleepycat.je.txn.LockGrantType;
import com.sleepycat.je.txn.LockResult;
import com.sleepycat.je.txn.WriteLockInfo;

@RunWith(EvoSuiteRunner.class)
public class TestLockResult_1 {


  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 Weak Mutation 1: com.sleepycat.je.txn.LockResult.getLockGrant()Lcom/sleepycat/je/txn/LockGrantType;:23 - DeleteField: grantLcom/sleepycat/je/txn/LockGrantType;
   * 2 com.sleepycat.je.txn.LockResult.getLockGrant()Lcom/sleepycat/je/txn/LockGrantType;: root-Branch
   * 3 Weak Mutation 1: com.sleepycat.je.txn.LockResult.getLockGrant()Lcom/sleepycat/je/txn/LockGrantType;:23 - DeleteField: grantLcom/sleepycat/je/txn/LockGrantType;
   */
  @Test
  public void test1()  throws Throwable  {
      LockGrantType lockGrantType0 = LockGrantType.DENIED;
      LockResult lockResult0 = new LockResult(lockGrantType0, (WriteLockInfo) null);
      LockGrantType lockGrantType1 = lockResult0.getLockGrant();
      assertEquals("DENIED", lockGrantType1.toString());
  }
}
