/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.txn;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.txn.TxnCommit;

@RunWith(EvoSuiteRunner.class)
public class TestTxnEnd_0 {


  //Test case number: 0
  /*
   * 9 covered goals:
   * 1 Weak Mutation 6: com.sleepycat.je.txn.TxnEnd.getId()J:28 - InsertUnaryOp Negation
   * 2 Weak Mutation 7: com.sleepycat.je.txn.TxnEnd.getId()J:28 - DeleteField: idJ
   * 3 com.sleepycat.je.txn.TxnEnd.getId()J: root-Branch
   * 4 Weak Mutation 0: com.sleepycat.je.txn.TxnEnd.<init>(JJ)V:17 - InsertUnaryOp Negation
   * 5 Weak Mutation 1: com.sleepycat.je.txn.TxnEnd.<init>(JJ)V:18 - DeleteStatement: currentTimeMillis()J
   * 6 Weak Mutation 2: com.sleepycat.je.txn.TxnEnd.<init>(JJ)V:19 - InsertUnaryOp Negation
   * 7 Weak Mutation 6: com.sleepycat.je.txn.TxnEnd.getId()J:28 - InsertUnaryOp Negation
   * 8 Weak Mutation 7: com.sleepycat.je.txn.TxnEnd.getId()J:28 - DeleteField: idJ
   * 9 com.sleepycat.je.txn.TxnEnd.<init>(JJ)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      TxnCommit txnCommit0 = new TxnCommit(1855L, 1855L);
      long long0 = txnCommit0.getId();
      assertEquals(1855L, long0);
      assertEquals(1855L, txnCommit0.getLastLsn());
  }
}
