/*
 * This file was automatically generated by EvoSuite
 */

package sudoku.main;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import sudoku.main.AbstractEnum;
import sudoku.main.Structure;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractEnum_2 {


  //Test case number: 2
  /*
   * 20 covered goals:
   * 1 Weak Mutation 20: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:145 - DeleteStatement: checkClassIsEnum(Ljava/lang/Class;)V
   * 2 Weak Mutation 21: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:146 - DeleteStatement: getValuesByName(Ljava/lang/Class;)Ljava/util/Map;
   * 3 Weak Mutation 23: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:147 - ReplaceComparisonOperator <= -> ==
   * 4 Weak Mutation 22: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:147 - DeleteStatement: mapContainsKey(Ljava/util/Map;Ljava/lang/Object;)I
   * 5 Weak Mutation 59: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:242 - DeleteField: ALL_VALUES_BY_NAMELjava/util/Map;
   * 6 Weak Mutation 63: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:242 - ReplaceComparisonOperator <= -> -1
   * 7 Weak Mutation 60: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:242 - DeleteStatement: mapContainsKey(Ljava/util/Map;Ljava/lang/Object;)I
   * 8 Weak Mutation 64: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:243 - DeleteField: ALL_VALUES_BY_NAMELjava/util/Map;
   * 9 Weak Mutation 65: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:243 - DeleteStatement: get(Ljava/lang/Object;)Ljava/lang/Object;
   * 10 sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;: I14 Branch 3 IFLE L147 - true
   * 11 sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;: I5 Branch 5 IFLE L242 - false
   * 12 Weak Mutation 21: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:146 - DeleteStatement: getValuesByName(Ljava/lang/Class;)Ljava/util/Map;
   * 13 Weak Mutation 20: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:145 - DeleteStatement: checkClassIsEnum(Ljava/lang/Class;)V
   * 14 Weak Mutation 23: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:147 - ReplaceComparisonOperator <= -> ==
   * 15 Weak Mutation 22: sudoku.main.AbstractEnum.valueOf0(Ljava/lang/Class;Ljava/lang/String;)Lsudoku/main/AbstractEnum;:147 - DeleteStatement: mapContainsKey(Ljava/util/Map;Ljava/lang/Object;)I
   * 16 Weak Mutation 59: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:242 - DeleteField: ALL_VALUES_BY_NAMELjava/util/Map;
   * 17 Weak Mutation 63: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:242 - ReplaceComparisonOperator <= -> -1
   * 18 Weak Mutation 60: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:242 - DeleteStatement: mapContainsKey(Ljava/util/Map;Ljava/lang/Object;)I
   * 19 Weak Mutation 64: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:243 - DeleteField: ALL_VALUES_BY_NAMELjava/util/Map;
   * 20 Weak Mutation 65: sudoku.main.AbstractEnum.getValuesByName(Ljava/lang/Class;)Ljava/util/Map;:243 - DeleteStatement: get(Ljava/lang/Object;)Ljava/lang/Object;
   */
  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = AbstractEnum.class;
      try {
        AbstractEnum.valueOf0((Class) class0, "COL");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * COL
         */
      }
  }
}
