/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.Cursor;
import com.sleepycat.je.CursorConfig;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.Environment;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.txn.Locker;

@RunWith(EvoSuiteRunner.class)
public class TestCursor_4 {


  //Test case number: 4
  /*
   * 15 covered goals:
   * 1 Weak Mutation 16: com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V:100 - ReplaceComparisonOperator != null -> = null
   * 2 Weak Mutation 17: com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V:101 - DeleteField: DEFAULTLcom/sleepycat/je/CursorConfig;
   * 3 Weak Mutation 18: com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V:103 - ReplaceConstant - 1 -> 0
   * 4 Weak Mutation 19: com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V:106 - InsertUnaryOp Negation
   * 5 Weak Mutation 21: com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V:106 - ReplaceComparisonOperator != -> ==
   * 6 Weak Mutation 22: com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V:106 - ReplaceComparisonOperator != null -> = null
   * 7 com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V: I7 Branch 3 IFNONNULL L100 - false
   * 8 com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V: I3 Branch 4 IFNE L106 - false
   * 9 com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V: I5 Branch 5 IFNONNULL L106 - false
   * 10 Weak Mutation 17: com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V:101 - DeleteField: DEFAULTLcom/sleepycat/je/CursorConfig;
   * 11 Weak Mutation 16: com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V:100 - ReplaceComparisonOperator != null -> = null
   * 12 Weak Mutation 19: com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V:106 - InsertUnaryOp Negation
   * 13 Weak Mutation 18: com.sleepycat.je.Cursor.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/CursorConfig;)V:103 - ReplaceConstant - 1 -> 0
   * 14 Weak Mutation 21: com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V:106 - ReplaceComparisonOperator != -> ==
   * 15 Weak Mutation 22: com.sleepycat.je.Cursor.init(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/dbi/DatabaseImpl;Lcom/sleepycat/je/txn/Locker;ZLcom/sleepycat/je/CursorConfig;)V:106 - ReplaceComparisonOperator != null -> = null
   */
  @Test
  public void test4()  throws Throwable  {
      Cursor cursor0 = null;
      try {
        cursor0 = new Cursor((DatabaseImpl) null, (Locker) null, (CursorConfig) null);
        fail("Expecting exception: AssertionError");
      } catch(AssertionError e) {
      }
  }
}
