/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.Cursor;
import com.sleepycat.je.CursorConfig;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.DbInternal;
import com.sleepycat.je.Environment;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.JoinCursor;
import com.sleepycat.je.LockMode;
import com.sleepycat.je.dbi.GetMode;
import com.sleepycat.je.txn.Locker;
import java.util.Properties;

@RunWith(EvoSuiteRunner.class)
public class TestDbInternal_13 {


  //Test case number: 13
  /*
   * 3 covered goals:
   * 1 Weak Mutation 25: com.sleepycat.je.DbInternal.getCheckpointUP(Lcom/sleepycat/je/EnvironmentConfig;)Z:102 - DeleteStatement: getCheckpointUP()Z
   * 2 com.sleepycat.je.DbInternal.getCheckpointUP(Lcom/sleepycat/je/EnvironmentConfig;)Z: root-Branch
   * 3 Weak Mutation 25: com.sleepycat.je.DbInternal.getCheckpointUP(Lcom/sleepycat/je/EnvironmentConfig;)Z:102 - DeleteStatement: getCheckpointUP()Z
   */
  @Test
  public void test13()  throws Throwable  {
      EnvironmentConfig environmentConfig0 = EnvironmentConfig.DEFAULT;
      boolean boolean0 = DbInternal.getCheckpointUP(environmentConfig0);
      assertEquals(true, boolean0);
  }
}
