/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.PreloadConfig;

@RunWith(EvoSuiteRunner.class)
public class TestPreloadConfig_1 {


  //Test case number: 1
  /*
   * 5 covered goals:
   * 1 Weak Mutation 1: com.sleepycat.je.PreloadConfig.getMaxBytes()J:29 - InsertUnaryOp Negation
   * 2 Weak Mutation 2: com.sleepycat.je.PreloadConfig.getMaxBytes()J:29 - DeleteField: maxBytesJ
   * 3 com.sleepycat.je.PreloadConfig.getMaxBytes()J: root-Branch
   * 4 Weak Mutation 1: com.sleepycat.je.PreloadConfig.getMaxBytes()J:29 - InsertUnaryOp Negation
   * 5 Weak Mutation 2: com.sleepycat.je.PreloadConfig.getMaxBytes()J:29 - DeleteField: maxBytesJ
   */
  @Test
  public void test1()  throws Throwable  {
      PreloadConfig preloadConfig0 = PreloadConfig.DEFAULT;
      long long0 = preloadConfig0.getMaxBytes();
      assertEquals(1L, long0);
  }
}
