/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseEntry;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseEntry_16 {


  //Test case number: 16
  /*
   * 7 covered goals:
   * 1 Weak Mutation 156: com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z:181 - DeleteField: data[B
   * 2 Weak Mutation 163: com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z:185 - ReplaceConstant - 0 -> 1
   * 3 com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z: I50 Branch 10 IFNONNULL L181 - true
   * 4 com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z: I59 Branch 11 IFNULL L184 - true
   * 5 Weak Mutation 157: com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z:181 - ReplaceComparisonOperator != null -> = null
   * 6 Weak Mutation 156: com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z:181 - DeleteField: data[B
   * 7 Weak Mutation 163: com.sleepycat.je.DatabaseEntry.equals(Ljava/lang/Object;)Z:185 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test16()  throws Throwable  {
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      byte[] byteArray0 = new byte[20];
      DatabaseEntry databaseEntry1 = new DatabaseEntry(byteArray0);
      boolean boolean0 = databaseEntry0.equals((Object) databaseEntry1);
      assertEquals("<DatabaseEntry dlen=0 doff=0 doff=0 offset=0 size=20>", databaseEntry1.toString());
      assertEquals(false, databaseEntry1.getPartial());
      assertEquals(false, databaseEntry0.getPartial());
      assertEquals(false, boolean0);
      assertEquals("<DatabaseEntry dlen=0 doff=0 doff=0 offset=0 size=0>", databaseEntry0.toString());
      assertFalse(databaseEntry1.equals(databaseEntry0));
  }
}
