/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.CheckpointConfig;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.Environment;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.EnvironmentMutableConfig;
import com.sleepycat.je.SecondaryConfig;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.log.LogException;
import java.io.File;

@RunWith(EvoSuiteRunner.class)
public class TestEnvironment_13 {


  //Test case number: 13
  /*
   * 5 covered goals:
   * 1 com.sleepycat.je.Environment.getEnvironmentImpl()Lcom/sleepycat/je/dbi/EnvironmentImpl;: root-Branch
   * 2 Weak Mutation 19: com.sleepycat.je.Environment.<init>(Ljava/io/File;)V:82 - DeleteStatement: getInstance()Lcom/sleepycat/je/dbi/DbEnvPool;
   * 3 Weak Mutation 18: com.sleepycat.je.Environment.<init>(Ljava/io/File;)V:81 - ReplaceConstant - 0 -> 1
   * 4 Weak Mutation 20: com.sleepycat.je.Environment.<init>(Ljava/io/File;)V:82 - DeleteStatement: getExistingEnvironment(Ljava/io/File;)Lcom/sleepycat/je/dbi/DbEnvPool$EnvironmentImplInfo;
   * 5 Weak Mutation 22: com.sleepycat.je.Environment.<init>(Ljava/io/File;)V:85 - ReplaceComparisonOperator = null -> != null
   */
  @Test
  public void test13()  throws Throwable  {
      File file0 = new File("V");
      Environment environment0 = new Environment(file0);
      EnvironmentImpl environmentImpl0 = environment0.getEnvironmentImpl();
      assertNull(environmentImpl0);
  }
}
