/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.SecondaryDatabase;
import com.sleepycat.je.SecondaryTrigger;
import com.sleepycat.je.txn.Locker;

@RunWith(EvoSuiteRunner.class)
public class TestSecondaryTrigger {


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 Weak Mutation 2: com.sleepycat.je.SecondaryTrigger.triggerRemoved(Lcom/sleepycat/je/Database;)V:14 - DeleteStatement: clearPrimary()V
   * 2 com.sleepycat.je.SecondaryTrigger.triggerRemoved(Lcom/sleepycat/je/Database;)V: root-Branch
   * 3 com.sleepycat.je.SecondaryTrigger.<init>(Lcom/sleepycat/je/SecondaryDatabase;)V: root-Branch
   * 4 Weak Mutation 2: com.sleepycat.je.SecondaryTrigger.triggerRemoved(Lcom/sleepycat/je/Database;)V:14 - DeleteStatement: clearPrimary()V
   */
  @Test
  public void test0()  throws Throwable  {
      SecondaryTrigger secondaryTrigger0 = new SecondaryTrigger((SecondaryDatabase) null);
      // Undeclared exception!
      try {
        secondaryTrigger0.triggerRemoved((Database) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 1
  /*
   * 11 covered goals:
   * 1 Weak Mutation 4: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable priKey -> newData
   * 2 Weak Mutation 5: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable priKey -> oldData
   * 3 Weak Mutation 7: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable oldData -> priKey
   * 4 Weak Mutation 8: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable newData -> priKey
   * 5 Weak Mutation 10: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - DeleteStatement: updateSecondary(Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/Cursor;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V
   * 6 com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V: root-Branch
   * 7 Weak Mutation 4: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable priKey -> newData
   * 8 Weak Mutation 5: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable priKey -> oldData
   * 9 Weak Mutation 7: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable oldData -> priKey
   * 10 Weak Mutation 8: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable newData -> priKey
   * 11 Weak Mutation 10: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - DeleteStatement: updateSecondary(Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/Cursor;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V
   */
  @Test
  public void test1()  throws Throwable  {
      SecondaryTrigger secondaryTrigger0 = new SecondaryTrigger((SecondaryDatabase) null);
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      byte[] byteArray0 = new byte[17];
      DatabaseEntry databaseEntry1 = new DatabaseEntry(byteArray0, (int) (byte)30, (int) (byte)30);
      // Undeclared exception!
      try {
        secondaryTrigger0.databaseUpdated((Database) null, (Locker) null, databaseEntry1, databaseEntry0, databaseEntry0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 2
  /*
   * 7 covered goals:
   * 1 Weak Mutation 6: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable oldData -> newData
   * 2 Weak Mutation 9: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable newData -> oldData
   * 3 Weak Mutation 4: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable priKey -> newData
   * 4 Weak Mutation 8: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable newData -> priKey
   * 5 Weak Mutation 10: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - DeleteStatement: updateSecondary(Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/Cursor;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V
   * 6 Weak Mutation 6: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable oldData -> newData
   * 7 Weak Mutation 9: com.sleepycat.je.SecondaryTrigger.databaseUpdated(Lcom/sleepycat/je/Database;Lcom/sleepycat/je/txn/Locker;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;Lcom/sleepycat/je/DatabaseEntry;)V:17 - ReplaceVariable newData -> oldData
   */
  @Test
  public void test2()  throws Throwable  {
      SecondaryTrigger secondaryTrigger0 = new SecondaryTrigger((SecondaryDatabase) null);
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      DatabaseEntry databaseEntry1 = new DatabaseEntry();
      // Undeclared exception!
      try {
        secondaryTrigger0.databaseUpdated((Database) null, (Locker) null, databaseEntry0, databaseEntry0, databaseEntry1);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
