/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.LockMode;

@RunWith(EvoSuiteRunner.class)
public class TestLockMode {


  //Test case number: 0
  /*
   * 9 covered goals:
   * 1 Weak Mutation 0: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - ReplaceConstant - LockMode. -> 
   * 2 Weak Mutation 1: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - DeleteField: lockModeNameLjava/lang/String;
   * 3 Weak Mutation 2: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 4 Weak Mutation 3: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - DeleteStatement: toString()Ljava/lang/String;
   * 5 com.sleepycat.je.LockMode.toString()Ljava/lang/String;: root-Branch
   * 6 Weak Mutation 0: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - ReplaceConstant - LockMode. -> 
   * 7 Weak Mutation 1: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - DeleteField: lockModeNameLjava/lang/String;
   * 8 Weak Mutation 2: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 9 Weak Mutation 3: com.sleepycat.je.LockMode.toString()Ljava/lang/String;:38 - DeleteStatement: toString()Ljava/lang/String;
   */
  @Test
  public void test0()  throws Throwable  {
      LockMode lockMode0 = LockMode.READ_UNCOMMITTED;
      String string0 = lockMode0.toString();
      assertEquals("LockMode.READ_UNCOMMITTED", string0);
      assertNotNull(string0);
  }
}
