/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.JoinConfig;

@RunWith(EvoSuiteRunner.class)
public class TestJoinConfig_0 {


  //Test case number: 0
  /*
   * 7 covered goals:
   * 1 Weak Mutation 0: com.sleepycat.je.JoinConfig.setNoSort(Z)V:20 - InsertUnaryOp Negation
   * 2 Weak Mutation 1: com.sleepycat.je.JoinConfig.setNoSort(Z)V:20 - InsertUnaryOp IINC 1
   * 3 Weak Mutation 2: com.sleepycat.je.JoinConfig.setNoSort(Z)V:20 - InsertUnaryOp IINC -1
   * 4 com.sleepycat.je.JoinConfig.setNoSort(Z)V: root-Branch
   * 5 Weak Mutation 0: com.sleepycat.je.JoinConfig.setNoSort(Z)V:20 - InsertUnaryOp Negation
   * 6 Weak Mutation 1: com.sleepycat.je.JoinConfig.setNoSort(Z)V:20 - InsertUnaryOp IINC 1
   * 7 Weak Mutation 2: com.sleepycat.je.JoinConfig.setNoSort(Z)V:20 - InsertUnaryOp IINC -1
   */
  @Test
  public void test0()  throws Throwable  {
      JoinConfig joinConfig0 = JoinConfig.DEFAULT;
      joinConfig0.setNoSort(true);
      assertEquals(true, joinConfig0.getNoSort());
  }
}
