/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseConfig;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseConfig_4 {


  //Test case number: 4
  /*
   * 7 covered goals:
   * 1 Weak Mutation 17: com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V:63 - InsertUnaryOp Negation
   * 2 Weak Mutation 19: com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V:63 - InsertUnaryOp IINC -1
   * 3 Weak Mutation 18: com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V:63 - InsertUnaryOp IINC 1
   * 4 com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V: root-Branch
   * 5 Weak Mutation 17: com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V:63 - InsertUnaryOp Negation
   * 6 Weak Mutation 19: com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V:63 - InsertUnaryOp IINC -1
   * 7 Weak Mutation 18: com.sleepycat.je.DatabaseConfig.setSortedDuplicates(Z)V:63 - InsertUnaryOp IINC 1
   */
  @Test
  public void test4()  throws Throwable  {
      DatabaseConfig databaseConfig0 = new DatabaseConfig();
      assertEquals(false, databaseConfig0.getSortedDuplicates());
      
      databaseConfig0.setSortedDuplicates(true);
      assertEquals(true, databaseConfig0.getSortedDuplicates());
      assertEquals(false, databaseConfig0.getExclusiveCreate());
  }
}
