/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseConfig;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseConfig_11 {


  //Test case number: 11
  /*
   * 5 covered goals:
   * 1 Weak Mutation 48: com.sleepycat.je.DatabaseConfig.setDuplicateComparator(Ljava/lang/Class;)V:166 - ReplaceConstant - Duplicate -> 
   * 2 com.sleepycat.je.DatabaseConfig.setDuplicateComparator(Ljava/lang/Class;)V: root-Branch
   * 3 Weak Mutation 137: com.sleepycat.je.DatabaseConfig.validateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:269 - ReplaceComparisonOperator != null -> = null
   * 4 Weak Mutation 138: com.sleepycat.je.DatabaseConfig.validateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:273 - DeleteStatement: instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;
   * 5 Weak Mutation 48: com.sleepycat.je.DatabaseConfig.setDuplicateComparator(Ljava/lang/Class;)V:166 - ReplaceConstant - Duplicate -> 
   */
  @Test
  public void test11()  throws Throwable  {
      DatabaseConfig databaseConfig0 = new DatabaseConfig();
      Class<?> class0 = DatabaseConfig.class;
      // Undeclared exception!
      try {
        databaseConfig0.setDuplicateComparator(class0);
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * com.sleepycat.je.DatabaseConfig cannot be cast to java.util.Comparator
         */
      }
  }
}
