#!/bin/bash

FEATURES="Yellow_Tier1_P1 Green_Tier2_P2 mov_0 Flower Copy Ring_Oval_Small Nr1 Nr8 Sounds P2_Rot_Police_Siren"

## loading basic configurations
source ../../common

## checking if we loaded variables 
if [[ ! -d "$BASEDIR" ]];
then
    echo "could not find base directory."
fi

CURDIR=`pwd`

INPUT="$CURDIR/src"
OUTPUT="$CURDIR/bin"

mkdir -p $OUTPUT
## running pre-processor
$BASEDIR/prepro $INPUT $OUTPUT "$FEATURES"
INPUT="$CURDIR/src-tests"
$BASEDIR/prepro $INPUT $OUTPUT "$FEATURES"

JUNIT="$LIBSDIR/junit-4.11.jar"
CP=".:$JUNIT"

## compiling
(cd $OUTPUT;
    pwd
    find . -name "*.java" | xargs javac -nowarn -cp $CP
 )