/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.tree.ChildReference;
import com.sleepycat.je.tree.DIN;
import com.sleepycat.je.tree.DupCountLN;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.LN;
import com.sleepycat.je.tree.NameLN;
import com.sleepycat.je.tree.Node;

@RunWith(EvoSuiteRunner.class)
public class TestChildReference_7 {


  //Test case number: 7
  /*
   * 5 covered goals:
   * 1 Weak Mutation 69: com.sleepycat.je.tree.ChildReference.getState()B:114 - InsertUnaryOp Negation
   * 2 Weak Mutation 70: com.sleepycat.je.tree.ChildReference.getState()B:114 - DeleteField: stateB
   * 3 com.sleepycat.je.tree.ChildReference.getState()B: root-Branch
   * 4 Weak Mutation 69: com.sleepycat.je.tree.ChildReference.getState()B:114 - InsertUnaryOp Negation
   * 5 Weak Mutation 70: com.sleepycat.je.tree.ChildReference.getState()B:114 - DeleteField: stateB
   */
  @Test
  public void test7()  throws Throwable  {
      NameLN nameLN0 = new NameLN();
      byte[] byteArray0 = new byte[1];
      ChildReference childReference0 = new ChildReference((Node) nameLN0, byteArray0, 0L, (byte)0);
      byte byte0 = childReference0.getState();
      assertEquals(4294970105L, nameLN0.getNextNodeId());
      assertEquals((byte)2, byte0);
  }
}
