/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.tree.Key;
import java.util.Comparator;

@RunWith(EvoSuiteRunner.class)
public class TestKey_10 {


  //Test case number: 10
  /*
   * 8 covered goals:
   * 1 com.sleepycat.je.tree.Key.equals(Ljava/lang/Object;)Z: I4 Branch 4 IFEQ L63 - true
   * 2 Weak Mutation 0: com.sleepycat.je.tree.Key.<init>([B)V:21 - ReplaceComparisonOperator != null -> = null
   * 3 Weak Mutation 1: com.sleepycat.je.tree.Key.<init>([B)V:26 - ReplaceConstant - 0 -> 1
   * 4 Weak Mutation 2: com.sleepycat.je.tree.Key.<init>([B)V:26 - DeleteField: key[B
   * 5 Weak Mutation 3: com.sleepycat.je.tree.Key.<init>([B)V:26 - ReplaceConstant - 0 -> 1
   * 6 Weak Mutation 4: com.sleepycat.je.tree.Key.<init>([B)V:26 - DeleteStatement: arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V
   * 7 Weak Mutation 18: com.sleepycat.je.tree.Key.equals(Ljava/lang/Object;)Z:63 - ReplaceComparisonOperator == -> !=
   * 8 Weak Mutation 24: com.sleepycat.je.tree.Key.equals(Ljava/lang/Object;)Z:63 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test10()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      Key key0 = new Key(byteArray0);
      assertNotNull(key0);
      
      boolean boolean0 = key0.equals((Object) "");
      assertEquals(false, boolean0);
  }
}
