/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.tree.NameLN;

@RunWith(EvoSuiteRunner.class)
public class TestNameLN_1 {


  //Test case number: 1
  /*
   * 8 covered goals:
   * 1 Weak Mutation 2: com.sleepycat.je.tree.NameLN.isDeleted()Z:33 - DeleteField: deletedZ
   * 2 Weak Mutation 3: com.sleepycat.je.tree.NameLN.makeDeleted()V:36 - ReplaceConstant - 1 -> 0
   * 3 com.sleepycat.je.tree.NameLN.makeDeleted()V: root-Branch
   * 4 Weak Mutation 1: com.sleepycat.je.tree.NameLN.isDeleted()Z:33 - InsertUnaryOp Negation
   * 5 Weak Mutation 2: com.sleepycat.je.tree.NameLN.isDeleted()Z:33 - DeleteField: deletedZ
   * 6 Weak Mutation 3: com.sleepycat.je.tree.NameLN.makeDeleted()V:36 - ReplaceConstant - 1 -> 0
   * 7 com.sleepycat.je.tree.NameLN.isDeleted()Z: root-Branch
   * 8 com.sleepycat.je.tree.NameLN.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      NameLN nameLN0 = new NameLN();
      nameLN0.makeDeleted();
      boolean boolean0 = nameLN0.isDeleted();
      assertEquals(true, boolean0);
  }
}
