/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.tree.NameLN;

@RunWith(EvoSuiteRunner.class)
public class TestNameLN_5 {


  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 Weak Mutation 61: com.sleepycat.je.tree.NameLN.getLogType()Lcom/sleepycat/je/log/LogEntryType;:77 - DeleteField: LOG_NAMELNLcom/sleepycat/je/log/LogEntryType;
   * 2 com.sleepycat.je.tree.NameLN.getLogType()Lcom/sleepycat/je/log/LogEntryType;: root-Branch
   * 3 Weak Mutation 61: com.sleepycat.je.tree.NameLN.getLogType()Lcom/sleepycat/je/log/LogEntryType;:77 - DeleteField: LOG_NAMELNLcom/sleepycat/je/log/LogEntryType;
   */
  @Test
  public void test5()  throws Throwable  {
      DatabaseId databaseId0 = new DatabaseId();
      NameLN nameLN0 = new NameLN(databaseId0);
      nameLN0.getLogType();
      assertEquals(1471L, nameLN0.getNextNodeId());
      assertEquals("<com.sleepycat.je.tree.NameLN/1469", nameLN0.shortDescription());
  }
}
