/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.CursorImpl;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.log.LogException;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.DBINReference;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.MapLN;
import com.sleepycat.je.tree.TreeLocation;
import com.sleepycat.je.tree.TreeWalkerStatsAccumulator;
import java.nio.ByteBuffer;

@RunWith(EvoSuiteRunner.class)
public class TestDBIN_20 {


  //Test case number: 20
  /*
   * 3 covered goals:
   * 1 Weak Mutation 146: com.sleepycat.je.tree.DBIN.shortClassName()Ljava/lang/String;:221 - ReplaceConstant - DBIN -> 
   * 2 com.sleepycat.je.tree.DBIN.shortClassName()Ljava/lang/String;: root-Branch
   * 3 Weak Mutation 146: com.sleepycat.je.tree.DBIN.shortClassName()Ljava/lang/String;:221 - ReplaceConstant - DBIN -> 
   */
  @Test
  public void test20()  throws Throwable  {
      DBIN dBIN0 = new DBIN();
      String string0 = dBIN0.shortClassName();
      assertEquals("DBIN", string0);
  }
}
