/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.BINDelta;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.MapLN;

@RunWith(EvoSuiteRunner.class)
public class TestBINDelta_6 {


  //Test case number: 6
  /*
   * 3 covered goals:
   * 1 Weak Mutation 108: com.sleepycat.je.tree.BINDelta.countAsObsoleteWhenLogged()Z:115 - ReplaceConstant - 0 -> 1
   * 2 com.sleepycat.je.tree.BINDelta.countAsObsoleteWhenLogged()Z: root-Branch
   * 3 Weak Mutation 108: com.sleepycat.je.tree.BINDelta.countAsObsoleteWhenLogged()Z:115 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test6()  throws Throwable  {
      BINDelta bINDelta0 = new BINDelta();
      boolean boolean0 = bINDelta0.countAsObsoleteWhenLogged();
      assertEquals(false, boolean0);
      assertEquals((-1L), bINDelta0.getLastFullLsn());
  }
}
