/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.CursorImpl;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.DBINReference;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.MapLN;
import com.sleepycat.je.tree.TreeLocation;
import com.sleepycat.je.tree.TreeWalkerStatsAccumulator;

@RunWith(EvoSuiteRunner.class)
public class TestDBIN_16 {


  //Test case number: 16
  /*
   * 3 covered goals:
   * 1 Weak Mutation 123: com.sleepycat.je.tree.DBIN.getLogType()Lcom/sleepycat/je/log/LogEntryType;:189 - DeleteField: LOG_DBINLcom/sleepycat/je/log/LogEntryType;
   * 2 com.sleepycat.je.tree.DBIN.getLogType()Lcom/sleepycat/je/log/LogEntryType;: root-Branch
   * 3 Weak Mutation 123: com.sleepycat.je.tree.DBIN.getLogType()Lcom/sleepycat/je/log/LogEntryType;:189 - DeleteField: LOG_DBINLcom/sleepycat/je/log/LogEntryType;
   */
  @Test
  public void test16()  throws Throwable  {
      DBIN dBIN0 = new DBIN();
      LogEntryType logEntryType0 = dBIN0.getLogType();
      assertNotNull(logEntryType0);
      assertEquals(4294971426L, dBIN0.getNextNodeId());
  }
}
