/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.log.LogManager;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.ChildReference;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.DIN;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.MapLN;
import com.sleepycat.je.tree.Node;

@RunWith(EvoSuiteRunner.class)
public class TestIN_8 {


  //Test case number: 8
  /*
   * 3 covered goals:
   * 1 Weak Mutation 123: com.sleepycat.je.tree.IN.setGeneration()V:302 - DeleteStatement: getNextGeneration()J
   * 2 com.sleepycat.je.tree.IN.setGeneration()V: root-Branch
   * 3 Weak Mutation 123: com.sleepycat.je.tree.IN.setGeneration()V:302 - DeleteStatement: getNextGeneration()J
   */
  @Test
  public void test8()  throws Throwable  {
      BIN bIN0 = new BIN();
      assertNotNull(bIN0);
      
      bIN0.setGeneration();
      assertEquals(296L, bIN0.getGeneration());
      assertEquals(103271L, bIN0.getLastId());
  }
}
