/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.MapLN;

@RunWith(EvoSuiteRunner.class)
public class TestDBIN_5 {


  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 Weak Mutation 16: com.sleepycat.je.tree.DBIN.getMainTreeKey()[B:74 - DeleteField: dupKey[B
   * 2 com.sleepycat.je.tree.DBIN.getMainTreeKey()[B: root-Branch
   * 3 Weak Mutation 16: com.sleepycat.je.tree.DBIN.getMainTreeKey()[B:74 - DeleteField: dupKey[B
   */
  @Test
  public void test5()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      DatabaseImpl databaseImpl0 = mapLN0.getDatabase();
      byte[] byteArray0 = new byte[3];
      DBIN dBIN0 = new DBIN(databaseImpl0, byteArray0, (int) (byte)1, byteArray0, (-263));
      dBIN0.getMainTreeKey();
      assertEquals(4294970798L, mapLN0.getNextNodeId());
      assertEquals("<dbin>\n  <dupkey><key v=\"0 0 0 \"/></dupkey>\n  <node>4294970794</node>\n  <idkey><key v=\"0 0 0 \"/></idkey>\n  <dirty val=\"false\"/>\n  <generation val=\"0\"/>\n  <level val=\"fffffef9\"/>\n  <isRoot val=\"false\"/>\n  <entries nEntries=\"0\">\n  </entries>\n</dbin>", dBIN0.toString());
  }
}
