/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.tree.INDupDeleteInfo;
import java.nio.ByteBuffer;

@RunWith(EvoSuiteRunner.class)
public class TestINDupDeleteInfo_3 {


  //Test case number: 3
  /*
   * 3 covered goals:
   * 1 Weak Mutation 4: com.sleepycat.je.tree.INDupDeleteInfo.getDeletedDupKey()[B:41 - DeleteField: deletedDupKey[B
   * 2 com.sleepycat.je.tree.INDupDeleteInfo.getDeletedDupKey()[B: root-Branch
   * 3 Weak Mutation 4: com.sleepycat.je.tree.INDupDeleteInfo.getDeletedDupKey()[B:41 - DeleteField: deletedDupKey[B
   */
  @Test
  public void test3()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      INDupDeleteInfo iNDupDeleteInfo0 = new INDupDeleteInfo();
      DatabaseId databaseId0 = iNDupDeleteInfo0.getDatabaseId();
      assertNotNull(databaseId0);
      
      INDupDeleteInfo iNDupDeleteInfo1 = new INDupDeleteInfo(724L, byteArray0, byteArray0, databaseId0);
      byte[] byteArray1 = iNDupDeleteInfo1.getDeletedDupKey();
      assertNotNull(byteArray1);
      assertEquals(724L, iNDupDeleteInfo1.getDeletedNodeId());
  }
}
