/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.log.LogException;
import com.sleepycat.je.tree.MapLN;
import java.nio.ByteBuffer;

@RunWith(EvoSuiteRunner.class)
public class TestMapLN {


  //Test case number: 0
  /*
   * 7 covered goals:
   * 1 Weak Mutation 0: com.sleepycat.je.tree.MapLN.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;)V:27 - ReplaceConstant - 0 -> 1
   * 2 Weak Mutation 8: com.sleepycat.je.tree.MapLN.getDatabase()Lcom/sleepycat/je/dbi/DatabaseImpl;:48 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 3 com.sleepycat.je.tree.MapLN.getDatabase()Lcom/sleepycat/je/dbi/DatabaseImpl;: root-Branch
   * 4 com.sleepycat.je.tree.MapLN.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;)V: root-Branch
   * 5 com.sleepycat.je.tree.MapLN.<init>()V: root-Branch
   * 6 Weak Mutation 0: com.sleepycat.je.tree.MapLN.<init>(Lcom/sleepycat/je/dbi/DatabaseImpl;)V:27 - ReplaceConstant - 0 -> 1
   * 7 Weak Mutation 8: com.sleepycat.je.tree.MapLN.getDatabase()Lcom/sleepycat/je/dbi/DatabaseImpl;:48 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   */
  @Test
  public void test0()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      DatabaseImpl databaseImpl0 = mapLN0.getDatabase();
      MapLN mapLN1 = new MapLN(databaseImpl0);
      assertEquals("<com.sleepycat.je.tree.MapLN/596", mapLN1.shortDescription());
  }

  //Test case number: 1
  /*
   * 39 covered goals:
   * 1 Weak Mutation 2: com.sleepycat.je.tree.MapLN.isDeleted()Z:39 - DeleteField: deletedZ
   * 2 Weak Mutation 3: com.sleepycat.je.tree.MapLN.makeDeleted()V:43 - ReplaceConstant - 1 -> 0
   * 3 Weak Mutation 4: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 4 Weak Mutation 5: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteStatement: getTree()Lcom/sleepycat/je/tree/Tree;
   * 5 Weak Mutation 6: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - ReplaceConstant - 1 -> 0
   * 6 Weak Mutation 7: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteStatement: setRoot(Lcom/sleepycat/je/tree/ChildReference;Z)V
   * 7 Weak Mutation 59: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - DeleteStatement: getLogSize()I
   * 8 Weak Mutation 58: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 9 Weak Mutation 63: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> *
   * 10 Weak Mutation 62: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> /
   * 11 Weak Mutation 61: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> %
   * 12 Weak Mutation 60: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> -
   * 13 Weak Mutation 68: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> *
   * 14 Weak Mutation 65: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> -
   * 15 Weak Mutation 66: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> %
   * 16 Weak Mutation 67: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> /
   * 17 Weak Mutation 64: com.sleepycat.je.tree.MapLN.getLogSize()I:102 - DeleteStatement: getBooleanLogSize()I
   * 18 com.sleepycat.je.tree.MapLN.getLogSize()I: root-Branch
   * 19 com.sleepycat.je.tree.MapLN.makeDeleted()V: root-Branch
   * 20 Weak Mutation 1: com.sleepycat.je.tree.MapLN.isDeleted()Z:39 - InsertUnaryOp Negation
   * 21 Weak Mutation 1: com.sleepycat.je.tree.MapLN.isDeleted()Z:39 - InsertUnaryOp Negation
   * 22 Weak Mutation 2: com.sleepycat.je.tree.MapLN.isDeleted()Z:39 - DeleteField: deletedZ
   * 23 Weak Mutation 3: com.sleepycat.je.tree.MapLN.makeDeleted()V:43 - ReplaceConstant - 1 -> 0
   * 24 Weak Mutation 4: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 25 Weak Mutation 5: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteStatement: getTree()Lcom/sleepycat/je/tree/Tree;
   * 26 Weak Mutation 6: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - ReplaceConstant - 1 -> 0
   * 27 Weak Mutation 7: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteStatement: setRoot(Lcom/sleepycat/je/tree/ChildReference;Z)V
   * 28 Weak Mutation 59: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - DeleteStatement: getLogSize()I
   * 29 Weak Mutation 58: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 30 Weak Mutation 63: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> *
   * 31 Weak Mutation 62: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> /
   * 32 Weak Mutation 61: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> %
   * 33 Weak Mutation 60: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> -
   * 34 Weak Mutation 68: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> *
   * 35 Weak Mutation 64: com.sleepycat.je.tree.MapLN.getLogSize()I:102 - DeleteStatement: getBooleanLogSize()I
   * 36 Weak Mutation 65: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> -
   * 37 Weak Mutation 66: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> %
   * 38 Weak Mutation 67: com.sleepycat.je.tree.MapLN.getLogSize()I:101 - ReplaceArithmeticOperator + -> /
   * 39 com.sleepycat.je.tree.MapLN.isDeleted()Z: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      mapLN0.makeDeleted();
      int int0 = mapLN0.getLogSize();
      assertEquals("<mapLN>\n  <node>0</node>\n</mapLN>\n<deleted val=\"true\">\n<database id=\"0\"/>", mapLN0.toString());
      assertEquals(32, int0);
  }

  //Test case number: 2
  /*
   * 8 covered goals:
   * 1 Weak Mutation 9: com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V:56 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 2 Weak Mutation 10: com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V:56 - DeleteStatement: getDbEnvironment()Lcom/sleepycat/je/dbi/EnvironmentImpl;
   * 3 Weak Mutation 11: com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V:56 - DeleteStatement: setEnvironmentImpl(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V
   * 4 com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V: root-Branch
   * 5 Weak Mutation 8: com.sleepycat.je.tree.MapLN.getDatabase()Lcom/sleepycat/je/dbi/DatabaseImpl;:48 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 6 Weak Mutation 9: com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V:56 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 7 Weak Mutation 10: com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V:56 - DeleteStatement: getDbEnvironment()Lcom/sleepycat/je/dbi/EnvironmentImpl;
   * 8 Weak Mutation 11: com.sleepycat.je.tree.MapLN.postFetchInit(Lcom/sleepycat/je/dbi/DatabaseImpl;J)V:56 - DeleteStatement: setEnvironmentImpl(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V
   */
  @Test
  public void test2()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      DatabaseImpl databaseImpl0 = mapLN0.getDatabase();
      // Undeclared exception!
      try {
        mapLN0.postFetchInit(databaseImpl0, 13L);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 3
  /*
   * 97 covered goals:
   * 1 Weak Mutation 38: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteField: deletedZ
   * 2 Weak Mutation 3: com.sleepycat.je.tree.MapLN.makeDeleted()V:43 - ReplaceConstant - 1 -> 0
   * 3 Weak Mutation 4: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 4 Weak Mutation 5: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteStatement: getTree()Lcom/sleepycat/je/tree/Tree;
   * 5 Weak Mutation 6: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - ReplaceConstant - 1 -> 0
   * 6 Weak Mutation 7: com.sleepycat.je.tree.MapLN.makeDeleted()V:44 - DeleteStatement: setRoot(Lcom/sleepycat/je/tree/ChildReference;Z)V
   * 7 Weak Mutation 12: com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;:60 - ReplaceConstant - 0 -> 1
   * 8 Weak Mutation 13: com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;:60 - ReplaceConstant - 1 -> 0
   * 9 Weak Mutation 14: com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;:60 - DeleteStatement: dumpString(IZ)Ljava/lang/String;
   * 10 Weak Mutation 15: com.sleepycat.je.tree.MapLN.beginTag()Ljava/lang/String;:64 - ReplaceConstant - <mapLN> -> 
   * 11 Weak Mutation 17: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp Negation of nSpaces
   * 12 Weak Mutation 16: com.sleepycat.je.tree.MapLN.endTag()Ljava/lang/String;:68 - ReplaceConstant - </mapLN> -> 
   * 13 Weak Mutation 19: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC -1 nSpaces
   * 14 Weak Mutation 18: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC 1 nSpaces
   * 15 Weak Mutation 21: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC 1 dumpTags
   * 16 Weak Mutation 20: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp Negation of dumpTags
   * 17 Weak Mutation 23: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 18 Weak Mutation 22: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC -1 dumpTags
   * 19 Weak Mutation 25: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 1
   * 20 Weak Mutation 24: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 0
   * 21 Weak Mutation 27: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 9
   * 22 Weak Mutation 26: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> -1
   * 23 Weak Mutation 29: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - DeleteStatement: append(C)Ljava/lang/StringBuffer;
   * 24 Weak Mutation 28: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 11
   * 25 Weak Mutation 31: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - InsertUnaryOp IINC 1 nSpaces
   * 26 Weak Mutation 30: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - InsertUnaryOp Negation of nSpaces
   * 27 Weak Mutation 34: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 28 Weak Mutation 35: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - ReplaceConstant - <deleted val=" -> 
   * 29 Weak Mutation 32: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - InsertUnaryOp IINC -1 nSpaces
   * 30 Weak Mutation 33: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - DeleteStatement: indent(I)Ljava/lang/String;
   * 31 Weak Mutation 39: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteStatement: toString(Z)Ljava/lang/String;
   * 32 Weak Mutation 36: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 33 Weak Mutation 37: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - InsertUnaryOp Negation
   * 34 Weak Mutation 42: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:77 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 35 Weak Mutation 43: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 0
   * 36 Weak Mutation 40: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 37 Weak Mutation 41: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:77 - ReplaceConstant - "> -> 
   * 38 Weak Mutation 46: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 9
   * 39 Weak Mutation 47: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 11
   * 40 Weak Mutation 44: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 1
   * 41 Weak Mutation 45: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> -1
   * 42 Weak Mutation 51: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - InsertUnaryOp IINC 1 nSpaces
   * 43 Weak Mutation 50: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - InsertUnaryOp Negation of nSpaces
   * 44 Weak Mutation 49: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 45 Weak Mutation 48: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - DeleteStatement: append(C)Ljava/lang/StringBuffer;
   * 46 Weak Mutation 55: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:80 - DeleteStatement: toString()Ljava/lang/String;
   * 47 Weak Mutation 54: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 48 Weak Mutation 53: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - DeleteStatement: dumpString(I)Ljava/lang/String;
   * 49 Weak Mutation 52: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - InsertUnaryOp IINC -1 nSpaces
   * 50 Weak Mutation 12: com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;:60 - ReplaceConstant - 0 -> 1
   * 51 Weak Mutation 13: com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;:60 - ReplaceConstant - 1 -> 0
   * 52 Weak Mutation 14: com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;:60 - DeleteStatement: dumpString(IZ)Ljava/lang/String;
   * 53 Weak Mutation 15: com.sleepycat.je.tree.MapLN.beginTag()Ljava/lang/String;:64 - ReplaceConstant - <mapLN> -> 
   * 54 Weak Mutation 17: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp Negation of nSpaces
   * 55 Weak Mutation 16: com.sleepycat.je.tree.MapLN.endTag()Ljava/lang/String;:68 - ReplaceConstant - </mapLN> -> 
   * 56 Weak Mutation 19: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC -1 nSpaces
   * 57 Weak Mutation 18: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC 1 nSpaces
   * 58 Weak Mutation 21: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC 1 dumpTags
   * 59 Weak Mutation 20: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp Negation of dumpTags
   * 60 Weak Mutation 23: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 61 Weak Mutation 22: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:73 - InsertUnaryOp IINC -1 dumpTags
   * 62 Weak Mutation 25: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 1
   * 63 Weak Mutation 24: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 0
   * 64 Weak Mutation 27: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 9
   * 65 Weak Mutation 26: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> -1
   * 66 Weak Mutation 29: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - DeleteStatement: append(C)Ljava/lang/StringBuffer;
   * 67 Weak Mutation 28: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:74 - ReplaceConstant - 10 -> 11
   * 68 Weak Mutation 31: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - InsertUnaryOp IINC 1 nSpaces
   * 69 Weak Mutation 30: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - InsertUnaryOp Negation of nSpaces
   * 70 Weak Mutation 34: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 71 Weak Mutation 35: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - ReplaceConstant - <deleted val=" -> 
   * 72 Weak Mutation 32: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - InsertUnaryOp IINC -1 nSpaces
   * 73 Weak Mutation 33: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:75 - DeleteStatement: indent(I)Ljava/lang/String;
   * 74 Weak Mutation 38: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteField: deletedZ
   * 75 Weak Mutation 39: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteStatement: toString(Z)Ljava/lang/String;
   * 76 Weak Mutation 36: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 77 Weak Mutation 37: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - InsertUnaryOp Negation
   * 78 Weak Mutation 42: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:77 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 79 Weak Mutation 43: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 0
   * 80 Weak Mutation 40: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:76 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 81 Weak Mutation 41: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:77 - ReplaceConstant - "> -> 
   * 82 Weak Mutation 46: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 9
   * 83 Weak Mutation 47: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 11
   * 84 Weak Mutation 44: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> 1
   * 85 Weak Mutation 45: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - ReplaceConstant - 10 -> -1
   * 86 Weak Mutation 51: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - InsertUnaryOp IINC 1 nSpaces
   * 87 Weak Mutation 50: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - InsertUnaryOp Negation of nSpaces
   * 88 Weak Mutation 49: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 89 Weak Mutation 48: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:78 - DeleteStatement: append(C)Ljava/lang/StringBuffer;
   * 90 Weak Mutation 55: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:80 - DeleteStatement: toString()Ljava/lang/String;
   * 91 Weak Mutation 54: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   * 92 Weak Mutation 53: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - DeleteStatement: dumpString(I)Ljava/lang/String;
   * 93 Weak Mutation 52: com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;:79 - InsertUnaryOp IINC -1 nSpaces
   * 94 com.sleepycat.je.tree.MapLN.toString()Ljava/lang/String;: root-Branch
   * 95 com.sleepycat.je.tree.MapLN.endTag()Ljava/lang/String;: root-Branch
   * 96 com.sleepycat.je.tree.MapLN.dumpString(IZ)Ljava/lang/String;: root-Branch
   * 97 com.sleepycat.je.tree.MapLN.beginTag()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      mapLN0.makeDeleted();
      String string0 = mapLN0.toString();
      assertEquals(true, mapLN0.isDeleted());
      assertEquals("<mapLN>\n  <node>0</node>\n</mapLN>\n<deleted val=\"true\">\n<database id=\"0\"/>", string0);
  }

  //Test case number: 4
  /*
   * 3 covered goals:
   * 1 Weak Mutation 56: com.sleepycat.je.tree.MapLN.getTransactionalLogType()Lcom/sleepycat/je/log/LogEntryType;:87 - DeleteField: LOG_MAPLN_TRANSACTIONALLcom/sleepycat/je/log/LogEntryType;
   * 2 com.sleepycat.je.tree.MapLN.getTransactionalLogType()Lcom/sleepycat/je/log/LogEntryType;: root-Branch
   * 3 Weak Mutation 56: com.sleepycat.je.tree.MapLN.getTransactionalLogType()Lcom/sleepycat/je/log/LogEntryType;:87 - DeleteField: LOG_MAPLN_TRANSACTIONALLcom/sleepycat/je/log/LogEntryType;
   */
  @Test
  public void test4()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      LogEntryType logEntryType0 = mapLN0.getTransactionalLogType();
      assertNotNull(logEntryType0);
      assertEquals(905L, mapLN0.getLastId());
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 Weak Mutation 57: com.sleepycat.je.tree.MapLN.getLogType()Lcom/sleepycat/je/log/LogEntryType;:94 - DeleteField: LOG_MAPLNLcom/sleepycat/je/log/LogEntryType;
   * 2 com.sleepycat.je.tree.MapLN.getLogType()Lcom/sleepycat/je/log/LogEntryType;: root-Branch
   * 3 Weak Mutation 57: com.sleepycat.je.tree.MapLN.getLogType()Lcom/sleepycat/je/log/LogEntryType;:94 - DeleteField: LOG_MAPLNLcom/sleepycat/je/log/LogEntryType;
   */
  @Test
  public void test5()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      LogEntryType logEntryType0 = mapLN0.getLogType();
      assertNotNull(logEntryType0);
      assertEquals(911L, mapLN0.getLastId());
  }

  //Test case number: 6
  /*
   * 7 covered goals:
   * 1 Weak Mutation 76: com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V:119 - InsertUnaryOp IINC -1 entryTypeVersion
   * 2 Weak Mutation 74: com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V:119 - InsertUnaryOp Negation of entryTypeVersion
   * 3 Weak Mutation 75: com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V:119 - InsertUnaryOp IINC 1 entryTypeVersion
   * 4 com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V: root-Branch
   * 5 Weak Mutation 76: com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V:119 - InsertUnaryOp IINC -1 entryTypeVersion
   * 6 Weak Mutation 74: com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V:119 - InsertUnaryOp Negation of entryTypeVersion
   * 7 Weak Mutation 75: com.sleepycat.je.tree.MapLN.readFromLog(Ljava/nio/ByteBuffer;B)V:119 - InsertUnaryOp IINC 1 entryTypeVersion
   */
  @Test
  public void test6()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      // Undeclared exception!
      try {
        mapLN0.readFromLog((ByteBuffer) null, (byte) (-123));
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 7
  /*
   * 7 covered goals:
   * 1 Weak Mutation 85: com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V:129 - DeleteStatement: dumpLog(Ljava/lang/StringBuffer;Z)V
   * 2 Weak Mutation 84: com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V:129 - ReplaceConstant - 1 -> 0
   * 3 Weak Mutation 83: com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V:129 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   * 4 com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V: root-Branch
   * 5 Weak Mutation 85: com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V:129 - DeleteStatement: dumpLog(Ljava/lang/StringBuffer;Z)V
   * 6 Weak Mutation 84: com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V:129 - ReplaceConstant - 1 -> 0
   * 7 Weak Mutation 83: com.sleepycat.je.tree.MapLN.dumpLogAdditional(Ljava/lang/StringBuffer;Z)V:129 - DeleteField: databaseImplLcom/sleepycat/je/dbi/DatabaseImpl;
   */
  @Test
  public void test7()  throws Throwable  {
      MapLN mapLN0 = new MapLN();
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "<mapLN>\n  <node>0</node>\n</mapLN>\n<deleted val=\"false\">\n<database id=\"0\"/>");
      mapLN0.dumpLogAdditional(stringBuffer0, false);
      assertEquals(182, stringBuffer0.capacity());
      assertEquals(929L, mapLN0.getNextNodeId());
  }
}
