/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.DupCountLN;
import com.sleepycat.je.tree.Node;
import com.sleepycat.je.tree.TreeLocation;

@RunWith(EvoSuiteRunner.class)
public class TestNode_2 {


  //Test case number: 2
  /*
   * 17 covered goals:
   * 1 Weak Mutation 29: com.sleepycat.je.tree.Node.getMemorySizeIncludedByParent()J:119 - ReplaceConstant - 0 -> -1
   * 2 Weak Mutation 28: com.sleepycat.je.tree.Node.getMemorySizeIncludedByParent()J:119 - ReplaceConstant - 0 -> 1
   * 3 com.sleepycat.je.tree.Node.getMemorySizeIncludedByParent()J: root-Branch
   * 4 Weak Mutation 10: com.sleepycat.je.tree.Node.<init>(Z)V:38 - DeleteStatement: getNextNodeId()J
   * 5 Weak Mutation 11: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - InsertUnaryOp Negation
   * 6 Weak Mutation 12: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - DeleteField: lastAllocatedIdJ
   * 7 Weak Mutation 13: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceConstant - 1 -> 0
   * 8 Weak Mutation 14: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceConstant - 1 -> -1
   * 9 Weak Mutation 15: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceConstant - 1 -> 2
   * 10 Weak Mutation 17: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceArithmeticOperator + -> %
   * 11 Weak Mutation 16: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceArithmeticOperator + -> -
   * 12 Weak Mutation 19: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceArithmeticOperator + -> *
   * 13 Weak Mutation 18: com.sleepycat.je.tree.Node.getNextNodeId()J:45 - ReplaceArithmeticOperator + -> /
   * 14 Weak Mutation 29: com.sleepycat.je.tree.Node.getMemorySizeIncludedByParent()J:119 - ReplaceConstant - 0 -> -1
   * 15 Weak Mutation 28: com.sleepycat.je.tree.Node.getMemorySizeIncludedByParent()J:119 - ReplaceConstant - 0 -> 1
   * 16 com.sleepycat.je.tree.Node.getNextNodeId()J: root-Branch
   * 17 com.sleepycat.je.tree.Node.<init>(Z)V: I7 Branch 2 IFEQ L37 - false
   */
  @Test
  public void test2()  throws Throwable  {
      DupCountLN dupCountLN0 = new DupCountLN((-1401));
      long long0 = dupCountLN0.getMemorySizeIncludedByParent();
      assertEquals("<dupCountLN>\n  <count v=\"-1401\"/>\n  <node>1113</node>\n  <data></data>\n</dupCountLN>", dupCountLN0.toString());
      assertEquals(0L, long0);
  }
}
