/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.tree.DupCountLN;
import com.sleepycat.je.tree.LN;
import com.sleepycat.je.tree.NameLN;

@RunWith(EvoSuiteRunner.class)
public class TestLN_5 {


  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 Weak Mutation 60: com.sleepycat.je.tree.LN.isValidForDelete()Z:98 - ReplaceConstant - 0 -> 1
   * 2 com.sleepycat.je.tree.LN.isValidForDelete()Z: root-Branch
   * 3 Weak Mutation 60: com.sleepycat.je.tree.LN.isValidForDelete()Z:98 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test5()  throws Throwable  {
      NameLN nameLN0 = new NameLN();
      boolean boolean0 = nameLN0.isValidForDelete();
      assertEquals(false, boolean0);
  }
}
