/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.ChildReference;
import com.sleepycat.je.tree.CursorsExistException;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.DIN;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.LN;
import com.sleepycat.je.tree.MapLN;
import com.sleepycat.je.tree.Node;
import com.sleepycat.je.tree.NodeNotEmptyException;
import com.sleepycat.je.tree.Tree;
import com.sleepycat.je.tree.TreeLocation;
import com.sleepycat.je.tree.TreeStats;
import com.sleepycat.je.tree.TreeWalkerStatsAccumulator;
import com.sleepycat.je.tree.WithRootLatched;
import java.util.List;

@RunWith(EvoSuiteRunner.class)
public class TestTree_21 {


  //Test case number: 21
  /*
   * 13 covered goals:
   * 1 Weak Mutation 292: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - InsertUnaryOp Negation
   * 2 Weak Mutation 293: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - InsertUnaryOp IINC 1
   * 3 Weak Mutation 294: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - InsertUnaryOp IINC -1
   * 4 Weak Mutation 295: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - ReplaceConstant - 0 -> 1
   * 5 com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;: root-Branch
   * 6 Weak Mutation 314: com.sleepycat.je.tree.Tree.getNextBinInternal(ZLcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:987 - ReplaceConstant - TYPE ERROR? -> 
   * 7 Weak Mutation 296: com.sleepycat.je.tree.Tree.getNextBinInternal(ZLcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:890 - DeleteStatement: getNEntries()I
   * 8 Weak Mutation 299: com.sleepycat.je.tree.Tree.getNextBinInternal(ZLcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:890 - ReplaceComparisonOperator != -> -1
   * 9 Weak Mutation 300: com.sleepycat.je.tree.Tree.getNextBinInternal(ZLcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:891 - DeleteStatement: getIdentifierKey()[B
   * 10 Weak Mutation 292: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - InsertUnaryOp Negation
   * 11 Weak Mutation 293: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - InsertUnaryOp IINC 1
   * 12 Weak Mutation 294: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - InsertUnaryOp IINC -1
   * 13 Weak Mutation 295: com.sleepycat.je.tree.Tree.getPrevBin(Lcom/sleepycat/je/tree/BIN;Z)Lcom/sleepycat/je/tree/BIN;:883 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test21()  throws Throwable  {
      Tree tree0 = new Tree();
      DBIN dBIN0 = new DBIN();
      // Undeclared exception!
      try {
        tree0.getPrevBin((BIN) dBIN0, true);
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * TYPE ERROR?
         */
      }
  }
}
