/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.log.LogException;
import com.sleepycat.je.tree.INDeleteInfo;
import java.nio.ByteBuffer;

@RunWith(EvoSuiteRunner.class)
public class TestINDeleteInfo_12 {


  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 com.sleepycat.je.tree.INDeleteInfo.postLogWork(J)V: root-Branch
   * 2 Weak Mutation 0: com.sleepycat.je.tree.INDeleteInfo.<init>(J[BLcom/sleepycat/je/dbi/DatabaseId;)V:22 - InsertUnaryOp Negation
   */
  @Test
  public void test12()  throws Throwable  {
      byte[] byteArray0 = new byte[26];
      DatabaseId databaseId0 = new DatabaseId();
      INDeleteInfo iNDeleteInfo0 = new INDeleteInfo((long) (byte)77, byteArray0, databaseId0);
      iNDeleteInfo0.postLogWork((long) (byte)0);
      assertEquals(77L, iNDeleteInfo0.getDeletedNodeId());
  }
}
