/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.SearchResult;

@RunWith(EvoSuiteRunner.class)
public class TestSearchResult_1 {


  //Test case number: 1
  /*
   * 9 covered goals:
   * 1 Weak Mutation 18: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteField: parentLcom/sleepycat/je/tree/IN;
   * 2 Weak Mutation 21: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteField: parentLcom/sleepycat/je/tree/IN;
   * 3 Weak Mutation 23: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteStatement: toString(J)Ljava/lang/String;
   * 4 Weak Mutation 22: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteStatement: getNodeId()J
   * 5 com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;: I19 Branch 1 IFNONNULL L19 - true
   * 6 Weak Mutation 18: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteField: parentLcom/sleepycat/je/tree/IN;
   * 7 Weak Mutation 21: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteField: parentLcom/sleepycat/je/tree/IN;
   * 8 Weak Mutation 23: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteStatement: toString(J)Ljava/lang/String;
   * 9 Weak Mutation 22: com.sleepycat.je.tree.SearchResult.toString()Ljava/lang/String;:19 - DeleteStatement: getNodeId()J
   */
  @Test
  public void test1()  throws Throwable  {
      SearchResult searchResult0 = new SearchResult();
      DatabaseImpl databaseImpl0 = new DatabaseImpl();
      byte[] byteArray0 = new byte[1];
      DBIN dBIN0 = new DBIN(databaseImpl0, byteArray0, 1218, byteArray0, 0);
      searchResult0.parent = (IN) dBIN0;
      assertEquals(185L, databaseImpl0.getEofNodeId());
      
      String string0 = searchResult0.toString();
      assertEquals("exactParentFound=false keepSearching=true parent=186 index=-1 childNotResident=false", string0);
  }
}
