/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.tree.DupCountLN;

@RunWith(EvoSuiteRunner.class)
public class TestDupCountLN_8 {


  //Test case number: 8
  /*
   * 22 covered goals:
   * 1 Weak Mutation 58: com.sleepycat.je.tree.DupCountLN.isDeleted()Z:53 - ReplaceConstant - 0 -> 1
   * 2 Weak Mutation 136: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> *
   * 3 Weak Mutation 129: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 1
   * 4 Weak Mutation 128: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 0
   * 5 Weak Mutation 131: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 3
   * 6 Weak Mutation 130: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> -1
   * 7 Weak Mutation 133: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> -
   * 8 Weak Mutation 132: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 5
   * 9 Weak Mutation 135: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> /
   * 10 Weak Mutation 134: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> %
   * 11 com.sleepycat.je.tree.DupCountLN.isDeleted()Z: root-Branch
   * 12 com.sleepycat.je.tree.DupCountLN.getLogSize()I: root-Branch
   * 13 Weak Mutation 58: com.sleepycat.je.tree.DupCountLN.isDeleted()Z:53 - ReplaceConstant - 0 -> 1
   * 14 Weak Mutation 136: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> *
   * 15 Weak Mutation 129: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 1
   * 16 Weak Mutation 128: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 0
   * 17 Weak Mutation 131: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 3
   * 18 Weak Mutation 130: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> -1
   * 19 Weak Mutation 133: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> -
   * 20 Weak Mutation 132: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceConstant - 4 -> 5
   * 21 Weak Mutation 135: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> /
   * 22 Weak Mutation 134: com.sleepycat.je.tree.DupCountLN.getLogSize()I:110 - ReplaceArithmeticOperator + -> %
   */
  @Test
  public void test8()  throws Throwable  {
      DupCountLN dupCountLN0 = new DupCountLN(1646);
      int int0 = dupCountLN0.getLogSize();
      assertEquals("<com.sleepycat.je.tree.DupCountLN/10000730", dupCountLN0.shortDescription());
      assertEquals(17, int0);
  }
}
