/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.CursorImpl;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.DBIN;
import com.sleepycat.je.tree.IN;
import com.sleepycat.je.tree.Node;
import com.sleepycat.je.tree.SearchResult;

@RunWith(EvoSuiteRunner.class)
public class TestBIN_22 {


  //Test case number: 22
  /*
   * 14 covered goals:
   * 1 Weak Mutation 250: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:380 - DeleteField: cursorSetLcom/sleepycat/je/utilint/TinyHashSet;
   * 2 Weak Mutation 251: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:380 - ReplaceComparisonOperator = null -> != null
   * 3 Weak Mutation 252: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:381 - DeleteField: cursorSetLcom/sleepycat/je/utilint/TinyHashSet;
   * 4 Weak Mutation 253: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:381 - DeleteStatement: iterator()Ljava/util/Iterator;
   * 5 Weak Mutation 254: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:382 - DeleteStatement: hasNext()Z
   * 6 Weak Mutation 255: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:382 - ReplaceComparisonOperator == -> !=
   * 7 com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V: I4 Branch 28 IFNULL L380 - false
   * 8 com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V: I15 Branch 29 IFEQ L382 - true
   * 9 Weak Mutation 254: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:382 - DeleteStatement: hasNext()Z
   * 10 Weak Mutation 255: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:382 - ReplaceComparisonOperator == -> !=
   * 11 Weak Mutation 252: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:381 - DeleteField: cursorSetLcom/sleepycat/je/utilint/TinyHashSet;
   * 12 Weak Mutation 253: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:381 - DeleteStatement: iterator()Ljava/util/Iterator;
   * 13 Weak Mutation 250: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:380 - DeleteField: cursorSetLcom/sleepycat/je/utilint/TinyHashSet;
   * 14 Weak Mutation 251: com.sleepycat.je.tree.BIN.adjustCursorsForInsert(I)V:380 - ReplaceComparisonOperator = null -> != null
   */
  @Test
  public void test22()  throws Throwable  {
      BIN bIN0 = new BIN();
      bIN0.adjustCursorsForInsert((-1433));
      assertEquals(12261L, bIN0.getNextNodeId());
      assertEquals(12261L, bIN0.getLastId());
  }
}
