/*
 * This file was automatically generated by EvoSuite
 */

package smashed;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import smashed.Edge;
import smashed.FinishTimeWorkSpace;
import smashed.Graph;
import smashed.Vertex;
import smashed.WorkSpace;

@RunWith(EvoSuiteRunner.class)
public class TestGraph_7 {


  //Test case number: 7
  /*
   * 74 covered goals:
   * 1 Weak Mutation 272: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - ReplaceComparisonOperator >= -> -1
   * 2 Weak Mutation 275: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - InsertUnaryOp IINC 1
   * 3 Weak Mutation 274: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - InsertUnaryOp Negation
   * 4 Weak Mutation 273: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - DeleteField: verticesLjava/util/LinkedList;
   * 5 Weak Mutation 277: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - DeleteStatement: get(I)Ljava/lang/Object;
   * 6 Weak Mutation 276: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - InsertUnaryOp IINC -1
   * 7 Weak Mutation 279: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> 1
   * 8 Weak Mutation 278: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> 0
   * 9 Weak Mutation 282: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> -2147483648
   * 10 Weak Mutation 281: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> 2147483646
   * 11 Weak Mutation 280: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> -1
   * 12 Weak Mutation 293: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - ReplaceComparisonOperator >= -> -1
   * 13 Weak Mutation 294: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - DeleteField: verticesLjava/util/LinkedList;
   * 14 Weak Mutation 295: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - InsertUnaryOp Negation
   * 15 Weak Mutation 296: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - InsertUnaryOp IINC 1
   * 16 Weak Mutation 297: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - InsertUnaryOp IINC -1
   * 17 Weak Mutation 298: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - DeleteStatement: get(I)Ljava/lang/Object;
   * 18 Weak Mutation 305: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - ReplaceComparisonOperator == -> -2
   * 19 Weak Mutation 299: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - InsertUnaryOp Negation
   * 20 Weak Mutation 300: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - InsertUnaryOp +1
   * 21 Weak Mutation 301: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - InsertUnaryOp -1
   * 22 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I17 Branch 20 IF_ICMPGE L243 - false
   * 23 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I63 Branch 21 IF_ICMPGE L259 - false
   * 24 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I76 Branch 22 IFEQ L262 - true
   * 25 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I234 Branch 29 IF_ICMPGE L357 - false
   * 26 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I268 Branch 30 IF_ICMPGE L369 - false
   * 27 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I287 Branch 31 IFNONNULL L377 - false
   * 28 Weak Mutation 275: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - InsertUnaryOp IINC 1
   * 29 Weak Mutation 274: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - InsertUnaryOp Negation
   * 30 Weak Mutation 273: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - DeleteField: verticesLjava/util/LinkedList;
   * 31 Weak Mutation 272: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - ReplaceComparisonOperator >= -> -1
   * 32 Weak Mutation 279: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> 1
   * 33 Weak Mutation 278: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> 0
   * 34 Weak Mutation 277: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - DeleteStatement: get(I)Ljava/lang/Object;
   * 35 Weak Mutation 276: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:245 - InsertUnaryOp IINC -1
   * 36 Weak Mutation 283: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:251 - ReplaceConstant - 0 -> 1
   * 37 Weak Mutation 282: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> -2147483648
   * 38 Weak Mutation 281: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> 2147483646
   * 39 Weak Mutation 280: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:247 - ReplaceConstant - 2147483647 -> -1
   * 40 Weak Mutation 287: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - InsertUnaryOp IINC -1
   * 41 Weak Mutation 286: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - InsertUnaryOp IINC 1
   * 42 Weak Mutation 285: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - InsertUnaryOp Negation
   * 43 Weak Mutation 284: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - ReplaceConstant - 0 -> 1
   * 44 Weak Mutation 262: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:238 - DeleteStatement: size()I
   * 45 Weak Mutation 263: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - ReplaceConstant - 0 -> 1
   * 46 Weak Mutation 261: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:238 - DeleteField: verticesLjava/util/LinkedList;
   * 47 Weak Mutation 266: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - InsertUnaryOp IINC -1
   * 48 Weak Mutation 267: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - InsertUnaryOp Negation
   * 49 Weak Mutation 264: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - InsertUnaryOp Negation
   * 50 Weak Mutation 265: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - InsertUnaryOp IINC 1
   * 51 Weak Mutation 271: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - ReplaceComparisonOperator >= -> >
   * 52 Weak Mutation 268: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - InsertUnaryOp IINC 1
   * 53 Weak Mutation 269: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:243 - InsertUnaryOp IINC -1
   * 54 Weak Mutation 305: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - ReplaceComparisonOperator == -> -2
   * 55 Weak Mutation 288: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - InsertUnaryOp Negation
   * 56 Weak Mutation 289: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - InsertUnaryOp IINC 1
   * 57 Weak Mutation 290: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - InsertUnaryOp IINC -1
   * 58 Weak Mutation 292: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - ReplaceComparisonOperator >= -> >
   * 59 Weak Mutation 293: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:259 - ReplaceComparisonOperator >= -> -1
   * 60 Weak Mutation 294: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - DeleteField: verticesLjava/util/LinkedList;
   * 61 Weak Mutation 295: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - InsertUnaryOp Negation
   * 62 Weak Mutation 296: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - InsertUnaryOp IINC 1
   * 63 Weak Mutation 297: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - InsertUnaryOp IINC -1
   * 64 Weak Mutation 298: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:261 - DeleteStatement: get(I)Ljava/lang/Object;
   * 65 Weak Mutation 299: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - InsertUnaryOp Negation
   * 66 Weak Mutation 300: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - InsertUnaryOp +1
   * 67 Weak Mutation 301: smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;:262 - InsertUnaryOp -1
   * 68 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I17 Branch 20 IF_ICMPGE L243 - true
   * 69 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I63 Branch 21 IF_ICMPGE L259 - true
   * 70 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I100 Branch 23 IFEQ L279 - true
   * 71 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I100 Branch 23 IFEQ L279 - false
   * 72 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I120 Branch 24 IF_ICMPGE L288 - true
   * 73 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I234 Branch 29 IF_ICMPGE L357 - true
   * 74 smashed.Graph.Prim(Lsmashed/Vertex;)Lsmashed/Graph;: I268 Branch 30 IF_ICMPGE L369 - true
   */
  @Test
  public void test7()  throws Throwable  {
      Graph graph0 = new Graph();
      Vertex vertex0 = new Vertex();
      Edge edge0 = new Edge(vertex0, vertex0, 0);
      graph0.addVertex(edge0.start);
      graph0.Prim(edge0.end);
      assertEquals(Integer.MAX_VALUE, vertex0.VertexCycle);
  }
}
