/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.softlang.company.Employee;
import org.softlang.company.impl.pojo.EmployeeImpl;
import org.softlang.proxy.AccessControl;
import org.softlang.proxy.ProxyEmployee;

@RunWith(EvoSuiteRunner.class)
public class TestProxyEmployee_2 {


  //Test case number: 2
  /*
   * 5 covered goals:
   * 1 Weak Mutation 4: org.softlang.proxy.ProxyEmployee.getAddress()Ljava/lang/String;:27 - DeleteField: subjectLorg/softlang/company/Employee;
   * 2 Weak Mutation 5: org.softlang.proxy.ProxyEmployee.getAddress()Ljava/lang/String;:27 - DeleteStatement: getAddress()Ljava/lang/String;
   * 3 org.softlang.proxy.ProxyEmployee.getAddress()Ljava/lang/String;: root-Branch
   * 4 Weak Mutation 4: org.softlang.proxy.ProxyEmployee.getAddress()Ljava/lang/String;:27 - DeleteField: subjectLorg/softlang/company/Employee;
   * 5 Weak Mutation 5: org.softlang.proxy.ProxyEmployee.getAddress()Ljava/lang/String;:27 - DeleteStatement: getAddress()Ljava/lang/String;
   */
  @Test
  public void test2()  throws Throwable  {
      EmployeeImpl employeeImpl0 = new EmployeeImpl();
      ProxyEmployee proxyEmployee0 = new ProxyEmployee((AccessControl) null, (Employee) employeeImpl0);
      String string0 = proxyEmployee0.getAddress();
      assertNull(string0);
  }
}
