/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.softlang.company.Company;
import org.softlang.company.impl.pojo.CompanyImpl;
import org.softlang.proxy.AccessControl;
import org.softlang.proxy.ProxyCompany;

@RunWith(EvoSuiteRunner.class)
public class TestProxyCompany_0 {


  //Test case number: 0
  /*
   * 6 covered goals:
   * 1 Weak Mutation 0: org.softlang.proxy.ProxyCompany.getName()Ljava/lang/String;:36 - DeleteField: subjectLorg/softlang/company/Company;
   * 2 Weak Mutation 1: org.softlang.proxy.ProxyCompany.getName()Ljava/lang/String;:36 - DeleteStatement: getName()Ljava/lang/String;
   * 3 org.softlang.proxy.ProxyCompany.getName()Ljava/lang/String;: root-Branch
   * 4 org.softlang.proxy.ProxyCompany.<init>(Lorg/softlang/proxy/AccessControl;Lorg/softlang/company/Company;)V: root-Branch
   * 5 Weak Mutation 0: org.softlang.proxy.ProxyCompany.getName()Ljava/lang/String;:36 - DeleteField: subjectLorg/softlang/company/Company;
   * 6 Weak Mutation 1: org.softlang.proxy.ProxyCompany.getName()Ljava/lang/String;:36 - DeleteStatement: getName()Ljava/lang/String;
   */
  @Test
  public void test0()  throws Throwable  {
      AccessControl accessControl0 = new AccessControl();
      CompanyImpl companyImpl0 = new CompanyImpl();
      ProxyCompany proxyCompany0 = new ProxyCompany(accessControl0, (Company) companyImpl0);
      String string0 = proxyCompany0.getName();
      assertNull(string0);
  }
}
