/*
 * This file was automatically generated by EvoSuite
 */

package org.softlang.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.softlang.company.Company;
import org.softlang.company.impl.pojo.CompanyImpl;
import org.softlang.proxy.AccessControl;
import org.softlang.proxy.ProxyCompany;

@RunWith(EvoSuiteRunner.class)
public class TestProxyCompany_1 {


  //Test case number: 1
  /*
   * 5 covered goals:
   * 1 Weak Mutation 2: org.softlang.proxy.ProxyCompany.setName(Ljava/lang/String;)V:40 - DeleteField: subjectLorg/softlang/company/Company;
   * 2 Weak Mutation 3: org.softlang.proxy.ProxyCompany.setName(Ljava/lang/String;)V:40 - DeleteStatement: setName(Ljava/lang/String;)V
   * 3 org.softlang.proxy.ProxyCompany.setName(Ljava/lang/String;)V: root-Branch
   * 4 Weak Mutation 2: org.softlang.proxy.ProxyCompany.setName(Ljava/lang/String;)V:40 - DeleteField: subjectLorg/softlang/company/Company;
   * 5 Weak Mutation 3: org.softlang.proxy.ProxyCompany.setName(Ljava/lang/String;)V:40 - DeleteStatement: setName(Ljava/lang/String;)V
   */
  @Test
  public void test1()  throws Throwable  {
      AccessControl accessControl0 = new AccessControl();
      CompanyImpl companyImpl0 = new CompanyImpl();
      ProxyCompany proxyCompany0 = new ProxyCompany(accessControl0, (Company) companyImpl0);
      proxyCompany0.setName("H>`HNp[Cl</OR8oh`U&");
      assertEquals("H>`HNp[Cl</OR8oh`U&", proxyCompany0.getName());
  }
}
