/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.config.LongConfigParam;

@RunWith(EvoSuiteRunner.class)
public class TestLongConfigParam_4 {


  //Test case number: 4
  /*
   * 20 covered goals:
   * 1 Weak Mutation 51: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - ReplaceConstant - :  -> 
   * 2 Weak Mutation 50: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 3 Weak Mutation 49: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteField: DEBUG_NAMELjava/lang/String;
   * 4 Weak Mutation 55: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 5 Weak Mutation 54: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - ReplaceConstant -  not valid value for  -> 
   * 6 Weak Mutation 53: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 7 Weak Mutation 52: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 8 Weak Mutation 58: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: toString()Ljava/lang/String;
   * 9 Weak Mutation 57: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 10 Weak Mutation 56: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteField: nameLjava/lang/String;
   * 11 Weak Mutation 51: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - ReplaceConstant - :  -> 
   * 12 Weak Mutation 50: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 13 Weak Mutation 49: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteField: DEBUG_NAMELjava/lang/String;
   * 14 Weak Mutation 55: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 15 Weak Mutation 54: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - ReplaceConstant -  not valid value for  -> 
   * 16 Weak Mutation 53: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 17 Weak Mutation 52: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 18 Weak Mutation 58: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: toString()Ljava/lang/String;
   * 19 Weak Mutation 57: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 20 Weak Mutation 56: com.sleepycat.je.config.LongConfigParam.validateValue(Ljava/lang/String;)V:33 - DeleteField: nameLjava/lang/String;
   */
  @Test
  public void test4()  throws Throwable  {
      LongConfigParam longConfigParam0 = new LongConfigParam(" GvgS1YozlbvHg2nq", (Long) 64L, (Long) 64L, (Long) 64L, false, " GvgS1YozlbvHg2nq");
      try {
        longConfigParam0.validateValue(" GvgS1YozlbvHg2nq");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * com.sleepycat.je.config.LongConfigParam:  GvgS1YozlbvHg2nq not valid value for  GvgS1YozlbvHg2nq
         */
      }
  }
}
