/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.config.IntConfigParam;

@RunWith(EvoSuiteRunner.class)
public class TestIntConfigParam_0 {


  //Test case number: 0
  /*
   * 22 covered goals:
   * 1 Weak Mutation 5: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:17 - ReplaceComparisonOperator >= -> ==
   * 2 Weak Mutation 29: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:22 - ReplaceComparisonOperator <= -> <
   * 3 Weak Mutation 0: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:15 - ReplaceComparisonOperator = null -> != null
   * 4 Weak Mutation 1: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:16 - DeleteField: minLjava/lang/Integer;
   * 5 Weak Mutation 2: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:16 - ReplaceComparisonOperator = null -> != null
   * 6 Weak Mutation 3: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:17 - DeleteField: minLjava/lang/Integer;
   * 7 Weak Mutation 4: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:17 - DeleteStatement: compareTo(Ljava/lang/Integer;)I
   * 8 Weak Mutation 5: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:17 - ReplaceComparisonOperator >= -> ==
   * 9 Weak Mutation 25: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:21 - ReplaceComparisonOperator = null -> != null
   * 10 Weak Mutation 24: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:21 - DeleteField: maxLjava/lang/Integer;
   * 11 Weak Mutation 27: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:22 - DeleteStatement: compareTo(Ljava/lang/Integer;)I
   * 12 Weak Mutation 26: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:22 - DeleteField: maxLjava/lang/Integer;
   * 13 Weak Mutation 29: com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V:22 - ReplaceComparisonOperator <= -> <
   * 14 com.sleepycat.je.config.IntConfigParam.validateValue(Ljava/lang/String;)V: root-Branch
   * 15 com.sleepycat.je.config.IntConfigParam.<init>(Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;ZLjava/lang/String;)V: root-Branch
   * 16 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I3 Branch 1 IFNULL L15 - false
   * 17 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I8 Branch 2 IFNULL L16 - true
   * 18 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I8 Branch 2 IFNULL L16 - false
   * 19 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I15 Branch 3 IFGE L17 - true
   * 20 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I48 Branch 4 IFNULL L21 - true
   * 21 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I48 Branch 4 IFNULL L21 - false
   * 22 com.sleepycat.je.config.IntConfigParam.validate(Ljava/lang/Integer;)V: I55 Branch 5 IFLE L22 - true
   */
  @Test
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(1026);
      IntConfigParam intConfigParam0 = new IntConfigParam("# The buffer siz; for faulting in ob*ects from disk, in bytes.", (Integer) (-6), integer0, integer0, true, "# The buffer siz; for faulting in ob*ects from disk, in bytes.");
      intConfigParam0.validate();
      assertEquals("# The buffer siz; for faulting in ob*ects from disk, in bytes.", intConfigParam0.getName());
  }
}
