/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.cleaner;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.cleaner.PackedOffsets;
import java.nio.ByteBuffer;

@RunWith(EvoSuiteRunner.class)
public class TestPackedOffsets_1 {


  //Test case number: 1
  /*
   * 87 covered goals:
   * 1 Weak Mutation 15: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:90 - DeleteField: priorValJ
   * 2 Weak Mutation 32: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - ReplaceComparisonOperator >= -> ==
   * 3 Weak Mutation 63: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - ReplaceArithmeticOperator + -> *
   * 4 Weak Mutation 60: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - ReplaceArithmeticOperator + -> -
   * 5 Weak Mutation 95: com.sleepycat.je.cleaner.PackedOffsets.pack([J)V:39 - ReplaceArithmeticOperator - -> +
   * 6 Weak Mutation 97: com.sleepycat.je.cleaner.PackedOffsets.pack([J)V:39 - ReplaceArithmeticOperator - -> *
   * 7 Weak Mutation 139: com.sleepycat.je.cleaner.PackedOffsets.append([SIJ)I:64 - ReplaceComparisonOperator >= -> ==
   * 8 Weak Mutation 157: com.sleepycat.je.cleaner.PackedOffsets.append([SIJ)I:67 - ReplaceBitwiseOperator >>> -> <<
   * 9 Weak Mutation 0: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - DeleteField: this$0Lcom/sleepycat/je/cleaner/PackedOffsets;
   * 10 Weak Mutation 1: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - DeleteStatement: access$100(Lcom/sleepycat/je/cleaner/PackedOffsets;)[S
   * 11 Weak Mutation 2: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - ReplaceComparisonOperator = null -> != null
   * 12 Weak Mutation 3: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - InsertUnaryOp Negation
   * 13 Weak Mutation 4: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - InsertUnaryOp +1
   * 14 Weak Mutation 5: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - InsertUnaryOp -1
   * 15 Weak Mutation 6: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - DeleteField: indexI
   * 16 Weak Mutation 7: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - DeleteField: this$0Lcom/sleepycat/je/cleaner/PackedOffsets;
   * 17 Weak Mutation 8: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - DeleteStatement: access$100(Lcom/sleepycat/je/cleaner/PackedOffsets;)[S
   * 18 Weak Mutation 10: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - ReplaceComparisonOperator >= -> >
   * 19 Weak Mutation 11: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - ReplaceComparisonOperator >= -> -1
   * 20 Weak Mutation 12: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - ReplaceConstant - 1 -> 0
   * 21 Weak Mutation 13: com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z:87 - ReplaceConstant - 0 -> 1
   * 22 Weak Mutation 14: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:90 - InsertUnaryOp Negation
   * 23 Weak Mutation 15: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:90 - DeleteField: priorValJ
   * 24 Weak Mutation 17: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - DeleteField: this$0Lcom/sleepycat/je/cleaner/PackedOffsets;
   * 25 Weak Mutation 16: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:91 - ReplaceConstant - 0 -> 1
   * 26 Weak Mutation 19: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - InsertUnaryOp Negation
   * 27 Weak Mutation 18: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - DeleteStatement: access$100(Lcom/sleepycat/je/cleaner/PackedOffsets;)[S
   * 28 Weak Mutation 21: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - InsertUnaryOp -1
   * 29 Weak Mutation 20: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - InsertUnaryOp +1
   * 30 Weak Mutation 23: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - ReplaceConstant - 1 -> 0
   * 31 Weak Mutation 22: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - DeleteField: indexI
   * 32 Weak Mutation 25: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - ReplaceArithmeticOperator + -> %
   * 33 Weak Mutation 24: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - ReplaceArithmeticOperator + -> -
   * 34 Weak Mutation 27: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - ReplaceArithmeticOperator + -> *
   * 35 Weak Mutation 26: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:92 - ReplaceArithmeticOperator + -> /
   * 36 Weak Mutation 29: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - ReplaceConstant - 0 -> 1
   * 37 Weak Mutation 28: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - InsertUnaryOp Negation
   * 38 Weak Mutation 31: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - DeleteStatement: longSub(JJ)I
   * 39 Weak Mutation 30: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - ReplaceConstant - 0 -> -1
   * 40 Weak Mutation 32: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - ReplaceComparisonOperator >= -> ==
   * 41 Weak Mutation 33: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:93 - ReplaceComparisonOperator >= -> >
   * 42 Weak Mutation 55: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - InsertUnaryOp Negation
   * 43 Weak Mutation 54: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - InsertUnaryOp Negation
   * 44 Weak Mutation 53: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - InsertUnaryOp Negation
   * 45 Weak Mutation 57: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - InsertUnaryOp IINC -1
   * 46 Weak Mutation 56: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - InsertUnaryOp IINC 1
   * 47 Weak Mutation 63: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - ReplaceArithmeticOperator + -> *
   * 48 Weak Mutation 62: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - ReplaceArithmeticOperator + -> /
   * 49 Weak Mutation 61: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - ReplaceArithmeticOperator + -> %
   * 50 Weak Mutation 60: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:97 - ReplaceArithmeticOperator + -> -
   * 51 Weak Mutation 64: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:101 - InsertUnaryOp Negation
   * 52 Weak Mutation 65: com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J:102 - InsertUnaryOp Negation
   * 53 Weak Mutation 95: com.sleepycat.je.cleaner.PackedOffsets.pack([J)V:39 - ReplaceArithmeticOperator - -> +
   * 54 Weak Mutation 97: com.sleepycat.je.cleaner.PackedOffsets.pack([J)V:39 - ReplaceArithmeticOperator - -> *
   * 55 Weak Mutation 110: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:50 - DeleteField: sizeI
   * 56 Weak Mutation 111: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:51 - ReplaceConstant - 0 -> 1
   * 57 Weak Mutation 108: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:50 - InsertUnaryOp +1
   * 58 Weak Mutation 109: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:50 - InsertUnaryOp -1
   * 59 Weak Mutation 107: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:50 - InsertUnaryOp Negation
   * 60 Weak Mutation 119: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp Negation
   * 61 Weak Mutation 118: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:54 - DeleteStatement: next()J
   * 62 Weak Mutation 117: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:54 - InsertUnaryOp IINC -1
   * 63 Weak Mutation 116: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:54 - InsertUnaryOp IINC 1
   * 64 Weak Mutation 115: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:54 - InsertUnaryOp Negation
   * 65 Weak Mutation 114: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:53 - ReplaceComparisonOperator == -> !=
   * 66 Weak Mutation 113: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:53 - DeleteStatement: hasNext()Z
   * 67 Weak Mutation 112: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:52 - DeleteStatement: iterator()Lcom/sleepycat/je/cleaner/PackedOffsets$Iterator;
   * 68 Weak Mutation 127: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp -1
   * 69 Weak Mutation 126: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp +1
   * 70 Weak Mutation 125: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp Negation
   * 71 Weak Mutation 124: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp IINC -1
   * 72 Weak Mutation 123: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp IINC 1
   * 73 Weak Mutation 122: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - InsertUnaryOp Negation
   * 74 Weak Mutation 121: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - ReplaceComparisonOperator != -> ==
   * 75 Weak Mutation 139: com.sleepycat.je.cleaner.PackedOffsets.append([SIJ)I:64 - ReplaceComparisonOperator >= -> ==
   * 76 Weak Mutation 128: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - DeleteField: sizeI
   * 77 Weak Mutation 130: com.sleepycat.je.cleaner.PackedOffsets.toArray()[J:56 - ReplaceComparisonOperator == -> -2
   * 78 Weak Mutation 157: com.sleepycat.je.cleaner.PackedOffsets.append([SIJ)I:67 - ReplaceBitwiseOperator >>> -> <<
   * 79 com.sleepycat.je.cleaner.PackedOffsets.iterator()Lcom/sleepycat/je/cleaner/PackedOffsets$Iterator;: root-Branch
   * 80 com.sleepycat.je.cleaner.PackedOffsets.toArray()[J: I19 Branch 5 IFEQ L53 - true
   * 81 com.sleepycat.je.cleaner.PackedOffsets.toArray()[J: I19 Branch 5 IFEQ L53 - false
   * 82 com.sleepycat.je.cleaner.PackedOffsets.toArray()[J: I32 Branch 6 IFNE L56 - false
   * 83 com.sleepycat.je.cleaner.PackedOffsets.toArray()[J: I36 Branch 7 IF_ICMPEQ L56 - true
   * 84 com.sleepycat.je.cleaner.PackedOffsets$Iterator.next()J: I29 Branch 3 IFGE L93 - true
   * 85 com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z: I5 Branch 1 IFNULL L87 - false
   * 86 com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z: I12 Branch 2 IF_ICMPGE L87 - true
   * 87 com.sleepycat.je.cleaner.PackedOffsets$Iterator.hasNext()Z: I12 Branch 2 IF_ICMPGE L87 - false
   */
  @Test
  public void test1()  throws Throwable  {
      PackedOffsets packedOffsets0 = new PackedOffsets();
      long[] longArray0 = new long[10];
      longArray0[8] = (long) 8;
      longArray0[9] = (long) 8;
      packedOffsets0.pack(longArray0);
      packedOffsets0.toArray();
      assertEquals(28, packedOffsets0.getLogSize());
      assertEquals("<offsets size=\"10\">0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x8 0x8 </offsets>", packedOffsets0.toString());
  }
}
