/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log.entry;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.log.FileHeader;
import com.sleepycat.je.log.LogReadable;
import com.sleepycat.je.log.entry.SingleItemLogEntry;
import com.sleepycat.je.tree.BIN;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;

@RunWith(EvoSuiteRunner.class)
public class TestSingleItemLogEntry_2 {


  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 Weak Mutation 12: com.sleepycat.je.log.entry.SingleItemLogEntry.getMainItem()Ljava/lang/Object;:40 - DeleteField: itemLcom/sleepycat/je/log/LogReadable;
   * 2 com.sleepycat.je.log.entry.SingleItemLogEntry.getMainItem()Ljava/lang/Object;: root-Branch
   * 3 Weak Mutation 12: com.sleepycat.je.log.entry.SingleItemLogEntry.getMainItem()Ljava/lang/Object;:40 - DeleteField: itemLcom/sleepycat/je/log/LogReadable;
   */
  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = Charset.class;
      SingleItemLogEntry singleItemLogEntry0 = new SingleItemLogEntry(class0);
      BIN bIN0 = new BIN();
      singleItemLogEntry0.item = (LogReadable) bIN0;
      BIN bIN1 = (BIN)singleItemLogEntry0.getMainItem();
      assertEquals(true, bIN1.isCompressible());
  }
}
