/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log.entry;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.dbi.DbConfigManager;
import com.sleepycat.je.log.entry.INLogEntry;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.ChildReference;
import com.sleepycat.je.tree.DIN;
import com.sleepycat.je.tree.IN;
import java.nio.ByteBuffer;
import java.util.Map;

@RunWith(EvoSuiteRunner.class)
public class TestINLogEntry_11 {


  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 Weak Mutation 94: com.sleepycat.je.log.entry.INLogEntry.writeToLog(Ljava/nio/ByteBuffer;)V:156 - DeleteStatement: writeToLog(Ljava/nio/ByteBuffer;)V
   * 2 com.sleepycat.je.log.entry.INLogEntry.writeToLog(Ljava/nio/ByteBuffer;)V: root-Branch
   * 3 Weak Mutation 94: com.sleepycat.je.log.entry.INLogEntry.writeToLog(Ljava/nio/ByteBuffer;)V:156 - DeleteStatement: writeToLog(Ljava/nio/ByteBuffer;)V
   */
  @Test
  public void test11()  throws Throwable  {
      Class<?> class0 = DbConfigManager.class;
      INLogEntry iNLogEntry0 = new INLogEntry(class0);
      // Undeclared exception!
      try {
        iNLogEntry0.writeToLog((ByteBuffer) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
