/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.log.LogUtils;
import java.nio.ByteBuffer;
import java.sql.Timestamp;
import javax.transaction.xa.Xid;

@RunWith(EvoSuiteRunner.class)
public class TestLogUtils_23 {


  //Test case number: 23
  /*
   * 100 covered goals:
   * 1 Weak Mutation 49: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> -
   * 2 Weak Mutation 52: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> *
   * 3 Weak Mutation 70: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> -
   * 4 Weak Mutation 73: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> *
   * 5 Weak Mutation 29: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - InsertUnaryOp +1
   * 6 Weak Mutation 28: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - InsertUnaryOp Negation
   * 7 Weak Mutation 31: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - DeleteField: formatIdI
   * 8 Weak Mutation 30: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - InsertUnaryOp -1
   * 9 Weak Mutation 34: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - ReplaceConstant - 0 -> 1
   * 10 Weak Mutation 35: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - InsertUnaryOp Negation
   * 11 Weak Mutation 32: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:321 - DeleteField: gid[B
   * 12 Weak Mutation 33: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:321 - ReplaceComparisonOperator = null -> != null
   * 13 Weak Mutation 38: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - DeleteField: gid[B
   * 14 Weak Mutation 36: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - InsertUnaryOp IINC 1
   * 15 Weak Mutation 37: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - InsertUnaryOp IINC -1
   * 16 Weak Mutation 42: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp Negation
   * 17 Weak Mutation 43: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC 1
   * 18 Weak Mutation 40: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - ReplaceComparisonOperator >= -> >
   * 19 Weak Mutation 41: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - ReplaceComparisonOperator >= -> -1
   * 20 Weak Mutation 46: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp Negation
   * 21 Weak Mutation 47: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC 1
   * 22 Weak Mutation 44: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC -1
   * 23 Weak Mutation 45: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - DeleteField: gid[B
   * 24 Weak Mutation 51: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> /
   * 25 Weak Mutation 50: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> %
   * 26 Weak Mutation 48: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC -1
   * 27 Weak Mutation 55: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - ReplaceConstant - 0 -> 1
   * 28 Weak Mutation 54: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:326 - ReplaceComparisonOperator = null -> != null
   * 29 Weak Mutation 53: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:326 - DeleteField: bqual[B
   * 30 Weak Mutation 59: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - DeleteField: bqual[B
   * 31 Weak Mutation 58: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - InsertUnaryOp IINC -1
   * 32 Weak Mutation 57: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - InsertUnaryOp IINC 1
   * 33 Weak Mutation 56: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - InsertUnaryOp Negation
   * 34 Weak Mutation 63: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp Negation
   * 35 Weak Mutation 62: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - ReplaceComparisonOperator >= -> -1
   * 36 Weak Mutation 61: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - ReplaceComparisonOperator >= -> >
   * 37 Weak Mutation 68: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC 1
   * 38 Weak Mutation 69: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC -1
   * 39 Weak Mutation 71: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> %
   * 40 Weak Mutation 64: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC 1
   * 41 Weak Mutation 65: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC -1
   * 42 Weak Mutation 66: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - DeleteField: bqual[B
   * 43 Weak Mutation 67: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp Negation
   * 44 Weak Mutation 76: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:331 - InsertUnaryOp IINC -1
   * 45 Weak Mutation 72: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> /
   * 46 Weak Mutation 74: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:331 - InsertUnaryOp Negation
   * 47 Weak Mutation 75: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:331 - InsertUnaryOp IINC 1
   * 48 Weak Mutation 29: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - InsertUnaryOp +1
   * 49 Weak Mutation 28: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - InsertUnaryOp Negation
   * 50 Weak Mutation 31: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - DeleteField: formatIdI
   * 51 Weak Mutation 30: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:320 - InsertUnaryOp -1
   * 52 Weak Mutation 34: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - ReplaceConstant - 0 -> 1
   * 53 Weak Mutation 35: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - InsertUnaryOp Negation
   * 54 Weak Mutation 32: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:321 - DeleteField: gid[B
   * 55 Weak Mutation 33: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:321 - ReplaceComparisonOperator = null -> != null
   * 56 Weak Mutation 38: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - DeleteField: gid[B
   * 57 Weak Mutation 36: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - InsertUnaryOp IINC 1
   * 58 Weak Mutation 37: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - InsertUnaryOp IINC -1
   * 59 Weak Mutation 42: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp Negation
   * 60 Weak Mutation 43: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC 1
   * 61 Weak Mutation 40: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - ReplaceComparisonOperator >= -> >
   * 62 Weak Mutation 41: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:322 - ReplaceComparisonOperator >= -> -1
   * 63 Weak Mutation 46: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp Negation
   * 64 Weak Mutation 47: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC 1
   * 65 Weak Mutation 44: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC -1
   * 66 Weak Mutation 45: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - DeleteField: gid[B
   * 67 Weak Mutation 51: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> /
   * 68 Weak Mutation 50: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> %
   * 69 Weak Mutation 49: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> -
   * 70 Weak Mutation 48: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - InsertUnaryOp IINC -1
   * 71 Weak Mutation 55: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - ReplaceConstant - 0 -> 1
   * 72 Weak Mutation 54: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:326 - ReplaceComparisonOperator = null -> != null
   * 73 Weak Mutation 53: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:326 - DeleteField: bqual[B
   * 74 Weak Mutation 52: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:323 - ReplaceArithmeticOperator + -> *
   * 75 Weak Mutation 59: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - DeleteField: bqual[B
   * 76 Weak Mutation 58: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - InsertUnaryOp IINC -1
   * 77 Weak Mutation 57: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - InsertUnaryOp IINC 1
   * 78 Weak Mutation 56: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - InsertUnaryOp Negation
   * 79 Weak Mutation 63: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp Negation
   * 80 Weak Mutation 62: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - ReplaceComparisonOperator >= -> -1
   * 81 Weak Mutation 61: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:327 - ReplaceComparisonOperator >= -> >
   * 82 Weak Mutation 68: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC 1
   * 83 Weak Mutation 69: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC -1
   * 84 Weak Mutation 70: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> -
   * 85 Weak Mutation 71: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> %
   * 86 Weak Mutation 64: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC 1
   * 87 Weak Mutation 65: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp IINC -1
   * 88 Weak Mutation 66: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - DeleteField: bqual[B
   * 89 Weak Mutation 67: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - InsertUnaryOp Negation
   * 90 Weak Mutation 76: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:331 - InsertUnaryOp IINC -1
   * 91 Weak Mutation 72: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> /
   * 92 Weak Mutation 73: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:328 - ReplaceArithmeticOperator + -> *
   * 93 Weak Mutation 74: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:331 - InsertUnaryOp Negation
   * 94 Weak Mutation 75: com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I:331 - InsertUnaryOp IINC 1
   * 95 com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I: I9 Branch 5 IFNULL L321 - false
   * 96 com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I: I19 Branch 6 IF_ICMPGE L322 - true
   * 97 com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I: I19 Branch 6 IF_ICMPGE L322 - false
   * 98 com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I: I37 Branch 7 IFNULL L326 - false
   * 99 com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I: I47 Branch 8 IF_ICMPGE L327 - true
   * 100 com.sleepycat.je.log.LogUtils$XidImpl.hashCode()I: I47 Branch 8 IF_ICMPGE L327 - false
   */
  @Test
  public void test23()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      LogUtils.XidImpl logUtils_XidImpl0 = new LogUtils.XidImpl(8, byteArray0, byteArray0);
      byteArray0[0] = (byte)92;
      int int0 = logUtils_XidImpl0.hashCode();
      assertEquals("<Xid formatId=\"8\" gTxnId=\"\\\u0000\u0000\u0000\u0000\u0000\u0000\" bqual=\"\\\u0000\u0000\u0000\u0000\u0000\u0000\"/>", logUtils_XidImpl0.toString());
      assertEquals(192, int0);
  }
}
