/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.tree.BIN;

@RunWith(EvoSuiteRunner.class)
public class TestLogEntryType_8 {


  //Test case number: 8
  /*
   * 3 covered goals:
   * 1 Weak Mutation 50: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceComparisonOperator <= -> <
   * 2 com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;: I3 Branch 3 IFLE L95 - true
   * 3 Weak Mutation 50: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceComparisonOperator <= -> <
   */
  @Test
  public void test8()  throws Throwable  {
      LogEntryType logEntryType0 = LogEntryType.findType((byte)0, (byte)0);
      assertNull(logEntryType0);
  }
}
