/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.log.FileHeader;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.log.LogException;

@RunWith(EvoSuiteRunner.class)
public class TestFileHeader_9 {


  //Test case number: 9
  /*
   * 60 covered goals:
   * 1 Weak Mutation 51: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> -1
   * 2 Weak Mutation 50: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 1
   * 3 Weak Mutation 49: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 0
   * 4 Weak Mutation 48: com.sleepycat.je.log.FileHeader.entrySize()I:71 - DeleteStatement: getTimestampLogSize()I
   * 5 Weak Mutation 55: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> %
   * 6 Weak Mutation 54: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> -
   * 7 Weak Mutation 53: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 5
   * 8 Weak Mutation 52: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 3
   * 9 Weak Mutation 59: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 1
   * 10 Weak Mutation 58: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 0
   * 11 Weak Mutation 57: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> *
   * 12 Weak Mutation 56: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> /
   * 13 Weak Mutation 63: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> -
   * 14 Weak Mutation 62: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 9
   * 15 Weak Mutation 61: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 7
   * 16 Weak Mutation 60: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> -1
   * 17 Weak Mutation 68: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 1
   * 18 Weak Mutation 69: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> -1
   * 19 Weak Mutation 70: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 3
   * 20 Weak Mutation 71: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 5
   * 21 Weak Mutation 64: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> %
   * 22 Weak Mutation 65: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> /
   * 23 Weak Mutation 66: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> *
   * 24 Weak Mutation 67: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 0
   * 25 Weak Mutation 72: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> -
   * 26 Weak Mutation 73: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> %
   * 27 Weak Mutation 74: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> /
   * 28 Weak Mutation 75: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> *
   * 29 Weak Mutation 76: com.sleepycat.je.log.FileHeader.getLogSize()I:78 - DeleteStatement: entrySize()I
   * 30 com.sleepycat.je.log.FileHeader.entrySize()I: root-Branch
   * 31 com.sleepycat.je.log.FileHeader.getLogSize()I: root-Branch
   * 32 Weak Mutation 51: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> -1
   * 33 Weak Mutation 50: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 1
   * 34 Weak Mutation 49: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 0
   * 35 Weak Mutation 48: com.sleepycat.je.log.FileHeader.entrySize()I:71 - DeleteStatement: getTimestampLogSize()I
   * 36 Weak Mutation 55: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> %
   * 37 Weak Mutation 54: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> -
   * 38 Weak Mutation 53: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 5
   * 39 Weak Mutation 52: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 3
   * 40 Weak Mutation 59: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 1
   * 41 Weak Mutation 58: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 0
   * 42 Weak Mutation 57: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> *
   * 43 Weak Mutation 56: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> /
   * 44 Weak Mutation 63: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> -
   * 45 Weak Mutation 62: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 9
   * 46 Weak Mutation 61: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> 7
   * 47 Weak Mutation 60: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 8 -> -1
   * 48 Weak Mutation 68: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 1
   * 49 Weak Mutation 69: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> -1
   * 50 Weak Mutation 70: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 3
   * 51 Weak Mutation 71: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 5
   * 52 Weak Mutation 64: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> %
   * 53 Weak Mutation 65: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> /
   * 54 Weak Mutation 66: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> *
   * 55 Weak Mutation 67: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceConstant - 4 -> 0
   * 56 Weak Mutation 76: com.sleepycat.je.log.FileHeader.getLogSize()I:78 - DeleteStatement: entrySize()I
   * 57 Weak Mutation 72: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> -
   * 58 Weak Mutation 73: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> %
   * 59 Weak Mutation 74: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> /
   * 60 Weak Mutation 75: com.sleepycat.je.log.FileHeader.entrySize()I:71 - ReplaceArithmeticOperator + -> *
   */
  @Test
  public void test9()  throws Throwable  {
      FileHeader fileHeader0 = new FileHeader();
      int int0 = fileHeader0.getLogSize();
      assertEquals(24, int0);
  }
}
