/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.log.LogEntryType;
import com.sleepycat.je.tree.BIN;

@RunWith(EvoSuiteRunner.class)
public class TestLogEntryType_7 {


  //Test case number: 7
  /*
   * 46 covered goals:
   * 1 Weak Mutation 46: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp Negation
   * 2 Weak Mutation 47: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC 1
   * 3 Weak Mutation 51: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceComparisonOperator <= -> -1
   * 4 Weak Mutation 48: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC -1
   * 5 Weak Mutation 55: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 0
   * 6 Weak Mutation 54: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC -1
   * 7 Weak Mutation 53: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC 1
   * 8 Weak Mutation 52: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp Negation
   * 9 Weak Mutation 59: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 28
   * 10 Weak Mutation 58: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 26
   * 11 Weak Mutation 57: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> -1
   * 12 Weak Mutation 56: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 1
   * 13 Weak Mutation 61: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceComparisonOperator <= -> <
   * 14 Weak Mutation 63: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - DeleteField: LOG_TYPES[Lcom/sleepycat/je/log/LogEntryType;
   * 15 Weak Mutation 68: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> +
   * 16 Weak Mutation 69: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> %
   * 17 Weak Mutation 70: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> /
   * 18 Weak Mutation 71: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> *
   * 19 Weak Mutation 64: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - InsertUnaryOp Negation
   * 20 Weak Mutation 65: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - InsertUnaryOp IINC 1
   * 21 Weak Mutation 66: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - InsertUnaryOp IINC -1
   * 22 Weak Mutation 67: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceConstant - 1 -> 0
   * 23 com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;: I3 Branch 3 IFLE L95 - false
   * 24 com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;: I6 Branch 4 IF_ICMPLE L95 - true
   * 25 Weak Mutation 46: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp Negation
   * 26 Weak Mutation 47: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC 1
   * 27 Weak Mutation 51: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceComparisonOperator <= -> -1
   * 28 Weak Mutation 48: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC -1
   * 29 Weak Mutation 55: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 0
   * 30 Weak Mutation 54: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC -1
   * 31 Weak Mutation 53: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp IINC 1
   * 32 Weak Mutation 52: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - InsertUnaryOp Negation
   * 33 Weak Mutation 59: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 28
   * 34 Weak Mutation 58: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 26
   * 35 Weak Mutation 57: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> -1
   * 36 Weak Mutation 56: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceConstant - 27 -> 1
   * 37 Weak Mutation 63: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - DeleteField: LOG_TYPES[Lcom/sleepycat/je/log/LogEntryType;
   * 38 Weak Mutation 61: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:95 - ReplaceComparisonOperator <= -> <
   * 39 Weak Mutation 68: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> +
   * 40 Weak Mutation 69: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> %
   * 41 Weak Mutation 70: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> /
   * 42 Weak Mutation 71: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceArithmeticOperator - -> *
   * 43 Weak Mutation 64: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - InsertUnaryOp Negation
   * 44 Weak Mutation 65: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - InsertUnaryOp IINC 1
   * 45 Weak Mutation 66: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - InsertUnaryOp IINC -1
   * 46 Weak Mutation 67: com.sleepycat.je.log.LogEntryType.findType(BB)Lcom/sleepycat/je/log/LogEntryType;:98 - ReplaceConstant - 1 -> 0
   */
  @Test
  public void test7()  throws Throwable  {
      LogEntryType logEntryType0 = LogEntryType.findType((byte)27, (byte)15);
      assertNotNull(logEntryType0);
      assertEquals(27, logEntryType0.getTypeNum());
  }
}
