/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.log.FileHandle;
import java.io.IOException;
import java.io.RandomAccessFile;

@RunWith(EvoSuiteRunner.class)
public class TestFileHandle {


  //Test case number: 0
  /*
   * 9 covered goals:
   * 1 Weak Mutation 4: com.sleepycat.je.log.FileHandle.isOldHeaderVersion()Z:32 - InsertUnaryOp Negation
   * 2 Weak Mutation 5: com.sleepycat.je.log.FileHandle.isOldHeaderVersion()Z:32 - DeleteField: oldHeaderVersionZ
   * 3 com.sleepycat.je.log.FileHandle.isOldHeaderVersion()Z: root-Branch
   * 4 Weak Mutation 0: com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V:23 - InsertUnaryOp Negation of oldHeaderVersion
   * 5 Weak Mutation 1: com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V:23 - InsertUnaryOp IINC 1 oldHeaderVersion
   * 6 Weak Mutation 2: com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V:23 - InsertUnaryOp IINC -1 oldHeaderVersion
   * 7 Weak Mutation 4: com.sleepycat.je.log.FileHandle.isOldHeaderVersion()Z:32 - InsertUnaryOp Negation
   * 8 Weak Mutation 5: com.sleepycat.je.log.FileHandle.isOldHeaderVersion()Z:32 - DeleteField: oldHeaderVersionZ
   * 9 com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "+*OOUi`H=2dq:", (EnvironmentImpl) null, true);
      boolean boolean0 = fileHandle0.isOldHeaderVersion();
      assertEquals(true, boolean0);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 Weak Mutation 7: com.sleepycat.je.log.FileHandle.close()V:50 - ReplaceComparisonOperator = null -> != null
   * 2 com.sleepycat.je.log.FileHandle.close()V: I4 Branch 1 IFNULL L50 - true
   * 3 Weak Mutation 7: com.sleepycat.je.log.FileHandle.close()V:50 - ReplaceComparisonOperator = null -> != null
   */
  @Test
  public void test1()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "+*OOUi`H=2dq:", (EnvironmentImpl) null, true);
      fileHandle0.close();
      assertEquals(true, fileHandle0.isOldHeaderVersion());
  }

  //Test case number: 2
  /*
   * 4 covered goals:
   * 1 com.sleepycat.je.log.FileHandle.getFile()Ljava/io/RandomAccessFile;: root-Branch
   * 2 Weak Mutation 0: com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V:23 - InsertUnaryOp Negation of oldHeaderVersion
   * 3 Weak Mutation 1: com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V:23 - InsertUnaryOp IINC 1 oldHeaderVersion
   * 4 Weak Mutation 2: com.sleepycat.je.log.FileHandle.<init>(Ljava/io/RandomAccessFile;Ljava/lang/String;Lcom/sleepycat/je/dbi/EnvironmentImpl;Z)V:23 - InsertUnaryOp IINC -1 oldHeaderVersion
   */
  @Test
  public void test2()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "+*OOUi`H=2dq:", (EnvironmentImpl) null, true);
      fileHandle0.getFile();
      assertEquals(true, fileHandle0.isOldHeaderVersion());
  }
}
