/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.log;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.log.CheckpointMonitor;

@RunWith(EvoSuiteRunner.class)
public class TestCheckpointMonitor {


  //Test case number: 0
  /*
   * 5 covered goals:
   * 1 Weak Mutation 0: com.sleepycat.je.log.CheckpointMonitor.<init>(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V:20 - ReplaceConstant - 0 -> 1
   * 2 Weak Mutation 1: com.sleepycat.je.log.CheckpointMonitor.<init>(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V:22 - DeleteStatement: getConfigManager()Lcom/sleepycat/je/dbi/DbConfigManager;
   * 3 com.sleepycat.je.log.CheckpointMonitor.<init>(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V: root-Branch
   * 4 Weak Mutation 0: com.sleepycat.je.log.CheckpointMonitor.<init>(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V:20 - ReplaceConstant - 0 -> 1
   * 5 Weak Mutation 1: com.sleepycat.je.log.CheckpointMonitor.<init>(Lcom/sleepycat/je/dbi/EnvironmentImpl;)V:22 - DeleteStatement: getConfigManager()Lcom/sleepycat/je/dbi/DbConfigManager;
   */
  @Test
  public void test0()  throws Throwable  {
      CheckpointMonitor checkpointMonitor0 = null;
      try {
        checkpointMonitor0 = new CheckpointMonitor((EnvironmentImpl) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
