#!/bin/bash

source ../../common
CURDIR=`pwd`
TIMESTAMP=`date +"%Y-%m-%d-%Hh%Mm"`
BINDIR=$CURDIR/bin
## remove old stuff (will be re-generated)
rm -rf $BINDIR
mkdir -p $BINDIR

a=0
NUM_VALID_CONFIGURATIONS_FOR_TG=1
#########################
## generate tests for
## NUM_VALID_CONFIGURATIONS_FOR_TG
## distinct products.
#########################
(
while read line 
do
    if [ $a -eq $NUM_VALID_CONFIGURATIONS_FOR_TG ]
    then
	break
    fi
    a=$(($a+1));
    FEATURES=`echo $line`
    ../../build "$FEATURES" $CURDIR
    if [ "$?" -ne 0 ]
    then
	echo "compile error"
    else
	NUM=`find $BINDIR -name "*.class" | wc -l`
	echo "$NUM classes generated"
	############################
	EVOSUITE_TESTS_DIRS=$CURDIR/evosuite-tests
	EVOSUITE_REPORTS_DIRS=$CURDIR/evosuite-report
	rm -rf ${EVOSUITE_TESTS_DIRS}
	rm -rf ${EVOSUITE_REPORTS_DIRS}
	../../evosuite "$BINDIR"
	EVO_OUTPUT="$CURDIR/evo-run-$a"
	rm -rf ${EVO_OUTPUT}  ## cleans if it exists
	mkdir -p ${EVO_OUTPUT}
	mv evosuite-tests ${EVO_OUTPUT}
	mv evosuite-report ${EVO_OUTPUT}
	############################
    fi
done < "all-configurations-shuffled.txt"

#########################
## generate tests
#########################
while read line 
do
    FEATURES=`echo $line`
    ################################
    ##../../build "$FEATURES" $CURDIR
    ################################
done < "random-configurations.txt"

) 2>&1 | tee log-${TIMESTAMP}.txt