/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.TokenizerException;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.impl.SequenceStore;
import de.susebox.jtopas.spi.DataProvider;
import java.util.Iterator;
import java.util.NoSuchElementException;

@RunWith(EvoSuiteRunner.class)
public class TestSequenceStore_16 {


  //Test case number: 16
  /*
   * 64 covered goals:
   * 1 Weak Mutation 34: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:593 - ReplaceConstant - 1 -> 0
   * 2 de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z: I4 Branch 4 IFEQ L592 - false
   * 3 Weak Mutation 10: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:575 - DeleteField: _currentListLde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 4 Weak Mutation 11: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:575 - ReplaceComparisonOperator = null -> != null
   * 5 Weak Mutation 12: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - InsertUnaryOp Negation
   * 6 Weak Mutation 13: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - InsertUnaryOp +1
   * 7 Weak Mutation 14: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - InsertUnaryOp -1
   * 8 Weak Mutation 15: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - DeleteField: _typeI
   * 9 Weak Mutation 16: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - ReplaceComparisonOperator == -> >=
   * 10 Weak Mutation 19: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - DeleteField: _currentListLde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 11 Weak Mutation 21: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - DeleteStatement: getType()I
   * 12 Weak Mutation 20: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - DeleteField: _propertyLde/susebox/jtopas/TokenizerProperty;
   * 13 Weak Mutation 23: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - InsertUnaryOp +1
   * 14 Weak Mutation 22: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - InsertUnaryOp Negation
   * 15 Weak Mutation 25: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - DeleteField: _typeI
   * 16 Weak Mutation 24: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - InsertUnaryOp -1
   * 17 Weak Mutation 29: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:577 - ReplaceConstant - 1 -> 0
   * 18 Weak Mutation 28: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:576 - ReplaceComparisonOperator != -> -1
   * 19 Weak Mutation 32: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.listHasNext()Z:581 - ReplaceConstant - 0 -> 1
   * 20 Weak Mutation 33: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:592 - ReplaceComparisonOperator == -> !=
   * 21 Weak Mutation 36: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:597 - ReplaceComparisonOperator = null -> != null
   * 22 Weak Mutation 46: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:607 - ReplaceComparisonOperator = null -> != null
   * 23 Weak Mutation 47: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - InsertUnaryOp Negation
   * 24 Weak Mutation 44: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:607 - DeleteField: _parentLde/susebox/jtopas/impl/SequenceStore;
   * 25 Weak Mutation 45: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:607 - DeleteStatement: access$000(Lde/susebox/jtopas/impl/SequenceStore;)[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 26 Weak Mutation 51: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - ReplaceConstant - 1 -> 0
   * 27 Weak Mutation 50: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - DeleteField: _currentIndexI
   * 28 Weak Mutation 49: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - InsertUnaryOp -1
   * 29 Weak Mutation 48: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - InsertUnaryOp +1
   * 30 Weak Mutation 55: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - ReplaceArithmeticOperator + -> *
   * 31 Weak Mutation 54: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - ReplaceArithmeticOperator + -> /
   * 32 Weak Mutation 53: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - ReplaceArithmeticOperator + -> %
   * 33 Weak Mutation 52: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - ReplaceArithmeticOperator + -> -
   * 34 Weak Mutation 59: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - ReplaceComparisonOperator >= -> -1
   * 35 Weak Mutation 56: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:608 - DeleteField: DIRECT_INDEX_COUNTC
   * 36 Weak Mutation 63: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - InsertUnaryOp +1
   * 37 Weak Mutation 62: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - InsertUnaryOp Negation
   * 38 Weak Mutation 61: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - DeleteStatement: access$000(Lde/susebox/jtopas/impl/SequenceStore;)[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 39 Weak Mutation 60: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - DeleteField: _parentLde/susebox/jtopas/impl/SequenceStore;
   * 40 Weak Mutation 68: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:611 - ReplaceConstant - 1 -> 0
   * 41 Weak Mutation 64: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - InsertUnaryOp -1
   * 42 Weak Mutation 65: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - DeleteField: _currentIndexI
   * 43 Weak Mutation 66: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:609 - ReplaceComparisonOperator = null -> != null
   * 44 Weak Mutation 67: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:610 - ReplaceComparisonOperator == -> !=
   * 45 Weak Mutation 76: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.next()Ljava/lang/Object;:638 - DeleteField: _currentListLde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 46 Weak Mutation 77: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.next()Ljava/lang/Object;:639 - DeleteField: _currentListLde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 47 Weak Mutation 79: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.next()Ljava/lang/Object;:640 - DeleteField: _currentElemLde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 48 Weak Mutation 74: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.next()Ljava/lang/Object;:634 - DeleteStatement: hasNext()Z
   * 49 Weak Mutation 75: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.next()Ljava/lang/Object;:634 - ReplaceComparisonOperator != -> ==
   * 50 Weak Mutation 80: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.next()Ljava/lang/Object;:640 - DeleteField: _propertyLde/susebox/jtopas/TokenizerProperty;
   * 51 Weak Mutation 186: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - ReplaceComparisonOperator >= -> -1
   * 52 Weak Mutation 187: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp Negation
   * 53 Weak Mutation 188: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp IINC 1
   * 54 Weak Mutation 189: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp IINC -1
   * 55 Weak Mutation 254: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - DeleteField: _asciiArray[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 56 Weak Mutation 255: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp Negation
   * 57 Weak Mutation 258: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - ReplaceComparisonOperator != null -> = null
   * 58 Weak Mutation 259: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - DeleteField: _asciiArray[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 59 Weak Mutation 256: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp IINC 1
   * 60 Weak Mutation 257: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp IINC -1
   * 61 Weak Mutation 262: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp IINC -1
   * 62 Weak Mutation 260: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp Negation
   * 63 Weak Mutation 261: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp IINC 1
   * 64 Weak Mutation 34: de.susebox.jtopas.impl.SequenceStore$SpecialSequencesIterator.hasNext()Z:593 - ReplaceConstant - 1 -> 0
   */
  @Test
  public void test16()  throws Throwable  {
      SequenceStore sequenceStore0 = new SequenceStore(true);
      String[] stringArray0 = new String[7];
      stringArray0[0] = "/9 4E7^LKlXGS3";
      Object object0 = new Object();
      TokenizerProperty tokenizerProperty0 = new TokenizerProperty(841, stringArray0, object0, 0, (-644));
      sequenceStore0.addSpecialSequence(tokenizerProperty0);
      SequenceStore.SpecialSequencesIterator sequenceStore_SpecialSequencesIterator0 = sequenceStore0.new SpecialSequencesIterator(sequenceStore0, 841);
      sequenceStore_SpecialSequencesIterator0.hasNext();
      sequenceStore_SpecialSequencesIterator0.next();
      assertEquals(15, sequenceStore0.getSequenceMaxLength());
      assertEquals(true, sequenceStore0.hasKeywords());
  }
}
