/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.impl.NoCaseSequenceStore;

@RunWith(EvoSuiteRunner.class)
public class TestNoCaseSequenceStore_0 {


  //Test case number: 0
  /*
   * 10 covered goals:
   * 1 Weak Mutation 0: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - InsertUnaryOp Negation
   * 2 Weak Mutation 1: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - InsertUnaryOp IINC 1
   * 3 Weak Mutation 2: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - InsertUnaryOp IINC -1
   * 4 Weak Mutation 3: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - DeleteStatement: toUpperCase(C)C
   * 5 de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C: root-Branch
   * 6 de.susebox.jtopas.impl.NoCaseSequenceStore.<init>(Z)V: root-Branch
   * 7 Weak Mutation 0: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - InsertUnaryOp Negation
   * 8 Weak Mutation 1: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - InsertUnaryOp IINC 1
   * 9 Weak Mutation 2: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - InsertUnaryOp IINC -1
   * 10 Weak Mutation 3: de.susebox.jtopas.impl.NoCaseSequenceStore.getStartChar(C)C:76 - DeleteStatement: toUpperCase(C)C
   */
  @Test
  public void test0()  throws Throwable  {
      NoCaseSequenceStore noCaseSequenceStore0 = new NoCaseSequenceStore(false);
      TokenizerProperty tokenizerProperty0 = noCaseSequenceStore0.getSpecialSequence("SVnLl@B^-");
      assertNull(tokenizerProperty0);
  }
}
