/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.TokenizerException;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.impl.SequenceStore;
import de.susebox.jtopas.spi.DataProvider;
import java.util.Iterator;

@RunWith(EvoSuiteRunner.class)
public class TestSequenceStore_9 {


  //Test case number: 9
  /*
   * 14 covered goals:
   * 1 Weak Mutation 226: de.susebox.jtopas.impl.SequenceStore.searchString(Ljava/lang/String;Z)Lde/susebox/jtopas/TokenizerProperty;:344 - ReplaceComparisonOperator != -> <
   * 2 Weak Mutation 339: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:462 - ReplaceComparisonOperator == -> >=
   * 3 Weak Mutation 343: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:463 - InsertUnaryOp IINC 1
   * 4 Weak Mutation 342: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:463 - InsertUnaryOp Negation
   * 5 Weak Mutation 344: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:463 - InsertUnaryOp IINC -1
   * 6 Weak Mutation 379: de.susebox.jtopas.impl.SequenceStore.compare(CC)I:503 - ReplaceArithmeticOperator - -> %
   * 7 de.susebox.jtopas.impl.SequenceStore.searchString(Ljava/lang/String;Z)Lde/susebox/jtopas/TokenizerProperty;: I114 Branch 32 IFGE L360 - true
   * 8 de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I: I40 Branch 40 IFEQ L462 - false
   * 9 Weak Mutation 226: de.susebox.jtopas.impl.SequenceStore.searchString(Ljava/lang/String;Z)Lde/susebox/jtopas/TokenizerProperty;:344 - ReplaceComparisonOperator != -> <
   * 10 Weak Mutation 343: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:463 - InsertUnaryOp IINC 1
   * 11 Weak Mutation 342: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:463 - InsertUnaryOp Negation
   * 12 Weak Mutation 339: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:462 - ReplaceComparisonOperator == -> >=
   * 13 Weak Mutation 344: de.susebox.jtopas.impl.SequenceStore.compare(Ljava/lang/String;Ljava/lang/String;I)I:463 - InsertUnaryOp IINC -1
   * 14 Weak Mutation 379: de.susebox.jtopas.impl.SequenceStore.compare(CC)I:503 - ReplaceArithmeticOperator - -> %
   */
  @Test
  public void test9()  throws Throwable  {
      SequenceStore sequenceStore0 = new SequenceStore(false);
      String[] stringArray0 = new String[7];
      stringArray0[0] = "/9 4E7^LKlXGS3";
      TokenizerProperty tokenizerProperty0 = new TokenizerProperty((int) 'S', stringArray0);
      sequenceStore0.addKeyword(tokenizerProperty0);
      stringArray0[0] = "F9CoYa-\"f&(wF'i";
      sequenceStore0.removeKeyword("/9 4E7^LKlXGS3");
      assertEquals(15, sequenceStore0.getSequenceMaxLength());
  }
}
