/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.TokenizerProperty;
import de.susebox.jtopas.impl.SequenceStore;

@RunWith(EvoSuiteRunner.class)
public class TestSequenceStore_1 {


  //Test case number: 1
  /*
   * 100 covered goals:
   * 1 Weak Mutation 102: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - ReplaceConstant - 1 -> 0
   * 2 Weak Mutation 101: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - ReplaceComparisonOperator <= -> -1
   * 3 Weak Mutation 98: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - DeleteField: _maxLengthI
   * 4 Weak Mutation 150: de.susebox.jtopas.impl.SequenceStore.hasKeywords()Z:175 - DeleteStatement: hasSequenceCommentOrString()Z
   * 5 Weak Mutation 152: de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C:206 - InsertUnaryOp Negation
   * 6 Weak Mutation 153: de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C:206 - InsertUnaryOp IINC 1
   * 7 Weak Mutation 154: de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C:206 - InsertUnaryOp IINC -1
   * 8 Weak Mutation 155: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:216 - DeleteStatement: getImages()[Ljava/lang/String;
   * 9 Weak Mutation 156: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:216 - ReplaceConstant - 0 -> 1
   * 10 Weak Mutation 157: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:217 - DeleteStatement: length()I
   * 11 Weak Mutation 158: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:218 - ReplaceConstant - 0 -> 1
   * 12 Weak Mutation 159: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:218 - DeleteStatement: charAt(I)C
   * 13 Weak Mutation 160: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:218 - DeleteStatement: getStartChar(C)C
   * 14 Weak Mutation 170: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - ReplaceComparisonOperator >= -> -1
   * 15 Weak Mutation 163: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp -1
   * 16 Weak Mutation 162: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp +1
   * 17 Weak Mutation 161: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp Negation
   * 18 Weak Mutation 167: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp IINC -1
   * 19 Weak Mutation 166: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp IINC 1
   * 20 Weak Mutation 165: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp Negation
   * 21 Weak Mutation 171: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:221 - InsertUnaryOp Negation
   * 22 Weak Mutation 173: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:221 - InsertUnaryOp IINC -1
   * 23 Weak Mutation 172: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:221 - InsertUnaryOp IINC 1
   * 24 Weak Mutation 175: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC 1
   * 25 Weak Mutation 174: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp Negation
   * 26 Weak Mutation 186: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - ReplaceComparisonOperator >= -> -1
   * 27 Weak Mutation 176: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC -1
   * 28 Weak Mutation 177: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - ReplaceComparisonOperator < -> !=
   * 29 Weak Mutation 182: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC -1
   * 30 Weak Mutation 183: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - DeleteField: DIRECT_INDEX_COUNTC
   * 31 Weak Mutation 180: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp Negation
   * 32 Weak Mutation 181: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC 1
   * 33 Weak Mutation 187: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp Negation
   * 34 Weak Mutation 188: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp IINC 1
   * 35 Weak Mutation 189: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp IINC -1
   * 36 Weak Mutation 254: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - DeleteField: _asciiArray[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 37 Weak Mutation 255: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp Negation
   * 38 Weak Mutation 258: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - ReplaceComparisonOperator != null -> = null
   * 39 Weak Mutation 256: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp IINC 1
   * 40 Weak Mutation 257: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp IINC -1
   * 41 Weak Mutation 259: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - DeleteField: _asciiArray[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 42 Weak Mutation 262: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp IINC -1
   * 43 Weak Mutation 260: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp Negation
   * 44 Weak Mutation 261: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp IINC 1
   * 45 de.susebox.jtopas.impl.SequenceStore$PropertyList.<init>(Lde/susebox/jtopas/impl/SequenceStore;Lde/susebox/jtopas/TokenizerProperty;Lde/susebox/jtopas/impl/SequenceStore$PropertyList;)V: root-Branch
   * 46 de.susebox.jtopas.impl.SequenceStore$PropertyList.<init>(Lde/susebox/jtopas/impl/SequenceStore;Lde/susebox/jtopas/TokenizerProperty;)V: root-Branch
   * 47 de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C: root-Branch
   * 48 de.susebox.jtopas.impl.SequenceStore.hasKeywords()Z: root-Branch
   * 49 de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z: I4 Branch 15 IFLE L107 - false
   * 50 de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;: I25 Branch 22 IF_ICMPGE L220 - false
   * 51 de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;: I34 Branch 23 IFLT L223 - false
   * 52 de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;: I37 Branch 24 IF_ICMPGE L223 - false
   * 53 de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;: I6 Branch 33 IFNONNULL L378 - false
   * 54 Weak Mutation 95: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - InsertUnaryOp Negation
   * 55 Weak Mutation 96: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - InsertUnaryOp +1
   * 56 Weak Mutation 97: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - InsertUnaryOp -1
   * 57 Weak Mutation 102: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - ReplaceConstant - 1 -> 0
   * 58 Weak Mutation 101: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - ReplaceComparisonOperator <= -> -1
   * 59 Weak Mutation 98: de.susebox.jtopas.impl.SequenceStore.hasSequenceCommentOrString()Z:107 - DeleteField: _maxLengthI
   * 60 Weak Mutation 152: de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C:206 - InsertUnaryOp Negation
   * 61 Weak Mutation 153: de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C:206 - InsertUnaryOp IINC 1
   * 62 Weak Mutation 154: de.susebox.jtopas.impl.SequenceStore.getStartChar(C)C:206 - InsertUnaryOp IINC -1
   * 63 Weak Mutation 155: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:216 - DeleteStatement: getImages()[Ljava/lang/String;
   * 64 Weak Mutation 156: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:216 - ReplaceConstant - 0 -> 1
   * 65 Weak Mutation 157: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:217 - DeleteStatement: length()I
   * 66 Weak Mutation 158: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:218 - ReplaceConstant - 0 -> 1
   * 67 Weak Mutation 159: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:218 - DeleteStatement: charAt(I)C
   * 68 Weak Mutation 150: de.susebox.jtopas.impl.SequenceStore.hasKeywords()Z:175 - DeleteStatement: hasSequenceCommentOrString()Z
   * 69 Weak Mutation 171: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:221 - InsertUnaryOp Negation
   * 70 Weak Mutation 170: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - ReplaceComparisonOperator >= -> -1
   * 71 Weak Mutation 175: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC 1
   * 72 Weak Mutation 174: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp Negation
   * 73 Weak Mutation 173: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:221 - InsertUnaryOp IINC -1
   * 74 Weak Mutation 172: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:221 - InsertUnaryOp IINC 1
   * 75 Weak Mutation 163: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp -1
   * 76 Weak Mutation 162: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp +1
   * 77 Weak Mutation 161: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp Negation
   * 78 Weak Mutation 160: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:218 - DeleteStatement: getStartChar(C)C
   * 79 Weak Mutation 167: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp IINC -1
   * 80 Weak Mutation 166: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp IINC 1
   * 81 Weak Mutation 165: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:220 - InsertUnaryOp Negation
   * 82 Weak Mutation 186: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - ReplaceComparisonOperator >= -> -1
   * 83 Weak Mutation 187: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp Negation
   * 84 Weak Mutation 188: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp IINC 1
   * 85 Weak Mutation 189: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:224 - InsertUnaryOp IINC -1
   * 86 Weak Mutation 176: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC -1
   * 87 Weak Mutation 177: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - ReplaceComparisonOperator < -> !=
   * 88 Weak Mutation 182: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC -1
   * 89 Weak Mutation 183: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - DeleteField: DIRECT_INDEX_COUNTC
   * 90 Weak Mutation 180: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp Negation
   * 91 Weak Mutation 181: de.susebox.jtopas.impl.SequenceStore.addSpecialSequence(Lde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:223 - InsertUnaryOp IINC 1
   * 92 Weak Mutation 254: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - DeleteField: _asciiArray[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 93 Weak Mutation 255: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp Negation
   * 94 Weak Mutation 258: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - ReplaceComparisonOperator != null -> = null
   * 95 Weak Mutation 259: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - DeleteField: _asciiArray[Lde/susebox/jtopas/impl/SequenceStore$PropertyList;
   * 96 Weak Mutation 256: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp IINC 1
   * 97 Weak Mutation 257: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:378 - InsertUnaryOp IINC -1
   * 98 Weak Mutation 262: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp IINC -1
   * 99 Weak Mutation 260: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp Negation
   * 100 Weak Mutation 261: de.susebox.jtopas.impl.SequenceStore.insertDirect(CLde/susebox/jtopas/TokenizerProperty;)Lde/susebox/jtopas/TokenizerProperty;:379 - InsertUnaryOp IINC 1
   */
  @Test
  public void test1()  throws Throwable  {
      SequenceStore sequenceStore0 = new SequenceStore(true);
      String[] stringArray0 = new String[22];
      stringArray0[0] = "O/tkJ\"cZ";
      Object object0 = new Object();
      TokenizerProperty tokenizerProperty0 = new TokenizerProperty((int) 'S', stringArray0, object0, (int) 'S', (int) 'S');
      sequenceStore0.addSpecialSequence(tokenizerProperty0);
      boolean boolean0 = sequenceStore0.hasKeywords();
      assertEquals(8, sequenceStore0.getSequenceMaxLength());
      assertEquals(true, boolean0);
  }
}
