/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.dbi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.dbi.EnvironmentImpl;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseImpl_1 {


  //Test case number: 1
  /*
   * 14 covered goals:
   * 1 Weak Mutation 37: com.sleepycat.je.dbi.DatabaseImpl.getDebugName()Ljava/lang/String;:149 - DeleteField: debugDatabaseNameLjava/lang/String;
   * 2 Weak Mutation 108: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - DeleteStatement: getRootLsn()J
   * 3 Weak Mutation 106: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - ReplaceConstant - 0 -> 1
   * 4 Weak Mutation 107: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - DeleteField: treeLcom/sleepycat/je/tree/Tree;
   * 5 Weak Mutation 105: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - ReplaceConstant - 0 -> 1
   * 6 com.sleepycat.je.dbi.DatabaseImpl.setDebugDatabaseName(Ljava/lang/String;)V: root-Branch
   * 7 com.sleepycat.je.dbi.DatabaseImpl.countRecords()J: root-Branch
   * 8 com.sleepycat.je.dbi.DatabaseImpl.getDebugName()Ljava/lang/String;: root-Branch
   * 9 com.sleepycat.je.dbi.DatabaseImpl.getDbEnvironment()Lcom/sleepycat/je/dbi/EnvironmentImpl;: root-Branch
   * 10 Weak Mutation 37: com.sleepycat.je.dbi.DatabaseImpl.getDebugName()Ljava/lang/String;:149 - DeleteField: debugDatabaseNameLjava/lang/String;
   * 11 Weak Mutation 108: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - DeleteStatement: getRootLsn()J
   * 12 Weak Mutation 106: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - ReplaceConstant - 0 -> 1
   * 13 Weak Mutation 107: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - DeleteField: treeLcom/sleepycat/je/tree/Tree;
   * 14 Weak Mutation 105: com.sleepycat.je.dbi.DatabaseImpl.countRecords()J:445 - ReplaceConstant - 0 -> 1
   */
  @Test
  public void test1()  throws Throwable  {
      DatabaseImpl databaseImpl0 = new DatabaseImpl();
      databaseImpl0.setDebugDatabaseName("S1RD)r='b8p");
      try {
        databaseImpl0.countRecords();
        fail("Expecting exception: DatabaseException");
      } catch(DatabaseException e) {
        /*
         * environmentImpl is null for target db S1RD)r='b8p
         */
      }
  }
}
