/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.dbi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.dbi.DbTree;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.tree.NameLN;
import com.sleepycat.je.txn.Locker;
import java.util.HashMap;
import java.util.Map;

@RunWith(EvoSuiteRunner.class)
public class TestDbTree_8 {


  //Test case number: 8
  /*
   * 21 covered goals:
   * 1 Weak Mutation 190: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:571 - ReplaceComparisonOperator <= -> ==
   * 2 Weak Mutation 189: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:571 - DeleteStatement: mapContainsKey(Ljava/util/Map;Ljava/lang/Object;)I
   * 3 Weak Mutation 196: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:575 - DeleteStatement: getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;
   * 4 Weak Mutation 195: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:575 - ReplaceConstant - 1 -> 0
   * 5 Weak Mutation 194: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:575 - InsertUnaryOp Negation
   * 6 Weak Mutation 205: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - DeleteStatement: equals(Ljava/lang/Object;)Z
   * 7 Weak Mutation 204: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - DeleteStatement: getId()Lcom/sleepycat/je/dbi/DatabaseId;
   * 8 Weak Mutation 206: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - ReplaceComparisonOperator == -> !=
   * 9 Weak Mutation 203: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - DeleteField: nameDatabaseLcom/sleepycat/je/dbi/DatabaseImpl;
   * 10 com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;: I5 Branch 36 IFLE L571 - true
   * 11 com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;: I7 Branch 37 IFEQ L590 - true
   * 12 com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;: I20 Branch 38 IFEQ L593 - true
   * 13 Weak Mutation 190: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:571 - ReplaceComparisonOperator <= -> ==
   * 14 Weak Mutation 189: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:571 - DeleteStatement: mapContainsKey(Ljava/util/Map;Ljava/lang/Object;)I
   * 15 Weak Mutation 205: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - DeleteStatement: equals(Ljava/lang/Object;)Z
   * 16 Weak Mutation 204: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - DeleteStatement: getId()Lcom/sleepycat/je/dbi/DatabaseId;
   * 17 Weak Mutation 206: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - ReplaceComparisonOperator == -> !=
   * 18 Weak Mutation 203: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;:593 - DeleteField: nameDatabaseLcom/sleepycat/je/dbi/DatabaseImpl;
   * 19 Weak Mutation 196: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:575 - DeleteStatement: getDb(Lcom/sleepycat/je/dbi/DatabaseId;JZLjava/lang/String;)Lcom/sleepycat/je/dbi/DatabaseImpl;
   * 20 Weak Mutation 195: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:575 - ReplaceConstant - 1 -> 0
   * 21 Weak Mutation 194: com.sleepycat.je.dbi.DbTree.getDb(Lcom/sleepycat/je/dbi/DatabaseId;JLjava/util/Map;)Lcom/sleepycat/je/dbi/DatabaseImpl;:575 - InsertUnaryOp Negation
   */
  @Test
  public void test8()  throws Throwable  {
      DbTree dbTree0 = new DbTree();
      assertNotNull(dbTree0);
      
      DatabaseId databaseId0 = DbTree.NAME_DB_ID;
      HashMap<DbTree, NameLN> hashMap0 = new HashMap<DbTree, NameLN>();
      // Undeclared exception!
      try {
        dbTree0.getDb(databaseId0, (-1710L), (Map) hashMap0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
