/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.dbi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.dbi.DbTree;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.log.LogException;
import com.sleepycat.je.tree.DIN;
import com.sleepycat.je.tree.NameLN;
import com.sleepycat.je.tree.Tree;
import java.io.File;
import java.util.Properties;

@RunWith(EvoSuiteRunner.class)
public class TestEnvironmentImpl_6 {


  //Test case number: 6
  /*
   * 8 covered goals:
   * 1 Weak Mutation 190: com.sleepycat.je.dbi.EnvironmentImpl.getFileManager()Lcom/sleepycat/je/log/FileManager;:1044 - DeleteField: fileManagerLcom/sleepycat/je/log/FileManager;
   * 2 com.sleepycat.je.dbi.EnvironmentImpl.logMapTreeRoot()V: root-Branch
   * 3 com.sleepycat.je.dbi.EnvironmentImpl.createDaemons()V: root-Branch
   * 4 com.sleepycat.je.dbi.EnvironmentImpl.getFileManager()Lcom/sleepycat/je/log/FileManager;: root-Branch
   * 5 com.sleepycat.je.dbi.EnvironmentImpl.getLogManager()Lcom/sleepycat/je/log/LogManager;: root-Branch
   * 6 com.sleepycat.je.dbi.EnvironmentImpl.<init>(Ljava/io/File;Lcom/sleepycat/je/EnvironmentConfig;)V: I93 Branch 2 IFNE L210 - true
   * 7 com.sleepycat.je.dbi.EnvironmentImpl.<init>(Ljava/io/File;Lcom/sleepycat/je/EnvironmentConfig;)V: I151 Branch 4 IFEQ L232 - false
   * 8 Weak Mutation 190: com.sleepycat.je.dbi.EnvironmentImpl.getFileManager()Lcom/sleepycat/je/log/FileManager;:1044 - DeleteField: fileManagerLcom/sleepycat/je/log/FileManager;
   */
  @Test
  public void test6()  throws Throwable  {
      File file0 = new File("/");
      Properties properties0 = new Properties();
      EnvironmentConfig environmentConfig0 = new EnvironmentConfig(properties0);
      environmentConfig0.setAllowCreate(true);
      EnvironmentImpl environmentImpl0 = null;
      try {
        environmentImpl0 = new EnvironmentImpl(file0, environmentConfig0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
