/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.dbi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.dbi.INList;
import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.DIN;
import com.sleepycat.je.tree.IN;
import java.util.SortedSet;

@RunWith(EvoSuiteRunner.class)
public class TestINList_4 {


  //Test case number: 4
  /*
   * 5 covered goals:
   * 1 Weak Mutation 23: com.sleepycat.je.dbi.INList.tailSet(Lcom/sleepycat/je/tree/IN;)Ljava/util/SortedSet;:218 - DeleteField: insLjava/util/SortedSet;
   * 2 Weak Mutation 24: com.sleepycat.je.dbi.INList.tailSet(Lcom/sleepycat/je/tree/IN;)Ljava/util/SortedSet;:218 - DeleteStatement: tailSet(Ljava/lang/Object;)Ljava/util/SortedSet;
   * 3 com.sleepycat.je.dbi.INList.tailSet(Lcom/sleepycat/je/tree/IN;)Ljava/util/SortedSet;: root-Branch
   * 4 Weak Mutation 23: com.sleepycat.je.dbi.INList.tailSet(Lcom/sleepycat/je/tree/IN;)Ljava/util/SortedSet;:218 - DeleteField: insLjava/util/SortedSet;
   * 5 Weak Mutation 24: com.sleepycat.je.dbi.INList.tailSet(Lcom/sleepycat/je/tree/IN;)Ljava/util/SortedSet;:218 - DeleteStatement: tailSet(Ljava/lang/Object;)Ljava/util/SortedSet;
   */
  @Test
  public void test4()  throws Throwable  {
      INList iNList0 = new INList((EnvironmentImpl) null);
      DIN dIN0 = new DIN();
      SortedSet<?> sortedSet0 = iNList0.tailSet((IN) dIN0);
      assertNotNull(sortedSet0);
      assertEquals(4294969208L, dIN0.getNextNodeId());
  }
}
