/*
 * This file was automatically generated by EvoSuite
 */

package com.sleepycat.je.dbi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.dbi.DatabaseId;
import com.sleepycat.je.dbi.DatabaseImpl;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.dbi.INList;
import com.sleepycat.je.log.LogException;
import com.sleepycat.je.txn.WriteLockInfo;
import java.nio.ByteBuffer;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseImpl_21 {


  //Test case number: 21
  /*
   * 16 covered goals:
   * 1 Weak Mutation 327: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - ReplaceConstant - Exception while trying to load  -> 
   * 2 Weak Mutation 332: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
   * 3 Weak Mutation 333: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: toString()Ljava/lang/String;
   * 4 Weak Mutation 330: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - ReplaceConstant -  Comparator class:  -> 
   * 5 Weak Mutation 331: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 6 Weak Mutation 328: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 7 Weak Mutation 329: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 8 Weak Mutation 326: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1101 - DeleteStatement: newInstance()Ljava/lang/Object;
   * 9 Weak Mutation 325: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1097 - ReplaceComparisonOperator != null -> = null
   * 10 Weak Mutation 327: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - ReplaceConstant - Exception while trying to load  -> 
   * 11 Weak Mutation 332: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
   * 12 Weak Mutation 333: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: toString()Ljava/lang/String;
   * 13 Weak Mutation 330: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - ReplaceConstant -  Comparator class:  -> 
   * 14 Weak Mutation 331: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 15 Weak Mutation 328: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 16 Weak Mutation 329: com.sleepycat.je.dbi.DatabaseImpl.instantiateComparator(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/Comparator;:1104 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   */
  @Test
  public void test21()  throws Throwable  {
      Class<?> class0 = INList.class;
      try {
        DatabaseImpl.instantiateComparator((Class) class0, (String) null);
        fail("Expecting exception: LogException");
      } catch(LogException e) {
        /*
         * Exception while trying to load null Comparator class: java.lang.InstantiationException: com.sleepycat.je.dbi.INList
         */
      }
  }
}
