/*
 * This file was automatically generated by EvoSuite
 */

package org.prevayler.implementation;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Date;
import org.prevayler.Transaction;
import org.prevayler.foundation.Chunk;
import org.prevayler.foundation.serialization.Serializer;
import org.prevayler.foundation.serialization.XStreamSerializer;
import org.prevayler.implementation.Capsule;
import org.prevayler.implementation.TransactionCapsule;
import org.prevayler.implementation.TransactionWithQueryCapsule;

@RunWith(EvoSuiteRunner.class)
public class TestCapsule_4 {


  //Test case number: 4
  /*
   * 20 covered goals:
   * 1 Weak Mutation 13: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - ReplaceConstant - withQuery -> 
   * 2 Weak Mutation 14: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - DeleteStatement: getParameter(Ljava/lang/String;)Ljava/lang/String;
   * 3 Weak Mutation 15: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - DeleteStatement: valueOf(Ljava/lang/String;)Ljava/lang/Boolean;
   * 4 Weak Mutation 16: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - DeleteStatement: booleanValue()Z
   * 5 Weak Mutation 17: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:66 - InsertUnaryOp Negation
   * 6 Weak Mutation 18: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:66 - ReplaceComparisonOperator == -> !=
   * 7 Weak Mutation 19: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:67 - DeleteStatement: getBytes()[B
   * 8 org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;: I11 Branch 1 IFEQ L66 - false
   * 9 Weak Mutation 9: org.prevayler.implementation.Capsule.toChunk()Lorg/prevayler/foundation/Chunk;:60 - DeleteField: _serialized[B
   * 10 Weak Mutation 10: org.prevayler.implementation.Capsule.toChunk()Lorg/prevayler/foundation/Chunk;:61 - ReplaceConstant - withQuery -> 
   * 11 Weak Mutation 11: org.prevayler.implementation.Capsule.toChunk()Lorg/prevayler/foundation/Chunk;:61 - DeleteStatement: valueOf(Z)Ljava/lang/String;
   * 12 Weak Mutation 12: org.prevayler.implementation.Capsule.toChunk()Lorg/prevayler/foundation/Chunk;:61 - DeleteStatement: setParameter(Ljava/lang/String;Ljava/lang/String;)V
   * 13 Weak Mutation 13: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - ReplaceConstant - withQuery -> 
   * 14 Weak Mutation 14: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - DeleteStatement: getParameter(Ljava/lang/String;)Ljava/lang/String;
   * 15 Weak Mutation 15: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - DeleteStatement: valueOf(Ljava/lang/String;)Ljava/lang/Boolean;
   * 16 Weak Mutation 17: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:66 - InsertUnaryOp Negation
   * 17 Weak Mutation 16: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:65 - DeleteStatement: booleanValue()Z
   * 18 Weak Mutation 19: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:67 - DeleteStatement: getBytes()[B
   * 19 Weak Mutation 18: org.prevayler.implementation.Capsule.fromChunk(Lorg/prevayler/foundation/Chunk;)Lorg/prevayler/implementation/Capsule;:66 - ReplaceComparisonOperator == -> !=
   * 20 org.prevayler.implementation.Capsule.toChunk()Lorg/prevayler/foundation/Chunk;: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      TransactionWithQueryCapsule transactionWithQueryCapsule0 = new TransactionWithQueryCapsule(byteArray0);
      Chunk chunk0 = transactionWithQueryCapsule0.toChunk();
      TransactionWithQueryCapsule transactionWithQueryCapsule1 = (TransactionWithQueryCapsule)Capsule.fromChunk(chunk0);
      assertFalse(transactionWithQueryCapsule0.equals(transactionWithQueryCapsule1));
  }
}
