/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas.sef;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.sef.SEFTestPatternMatching;

@RunWith(EvoSuiteRunner.class)
public class TestSEFTestPatternMatching_0 {


  //Test case number: 0
  /*
   * 80 covered goals:
   * 1 Weak Mutation 11: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:174 - ReplaceConstant - 0.95 123 -1 -123123.92382 0,32 +4,001 -123,213 -0 -> 
   * 2 Weak Mutation 12: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:178 - ReplaceConstant - .\-+, -> 
   * 3 Weak Mutation 13: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:178 - DeleteStatement: removeSeparators(Ljava/lang/String;)V
   * 4 Weak Mutation 14: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:179 - ReplaceConstant - [+\-]?[0-9]+\.?[0-9]* -> 
   * 5 Weak Mutation 15: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:179 - DeleteStatement: addPattern(Ljava/lang/String;)V
   * 6 Weak Mutation 17: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:180 - DeleteStatement: addPattern(Ljava/lang/String;)V
   * 7 Weak Mutation 16: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:180 - ReplaceConstant - [+\-]?[0-9]+,?[0-9]* -> 
   * 8 Weak Mutation 18: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:181 - DeleteStatement: setSource(Ljava/io/Reader;)V
   * 9 Weak Mutation 19: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:183 - DeleteStatement: hasMoreToken()Z
   * 10 Weak Mutation 20: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:183 - ReplaceComparisonOperator == -> !=
   * 11 Weak Mutation 21: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:184 - DeleteStatement: nextToken()Lde/susebox/jtopas/Token;
   * 12 Weak Mutation 23: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:186 - DeleteStatement: println(Ljava/lang/Object;)V
   * 13 Weak Mutation 22: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:186 - DeleteField: outLjava/io/PrintStream;
   * 14 Weak Mutation 25: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceConstant - -1 -> 0
   * 15 Weak Mutation 24: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - DeleteStatement: getType()I
   * 16 Weak Mutation 27: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceConstant - -1 -> -2
   * 17 Weak Mutation 26: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceConstant - -1 -> 1
   * 18 Weak Mutation 29: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceComparisonOperator == -> -2
   * 19 Weak Mutation 28: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceComparisonOperator == -> >=
   * 20 Weak Mutation 31: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - Wrong token type  -> 
   * 21 Weak Mutation 34: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getTypeName(I)Ljava/lang/String;
   * 22 Weak Mutation 35: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 23 Weak Mutation 32: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 24 Weak Mutation 33: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getType()I
   * 25 Weak Mutation 38: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getImage()Ljava/lang/String;
   * 26 Weak Mutation 39: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 27 Weak Mutation 36: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant -  for:  -> 
   * 28 Weak Mutation 37: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 29 Weak Mutation 42: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 0
   * 30 Weak Mutation 43: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 1
   * 31 Weak Mutation 40: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: toString()Ljava/lang/String;
   * 32 Weak Mutation 41: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getType()I
   * 33 Weak Mutation 46: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 4
   * 34 Weak Mutation 44: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> -1
   * 35 Weak Mutation 45: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 2
   * 36 Weak Mutation 50: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 1 -> 0
   * 37 Weak Mutation 49: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceComparisonOperator != -> -1
   * 38 de.susebox.jtopas.sef.SEFTestPatternMatching.<init>(Ljava/lang/String;)V: root-Branch
   * 39 de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V: I44 Branch 1 IFEQ L183 - true
   * 40 de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V: I44 Branch 1 IFEQ L183 - false
   * 41 de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V: I60 Branch 2 IF_ICMPEQ L187 - true
   * 42 de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V: I60 Branch 2 IF_ICMPEQ L187 - false
   * 43 de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V: I81 Branch 3 IF_ICMPNE L188 - false
   * 44 Weak Mutation 11: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:174 - ReplaceConstant - 0.95 123 -1 -123123.92382 0,32 +4,001 -123,213 -0 -> 
   * 45 Weak Mutation 12: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:178 - ReplaceConstant - .\-+, -> 
   * 46 Weak Mutation 13: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:178 - DeleteStatement: removeSeparators(Ljava/lang/String;)V
   * 47 Weak Mutation 14: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:179 - ReplaceConstant - [+\-]?[0-9]+\.?[0-9]* -> 
   * 48 Weak Mutation 15: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:179 - DeleteStatement: addPattern(Ljava/lang/String;)V
   * 49 Weak Mutation 17: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:180 - DeleteStatement: addPattern(Ljava/lang/String;)V
   * 50 Weak Mutation 16: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:180 - ReplaceConstant - [+\-]?[0-9]+,?[0-9]* -> 
   * 51 Weak Mutation 19: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:183 - DeleteStatement: hasMoreToken()Z
   * 52 Weak Mutation 18: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:181 - DeleteStatement: setSource(Ljava/io/Reader;)V
   * 53 Weak Mutation 21: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:184 - DeleteStatement: nextToken()Lde/susebox/jtopas/Token;
   * 54 Weak Mutation 20: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:183 - ReplaceComparisonOperator == -> !=
   * 55 Weak Mutation 23: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:186 - DeleteStatement: println(Ljava/lang/Object;)V
   * 56 Weak Mutation 22: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:186 - DeleteField: outLjava/io/PrintStream;
   * 57 Weak Mutation 25: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceConstant - -1 -> 0
   * 58 Weak Mutation 24: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - DeleteStatement: getType()I
   * 59 Weak Mutation 27: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceConstant - -1 -> -2
   * 60 Weak Mutation 26: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceConstant - -1 -> 1
   * 61 Weak Mutation 29: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceComparisonOperator == -> -2
   * 62 Weak Mutation 28: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:187 - ReplaceComparisonOperator == -> >=
   * 63 Weak Mutation 31: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - Wrong token type  -> 
   * 64 Weak Mutation 34: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getTypeName(I)Ljava/lang/String;
   * 65 Weak Mutation 35: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 66 Weak Mutation 32: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 67 Weak Mutation 33: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getType()I
   * 68 Weak Mutation 38: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getImage()Ljava/lang/String;
   * 69 Weak Mutation 39: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 70 Weak Mutation 36: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant -  for:  -> 
   * 71 Weak Mutation 37: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   * 72 Weak Mutation 42: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 0
   * 73 Weak Mutation 43: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 1
   * 74 Weak Mutation 40: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: toString()Ljava/lang/String;
   * 75 Weak Mutation 41: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - DeleteStatement: getType()I
   * 76 Weak Mutation 46: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 4
   * 77 Weak Mutation 44: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> -1
   * 78 Weak Mutation 45: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 3 -> 2
   * 79 Weak Mutation 50: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceConstant - 1 -> 0
   * 80 Weak Mutation 49: de.susebox.jtopas.sef.SEFTestPatternMatching.testNumberPattern()V:188 - ReplaceComparisonOperator != -> -1
   */
  @Test
  public void test0()  throws Throwable  {
      SEFTestPatternMatching sEFTestPatternMatching0 = new SEFTestPatternMatching("l+'");
      sEFTestPatternMatching0.testNumberPattern();
      assertEquals("l+'(de.susebox.jtopas.sef.SEFTestPatternMatching)", sEFTestPatternMatching0.toString());
  }
}
