/*
 * This file was automatically generated by EvoSuite
 */

package de.susebox.jtopas.sef;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.susebox.jtopas.sef.SEFTestTokenizerSource;
import java.io.CharArrayReader;
import java.io.DataInput;
import java.io.DataInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.LineNumberReader;
import java.io.PipedInputStream;
import java.io.Reader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import junit.framework.AssertionFailedError;
import junit.framework.TestCase;
import org.evosuite.testcase.TestCaseExecutor;

@RunWith(EvoSuiteRunner.class)
public class TestSEFTestTokenizerSource_2 {


  //Test case number: 2  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        TestCase.assertEquals((-365L), (-1L));
        fail("Expecting exception: AssertionFailedError");
      } catch(AssertionFailedError e) {
        /*
         * expected:<-365> but was:<-1>
         */
      }
  }
}
